### PR TITLE
Update Service Mesh Icon with Pattern's icon

### PR DESCRIPTION
**Pull request by Muhu-Muza**
**Description**

This PR fixes [#1744](https://github.com/meshery/meshery.io/issues/1744)
**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by vishalvivekm — CHANGES_REQUESTED** [review]
@Muhu-Muza What are these changes for ? can you please explain?
We just need to update the svg icon.

**Comment by vishalvivekm** [comment]
More over the service mesh Icon is still not updated with Pattern's icon ( mentioned in the issue )
### Deploy Preview: https://deploy-preview-1746--mesheryio-preview.netlify.app/catalog
image

**Comment by vishalvivekm** [comment]
@Muhu-Muza Let's discuss this on Websites's call on Monday. I've added this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Comment by leecalcote** [comment]
Thanks, @Muhu-Muza!

@iArchitSharma, when you have a moment, will you offer feedback / review?

**Comment by Muhu-Muza** [comment]
@vishalvivekm , I only updated  the service mesh Icon with the pattern's icon.
I used  the  patterns  svg  that you provided earlier.
pattern

**Pull request closed without merging**
