### PR TITLE
Update homePage.html

### PR DESCRIPTION
**Pull request by aditi5050**
The character of the first word of the website  should be capitalized so that is what I did this solve issue this solve issue #6397

### CODE REVIEW

**Comment by aditi5050** [comment]
pr2
pr1

**Comment by Nikhil-Ladha** [comment]
I don't see any issue opened for this, can you please point me to it?
Secondly, the lowercase of `the` was intentional IIRC, so I don't see any potential issue around it at all.

**Comment by aditi5050** [comment]
okay got it :) can you please assign some work to deal with or contribute to

**Comment by aditi5050** [comment]
html, css , javascript ,||c++|| python

**Review by legendarykamal — COMMENTED** [review]
This change wasn't needed, as this was completely intentional. 
Please make sure to follow the practice of raising an issue first , getting some triage over it and then proposing a solution, will help save your and reviewer's time.

Alternatively you can look for existing issues that have a `help wanted` label and you can ask under those issues to work on them.

**Pull request closed without merging**
