### PR TITLE
feature section margin fix

### PR DESCRIPTION
**Pull request by NikhilSharma03**
Signed-off-by: Nikhil <nikhilsharmamusic2000@gmail.com>

**Description**
There was an issue with the margin around the feature list

## Current State
Old

Fixed the margin around the feature list
## After Changes
New

**Notes for Reviewers**
Let me know if any adjustments are required.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
@NikhilSharma03 Is it possible to align these text in the same line?
image

**Comment by NikhilSharma03** [comment]
@adithyaakrishna yeah sure.

**Comment by adithyaakrishna** [comment]
> @adithyaakrishna yeah sure.

Also if possible the last column one also, this would make it look NEAT 👀

**Comment by NikhilSharma03** [comment]
@adithyaakrishna Can you please confirm? let me know if that okay i will push it.Thank you

**Comment by NikhilSharma03** [comment]
@adithyaakrishna Can you please confirm? let me know if that's okay i will push it. Thank you.

**Comment by NikhilSharma03** [comment]
@adithyaakrishna Can you please confirm? let me know if that's okay I will push it. Thank you.

Screenshot from 2021-05-27 22-54-56

**Comment by adithyaakrishna** [comment]
@NikhilSharma03 Wow! Looks NEAT 💯🎉

**Review by adithyaakrishna — APPROVED** [review]

**Comment by Ayush-Khandelwal-007** [comment]
Hey @adithyaakrishna , if I am not the 1st block in each card's white block is heading and further below blocks are the description, So rather than having different blocks for these should we go for a bulleted list with left text align as the number of points for not equal , that would look much neat I think.

**Comment by adithyaakrishna** [comment]
@NikhilSharma03 Any updates here?

**Comment by NikhilSharma03** [comment]
@adithyaakrishna Done on my part. 

## After Changes

119871200-d908a780-bf3f-11eb-841f-17f229c47309

## Note
Was waiting for approval.

**Comment by NikhilSharma03** [comment]
## After Changes

Screenshot from 2021-06-30 19-18-48

**Review by Ayush-Khandelwal-007 — APPROVED** [review]
LGTM 🥳

**Review by adithyaakrishna — APPROVED** [review]
LGTM🎉
Great Work @NikhilSharma03 🎈

**Pull request merged**
