### PR TITLE
Updates on the catalog

### PR DESCRIPTION
**Pull request by asubedy**
Signed-off-by: asubedy <frexpe@pm.me>

**Description**
This PR fixes following Issues:
1. Center the Cloud Native Catalog Heading and sub heading2. 
2. Moving Circuit Breaker to Resiliency from Traffic Management
3. Related Card is now clickable
4. Card chip also darkens on over now
5. Latest Updated and Version text added on individual page
6. Menu on mobile view is now right aligned.
7. Overflowing pattern name on card is now wrapped
8. JWT enabled and JWT-filter moved to JWT from WASM
This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
1. ✅ 
1. ✅
1. ❌ Clickable Related Patterns card. (I'm using Safari).
1. ✅
1. ✅
1. ✅
1. ✅

https://user-images.githubusercontent.com/7570704/179310422-1e3cd9fc-a28d-4e84-8bc7-4e0d7ab1c69f.mov

**Comment by leecalcote** [comment]
@asubedy almost there...

**Comment by asubedy** [comment]
@leecalcote the clickable related card issue is due to interference of other elements on the single page. Once the flex box implementation is through, the cards will be clickable easily.

**Comment by leecalcote** [comment]
That’s good to hear.

**Pull request merged**
