### PR TITLE
Dark mode first preview.

### LINKED ISSUE #869: Dark mode.
**Current Behavior**
The website needs a dark mode.

**Desired Behavior**

**Screenshots / Mockups**

**Alternatives**

---
<h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Krishna2323**
Signed-off-by: krishna2323 <belivethatkg@gmail.com>

**Description**
This is just for preview, I left some bugs on purpose for hacktoberfest.
Please suggest me some of my mistakes to improve the design,
I am working on talks-and-presentations page.

This PR fixes #869

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Krishna2323** [comment]
@leecalcote, I am really curious to hear some critics about my lovely gradients🤪.

**Comment by Krishna2323** [comment]
@legendarykamal @Nikhil-Ladha @debo19 @asubedy @Revolyssup, Please help me improve this by reviewing it.

**Comment by adithyaakrishna** [comment]
@Krishna2323 Any update on this?

**Comment by leecalcote** [comment]
@Krishna2323 there's much merit to what is in this PR. I consider that we should be pushing forward with it. We can displace the Meshery Adapters table with the integrations periodic table from https://github.com/meshery/meshery.io/issues/889, too.

**Comment by leecalcote** [comment]
@Krishna2323 heads-up: there are a number of merge conflicts.

**Comment by YashKamboj** [comment]
Screenshot 2022-11-18 at 3 31 40 PM
I think you changed the color of the CNCF logo , it is visible in dark mode but not in light mode

**Review by leecalcote — CHANGES_REQUESTED** [review]
https://github.com/meshery/meshery.io/pull/870/files#diff-fb5c7d910fbbece42f653663960c0b1c1f5a02a95e8e0c070c3b410bcd6f0086 This PNG needs to be left as-is.

**Comment by leecalcote** [comment]
Merge conflicts...

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
