### PR TITLE
I've updated the index.html file

### PR DESCRIPTION
**Pull request by GaurPeeyush**
I've added the landscape image to the page.

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Hi @GaurPeeyush, which issue is this fixing? 

It seems that the entire index.html is showing as changed. Can you highlight the specific areas that you changed?

You'll need to sign-off on your commit. See the instructions above.

**Comment by leecalcote** [comment]
@GaurPeeyush just following up...

**Comment by GaurPeeyush** [comment]
@leecalcote I added a landscape image to the page.

**Comment by GaurPeeyush** [comment]
@leecalcote 
I've added a landscape image to the page, in line 343.

**Comment by DelusionalOptimist** [comment]
Hey @GaurPeeyush so sorry this has been hanging for so long.
I guess you were trying to tackle https://github.com/meshery/meshery.io/issues/410 but a PR for that was merged long back. Sorry, I'll have to close this.
Please feel free to comment on other issues labelled as "help-wanted" or "good first issue".
Thanks!

**Comment by leecalcote** [comment]
Thank you, @GaurPeeyush and @DelusionalOptimist

**Pull request closed without merging**
