### PR TITLE
[blog] Copy SMI Conformance blog from smi-spec.io

### LINKED ISSUE #460: [Blog] Copy SMI Conformance blog from smi-spec.io
**Current State of the Meshery.io site**
[This blog post](https://smi-spec.io/blog/validating-smi-conformance-with-meshery/) can be copied and posted on meshery.io.

**Desired State of the Meshery.io site**
The blog post, including images, should be posted on smi-spec.io and https://meshery.io/blog

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

### PR DESCRIPTION
**Pull request by josephmidura**
**Description**

This PR fixes #460 

**Notes for Reviewers**
Screen recording below

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by josephmidura** [comment]
Here's a [preview](https://user-images.githubusercontent.com/11523557/120417681-dda8d380-c324-11eb-9abd-cae991afdb00.mov
).

**Review by alphaX86 — COMMENTED** [review]
LGTM so far....

But.... The name is printed two times...
image

Is this intended? 😅😅 Or am I asking too much?

**Comment by josephmidura** [comment]
No, you're not asking too much. I thought that the other post on the Meshery page had a duplicate author name as well. I removed the duplicate author name.

Screen Shot 2021-06-04 at 8 38 21 PM

**Review by alphaX86 — APPROVED** [review]
LGTM! Good to go

**Comment by josephmidura** [comment]
@leecalcote You mentioned this topic at today's community meeting.

**Comment by leecalcote** [comment]
Fantastic. 😄

**Pull request merged**
