### PR TITLE
made the input area responsive  

### LINKED ISSUE #1291: Making the community news letter card responsive
#### Current State of the Meshery.io site

Currently the Community news letter card is not responsive
Screenshot 2023-07-12 at 9 19 33 PM

#### Desired State of the Meshery.io site

The input fields should be little small and should have less padding, the font size should be small too.
---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by ShivangRawat30**
**Description**
made the input fields of community newsletter card responsive.

This PR fixes #1291 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@ShivangRawat30 

Let's discuss it on the websites call.
Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

**Review by thisiskaransgit — COMMENTED** [review]
@ShivangRawat30, thank you for this quick fix, the changes look good 🎉 
While you are on this page, please update the `href` for engage button in the discussion forum card. The button should redirect us to [discuss.layer.io](https://discuss.layer5.io/)

**Review by HarshDobariya79 — COMMENTED** [review]
Thank you for this PR @ShivangRawat30. Nice work. Just one thing I've noticed is from `840px` to `910px` the placeholder text is not properly visible. If possible can you look into it?

**Comment by ShivangRawat30** [comment]
Hey @HarshDobariya79 this fix also works on screen width from `840px` to `910px`.

**Comment by ShivangRawat30** [comment]
Hey @thisiskaransgit I think this has been already fixed because the card is redirecting us to [discuss.layer.io](https://discuss.layer5.io/)

**Comment by HarshDobariya79** [comment]
> Hey @HarshDobariya79 this fix also works on screen width from `840px` to `910px`.

Can you please confirm once again? Because I'm not able to see that.
image

**Comment by ShivangRawat30** [comment]
sorry @HarshDobariya79  there was a slight mistake, I've made some changes now.

**Review by Chadha93 — APPROVED** [review]
LGTM @ShivangRawat30

**Pull request merged**
