### PR TITLE
Enhanced The scrollbar 

### LINKED ISSUE #1067: [UI] Enhance the styling of the scroll bar
#### Current Behavior
The default scrollbar in the Edge browser does not meet the desired aesthetic standards, prompting the need to enhance its appearance through appropriate design measures.

#### Desired Behavior
Revamp the scroll bar by implementing a new design that aligns with the aesthetic requirements.

#### Implementation
Incorporate CSS properties for the scroll bar to ensure consistency in appearance across all browsers.

#### Mockups
image

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Gautam-666**
**Description**

This PR fixes #1067

**Notes for Reviewers**
Enhanced The Scrollbar. 
Screenshot (26)
Screenshot (27)

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by samyakshah3008 — APPROVED** [review]
Great work, looks good to merge!

**Review by thisiskaransgit — CHANGES_REQUESTED** [review]
We already have predefined styles, use them instead of creating your own.

**Comment by Gautam-666** [comment]
@thisiskaransgit One thing to consider is that predefined styles lack a perfect color combination for the scrollbar, which can result in visibility issues in both light mode and dark mode.

However, I have taken the initiative to add images with a predefined style. If they meet your requirements, I will be more than happy to commit them.
Screenshot (26)
Screenshot (27)

As you can see color combination looks perfect in light mode but after scrolling it matches with the background and is not visible. 
Screenshot (32)

**Review by HarshDobariya79 — APPROVED** [review]
Nice job @Gautam-666. Looks good to me.

**Comment by vishalvivekm** [comment]
@Gautam-666 
Let's discuss this in websites call. Add this as agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would :)

**Review by anshgoyalevil — APPROVED** [review]
Changes look good to me.

**Comment by leecalcote** [comment]
yay! 🎈 @Gautam-666

**Pull request merged**
