### PR TITLE
Made changes to the twitter logo on community page by updating svg files in assets/images/logos

### LINKED ISSUE #1442: Twitter logo need to be Updated to X
### Description

Twitter logo in the last section of [meshery.io/community](https://meshery.io/community/#:~:text=meetings%20and%20events.-,Add%20Calendar,-Community) need to be updated to X

---
<h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Himanshu1801**
**Description**
Twitter logo in the last section of [meshery.io/community](https://meshery.io/community/#:~:text=meetings%20and%20events.-,Add%20Calendar,-Community) need to be updated to X

This PR fixes #1442 

**Notes for Reviewers**
Made changes to the twitter logo on community page by editting the svg files.

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by abhijeetgauravm** [comment]
Hey @Himanshu1801   Let's discuss this on website call tomorrow at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by abhijeetgauravm** [comment]
Hey @Himanshu1801 really appreciate your enthusiasm to contribute , However please refrain from creating direct PRs without getting assigned first .

**Review by adi-ray — CHANGES_REQUESTED** [review]
- Add little bit of spacing between the icons.
- Make the twitter logo bold (matching other icons).

**Comment by Himanshu1801** [comment]
Hi @adi-ray I have made the required changes, can you please review it.

**Review by vishalvivekm — APPROVED** [review]
LGTM.
Thanks @Himanshu1801

**Pull request merged**
