### PR TITLE
fixed the width of form container

### LINKED ISSUE #998: [UI] Fix the width of form container on programs page for Small Media Devices.
### Description
The form container is overflowing on the programs page on the small media devices.
form

### Expected Behavior

On Small media devices the with should be auto.
formfixed

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by gyancodes**
Signed-off-by: Gyan Prakash Tiwari <gyanprakasheng@gmail.com>

**Description**
- [x] Make the form container width auto.
- [x] Make the input text box width auto

This PR fixes #998

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by GaganpreetKaurKalsi — CHANGES_REQUESTED** [review]
How about making input fields span full available width, @gyancodes ?

**Current :-** 
image

**Proposed :-** 
image

**Review by GaganpreetKaurKalsi — CHANGES_REQUESTED** [review]
image

Changing the width from `80%` to `100%` for `.NAME` should solve the issue.

**Comment by leecalcote** [comment]
@tinniaru3005 would you like to review this?

**Review by tinniaru3005 — APPROVED** [review]
LGTM! :)

**Comment by Chadha93** [comment]
@gyancodes Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by gyancodes** [comment]
@Chadha93 any update regarding this pr

**Review by Chadha93 — APPROVED** [review]
LGTM

**Comment by Chadha93** [comment]
@gyancodes Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Pull request merged**
