### PR TITLE
Fixed the broken blog link

### PR DESCRIPTION
**Pull request by bhargavmungara**
Signed-off-by: Bhargav Mungara bwe2409@gmail.com

Fixes #699

### CODE REVIEW

**Comment by bhargavmungara** [comment]
I don't know what is wrong this time

**Comment by Akshit42-hue** [comment]
Hey @bhargavmungara you have made changes in gemfile.lock please revert those changes

**Review by Abhijay007 — COMMENTED** [review]
@bhargavmungara please revert changes of `Gemfile.lock` file as suggested by @Akshit42-hue and please sign DCO

**Comment by Abhijay007** [comment]
@bhargavmungara there are two PRs  #700 and #699 covering the same issue which is #698 so it is better to close one of these PRs.

**Comment by debo19** [comment]
@bhargavmungara this issue was fixed. You can go through any other [good first issues](https://github.com/meshery/meshery.io/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) for now.

**Comment by YashKamboj** [comment]
This issue is solved from pr #701

**Pull request closed without merging**
