### PR TITLE
Banner section(section-1) for community page

### LINKED ISSUE #1271: New page design implementation for Contributors page
#### Current State of the Meshery.io site

Currently the page https://meshery.io/community/ is empty

#### Desired State of the Meshery.io site

Need to implement the mockup for this page from [Figma design](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=16435%3A39494&mode=design&t=6qls5jOGn5gJKKgm-1)
Contributors can pick separate section to implement the page fast

- [ ] Section-1: Banner section

image

- [ ] Section- 2: Resources section

image

- [ ] Section-3: Handbook section

image

- [ ] Section-4: Discuss forum section

image

- [ ] Section-5: Meshmate section

image

- [ ] Section-6: Calendar section"

image

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Gautam-04**
**Description**

This PR fixes #1271

**Notes for Reviewers**
Screenshot (43)
Screenshot (44)

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks for this, @Gautam-666. Please change the following:

1. remove changes to gemfile.lock.
2. use SVG for the "globe" banner.
3. use the proper font.

Please also consider changing your username, which I find personally offensive.

**Comment by Gautam-666** [comment]
@leecalcote Regarding the 2nd point. The banner images were available only in the png form in the Figma file as well as in the assets provided.

**Comment by leecalcote** [comment]
> @leecalcote Regarding the 2nd point. The banner images were available only in the png form in the Figma file as well as in the assets provided.

Having created this graphic, I know that there is an SVG version available in the community.

Have you given thought to my other request regarding your offensive username?

**Comment by Gautam-666** [comment]
@leecalcote  Update the files from png to SVG.

I can change my username but will have to change it from multiple locations so will need some time for it. Btw just wanted to know what's offensive🫣

**Comment by leecalcote** [comment]
The number 666 is used to signify the devil, the antichrist, or evil in general.

**Comment by leecalcote** [comment]
This is the same explanation that I have offered in the community Slack, previously.

**Comment by Gautam-04** [comment]
> The number 666 is used to signify the devil, the antichrist, or evil in general.

I didn't know about this one I kept it like that because it was my birth date. No issues I have changed now😊

**Comment by sudhanshutech** [comment]
@Gautam-04 why there is an unwanted yellow lining, please remove that
image

**Comment by Gautam-04** [comment]
> @Gautam-04 why there is an unwanted yellow lining, please remove that image

isn't that part of the Figma file?
Screenshot (47)

**Comment by sudhanshutech** [comment]
> > @Gautam-04 why there is an unwanted yellow lining, please remove that image
> 
> isn't that part of the Figma file? Screenshot (47)

no no we don't need that , it was made to make understand something, you can remove it

**Comment by Gautam-04** [comment]
Ohk i will do it.

**Comment by Gautam-04** [comment]
@sudhanshutech  removed the yellow arrow

**Comment by Gautam-04** [comment]
I have deleted the gemfile if that works otherwise have to create a new PR
because change gemfile can't be revert(system issues)

**Comment by thisiskaransgit** [comment]
@Gautam-04 merge conflicts...

**Comment by leecalcote** [comment]
Merge conflict resolved.

**Comment by Gautam-04** [comment]
Thank you Lee for solving the merge conflict.

**Review by sudhanshutech — APPROVED** [review]
for now looks good, let raise another issue for any improvement if needed. We need this page up so we can consider to merge this

**Review by thisiskaransgit — APPROVED** [review]
We will be soon moving ahead with merging each section. Looks good to merge, thank you for your contribution 🎉

**Review by Chadha93 — APPROVED** [review]
LGTM, thank you, everyone.

**Pull request merged**
