### PR TITLE
Update Go version to 1.23 and replace deprecated packages

### PR DESCRIPTION
**Pull request by devhindo**
Upgrade the Go version across multiple modules and update deprecated package usages to ensure compatibility with the latest standards. Increment design versions in the catalog to reflect these changes.

fixes: meshery/meshery#12829

### CODE REVIEW

**Comment by devhindo** [comment]
@leecalcote

**Review by winkletinkle — DISMISSED** [review]

**Comment by leecalcote** [comment]
@devhindo, will you have a look into these merge conflicts? Once resolved, let's be sure that we review and merge this PR before the next daily workflow kicks off, causing additional conflicts.

**Review by leecalcote — DISMISSED** [review]
Thanks for undertaking this issue, @devhindo

**Comment by devhindo** [comment]
done! conflicts solved @leecalcote

**Review by leecalcote — DISMISSED** [review]
Thanks, @devhindo!

**Pull request closed without merging**
