### PR TITLE
[BUG-1664] Resolve Meshery logo spacing and alignment issue

### PR DESCRIPTION
**Pull request by Muhammed-Moinuddin**
Remove extra margin, padding, and add align-items property.

**Description**

This PR fixes # 1664

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@Muhammed-Moinuddin 
Let's discuss this on websites call. Add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would :)

**Comment by vishalvivekm** [comment]
Also please sign off your commits, follow this: https://github.com/meshery/meshery.io/pull/1665/checks?check_run_id=23019470951

**Comment by Muhammed-Moinuddin** [comment]
> vishalvivekm
Wasn't able to join the meeting but yeah let's discuss this in DM.

**Review by leecalcote — COMMENTED** [review]
Please resync your fork, so that only your commits are included in this PR.

**Comment by Muhammed-Moinuddin** [comment]
> Please resync your fork, so that only your commits are included in this PR.

In order to synchronize it, I just discarded the commit. I need to open a new pull request now? Right?
Kindly guide me about it a bit.

**Pull request closed without merging**
