### PR TITLE
Added alt tags to all images for improved accessibility and SEO

### LINKED ISSUE #1369: Add alt tags to all images for improved accessibility and SEO
### Description

Alt attributes within `` tags are used by search engines to understand the contents of your images. They provide a textual description of images, allowing visually impaired users to understand the content and search engines to index images accurately.
Neglecting them will negatively affect the ranking in search results
### Expected Behavior

add alt tags to all images on the following pages. Alt tags should be descriptive and concise, conveying the purpose or context of the image without being overly verbose.
1. homepage
2. programs page
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by blindaks**
**Description**
https://github.com/meshery/meshery.io/pull/1380

This PR fixes #1369 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by saurabh100ni** [comment]
let's discuss this item on today's website meeting,
please add this agenda in the docs: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk

**Comment by blindaks** [comment]
@saurabh100ni Please merge this PR

**Comment by saurabh100ni** [comment]
@Mohith234 @sudhanshutech //

**Comment by blindaks** [comment]
@Mohith234 @sudhanshutech Please review my PR

**Review by sudhanshutech — APPROVED** [review]
LGTM

**Pull request merged**
