### PR TITLE
Adding vertical slider for showcasing Meshery Extension

### LINKED ISSUE #1477: Add horizontal slider for showcasing Meshery Extension.
#### Current State of the Meshery.io site
Screenshot 2023-10-26 at 9 54 36 PM

The screenshot and text doesn't describe the capability of Meshery Extension to its fullest.
#### Desired State of the Meshery.io site

Add a vertical slider instead of the current screenshot. The left hand side of the slider would contain a K8s manifest for a multi-tier application. 
The right side of the slider would contain the simplified view of the manifest i.e. Screenshot of  manifest rendered on canvas.

_If the contributor working on this issue, cannot find a screenshot/YAML to display, please atleast proceed with implementing the slider, leaving the screenshot/YAML as a placeholder._

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by yash37158**
**Description**
This pull request fixes the vertical slider instead of the current screenshot. Below is the video representation of the changes made.

**Updated Video as per the need**

https://github.com/meshery/meshery.io/assets/68152307/493653cc-c0f8-451d-9a66-82caa4ff279b

This PR fixes #1477 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
This screen recording is no longer accurate, right?

**Comment by leecalcote** [comment]
The current approach doesn't seem to work in Safari.

**Comment by abhijeetgauravm** [comment]
Hey @yash37158 Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by abhijeetgauravm** [comment]
Hey @yash37158 Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Review by leecalcote — APPROVED** [review]
Way to hang in there, @yash37158 👍

**Pull request merged**
