### PR TITLE
removed ruby version mandate

### PR DESCRIPTION
**Pull request by thisiskaransgit**
**Description**

Removing version mandate from Gemfile

following PRs will determine the success of this one.
**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by thisiskaransgit** [comment]
This PR mimics the same project configuration that we have on the docs  https://github.com/meshery/meshery/pull/8046
The solution does not seem to work in this case.

**Comment by thisiskaransgit** [comment]
The above commit [#55ac905](https://github.com/meshery/meshery.io/pull/1306/commits/55ac905a787f3074d9480e4935c4a32eb9765169), downgraded the declared ruby version to 3.1.1.

**Comment by leecalcote** [comment]
@thisiskaransgit the goal is to remove the version altogether...

**Review by leecalcote — APPROVED** [review]
I see the `#` in Gemfile now... 👍

**Pull request merged**
