### PR TITLE
Program page cards padding and footer fix

### LINKED ISSUE #421: Padding & Margin around Program Section
**Current State of the Meshery.io site**

1. Program Section is missing some padding & margin .
2. Subscribe Section on [Mehery's Program page](https://meshery.io/programs/) is missing padding.

**Desired State of the Meshery.io site**

1. Program Section must have some padding & margin around it.
2. Subscribe Section on [Mehery's Program page](https://meshery.io/programs/) must have some padding around it.

Screenshot_2021-04-01 Meshery The Service Mesh Manager

Screenshot_2021-04-01 Programs

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

### LINKED ISSUE #429: Programs page is covered by footer
**Description**
Programs page at `https://meshery.io/programs` is hidden by the footer

**Expected Behavior**
A brief description of what you expected to happen.

**Screenshots**
Add screenshots, if applicable, to help explain your problem.
Screen Shot 2021-04-17 at 5 13 09 PM

**Enviroment:**
 - OS: MacOS
 - Browser: Firefox
 - Version: 88.0b9
 - Device: Macbook Pro

---
[Optional] **To Reproduce**
1. Go to 'https://meshery.io/programs/'
3. Scroll down to Subcribe form

[Optional] **Additional Context**

### PR DESCRIPTION
**Pull request by Ayush-Khandelwal-007**
Signed-off-by: Ayush <ayushkhandelwal3217@gmail.com>

## **Description**

This PR fixes #421 
This PR fixes #429

I tried my best not to change the theme colours as well as match the figma styling wherever possible.
Please tell if any more modifications are required.

## **Notes for Reviewers**
Earlier the page was something like this:

https://user-images.githubusercontent.com/59086855/119660416-ded19080-be4c-11eb-8be9-e5b4115b829d.mov

After the changes it looks something like this:

https://user-images.githubusercontent.com/59086855/119660470-edb84300-be4c-11eb-8ec1-d419620de03b.mov

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Review by Neilblaze — CHANGES_REQUESTED** [review]
Good work @Ayush-Khandelwal-007 👍 
But before we merge the PR, I would like to look upon few issues that are being populated alongside the fix on the programs page ([Before](https://meshery.io/programs/) & [After](https://deploy-preview-464--mesheryio.netlify.app/programs)). 

Here are some of the requested changes,

• Try increasing the padding between each card instead of shifting one to the next row. Try to maintain a `3x3` grid structure (so, `3 in 1st row` & `2 in 2nd row` & **not** `4 in 1st row` and `1 in 2nd row`). This in case increases the aesthetics of the page.

⭐ Try keeping this as a reference : 
programs_page_upgrade

> 💡 Try to follow up the padding between cards with respect to [your](https://deploy-preview-464--mesheryio.netlify.app/programs/)'s. Besides, you can always experiment with different combinations, like resizing etc.

> #421 is device dependant and has low priority.


• Fix the error at the `Subscribe` & `Mailing List` Section. Refer to [this](https://deploy-preview-464--mesheryio.netlify.app/#mc_other_mailinglist).

⭐ This is the original one for Meshery [home](https://meshery.io/#mc_other_mailinglist).
orig_meshery

> 🧹 Although this does require some padding fixes for those buttons. And as always, feel free to add some custom spices to your cooked food if you want.

& this of your [PR](https://github.com/layer5io/meshery.io/pull/464#event-4799158231) via [this](https://deploy-preview-464--mesheryio.netlify.app/)
sub_mailing_err

> ⚠️ Page badly breaks on Safari!

• And most importantly, please make your PR **responsive** / **mobile-friendly**. Look out for the `Mailing list` section which is adding unnecessary frozen padding for mobile devices. 

> #429 is neatly fixed via this PR, so that won't need to be an overhead for now.

⭐ Reference for the above bullet : 
mobile_prev

--- 

Used devices : 
- Ubuntu 20.04 LTS (Firefox)
- Windows 10 (Chrome)
- iPhone 11 (Safari)

Signed off : @Neilblaze

**Comment by Ayush-Khandelwal-007** [comment]
Working on these changes!

**Review by Neilblaze — CHANGES_REQUESTED** [review]
Thanks @Ayush-Khandelwal-007, can you please do a quick update to the following stuff?

- Creating **3** separate `divs` for *Subscribe*, *Mailing* & *Service Mesh Landscape* (button) unnecessarily consumes too much space. I'll recommend you to update the section in this format.

🌟 Reference : 
sections

> 💠 Also, you can add a bit of padding between `Subscribe Section` & `Mailing Lists`.
> 💠 Feel free to add your imagination keeping the format & color scheme the same.

- In regards to #421 , update the padding in **responsive** view to this.

🌟 Reference :
padding

Rest LGTM 👍 
> I'll consider #467 as a duplicate of a subsection of PR #464

**Review by Neilblaze — APPROVED** [review]
LGTM 👍 
Good job @Ayush-Khandelwal-007 🎉

**Comment by Ayush-Khandelwal-007** [comment]
Hey , please don't merge it yet, i came across one more bug.

**Comment by Neilblaze** [comment]
> Hey , please don't merge it yet, i came across one more bug.

No worries, fix it, & we'll then merge it!

**Comment by Ayush-Khandelwal-007** [comment]
So as the commit message specify it fixes responsive nature of the testimonial div.
Here are the Screen recordings for before and after the changes.

### Before

https://user-images.githubusercontent.com/59086855/120037877-f6ad3e00-c01f-11eb-9eeb-032780ddee0f.mov

### After


https://user-images.githubusercontent.com/59086855/120037887-fb71f200-c01f-11eb-82dd-4de69b42c9e2.mov

**Comment by leecalcote** [comment]
Hot momma!

**Comment by amino19** [comment]
@Ayush-Khandelwal-007,  Good going! <3

**Review by Neilblaze — APPROVED** [review]
🥳

**Review by adithyaakrishna — APPROVED** [review]

**Comment by adithyaakrishna** [comment]
This PR is Ready to Merge 🎉 
Nice work @Ayush-Khandelwal-007 💯

**Pull request merged**
