### PR TITLE
revamp: filter section in catalog

### LINKED ISSUE #1222: [Catalog]
On [Meshery Catalog](https://meshery.io/catalog.) in filters
-
- List all the 200+ technologies ( https://meshery.io/integrations) under the Compatibility section and rename the section to `Technologies`

- We want to have checkboxes instead of radio buttons for all these 200+ technologies, so patterns containing checked technologies will show up. Inspiration: https://meshery.layer5.io/catalog  

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](https://slack.meshery.io) for access.

### PR DESCRIPTION
**Pull request by GaganpreetKaurKalsi**
### **Description**

This PR fixes #1222 

### Features added
- showing all cards for 'Technologies' and 'Categories' filter dynamically using javascript on the same page instead of specific page for each filter.
- Able to select multiple technologies at once, converted to checkbox from radio for 'Technologies' section.
- Show only those technologies under filter for which there is atleast 1 pattern card. Showing all technologies would create unnecessary crowd, not a good user experience.
- Show the count of cards available along side the filter name under 'Technologies' section.
- First 2 sections support dynamic loading of cards. Can extend the support to 3rd section as well.

### A few screenshots
image
image

### **[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by GaganpreetKaurKalsi** [comment]
### Few decisions to take
1. Do we need to show all integrations under newly named Technologies section or only the ones for which Patterns are available? If we are planning to show all integrations, then the list goes very long. Should we alphabetically group them? Or any better idea?
image

<br><br><br>

2. In dark mode, which one looks better, white icon or color icon? Color icon has visibility issues.
image
image

**Comment by leecalcote** [comment]
This second screenshot so nice to see. 😄

**Comment by GaganpreetKaurKalsi** [comment]
> This second screenshot so nice to see. 😄

With white icons or colored icons?

**Comment by sudhanshutech** [comment]
@GaganpreetKaurKalsi Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would

**Comment by leecalcote** [comment]
Whoa. Badge count. 😮

**Comment by leecalcote** [comment]
I missed your other question, @GaganpreetKaurKalsi. Yes, please alphabetically list them.

**Comment by leecalcote** [comment]
We do group these technologies by category in other UIs to help cut down the length. @Avi-88 has details...

**Comment by leecalcote** [comment]
A related concern is that of the Catalog's initial mobile view which doesn't display any catalog items, @GaganpreetKaurKalsi. I wonder if you might have a look at ensuring that the first page of catalog items is displayed in mobile view by default.


You made this Technologies refactoring look like child's play.

**Comment by leecalcote** [comment]
Added: sort filter by technology name.

**Review by leecalcote — APPROVED** [review]
Great work, @GaganpreetKaurKalsi. Clean.

**Comment by GaganpreetKaurKalsi** [comment]
> A related concern is that of the Catalog's initial mobile view which doesn't display any catalog items, @GaganpreetKaurKalsi. I wonder if you might have a look at ensuring that the first page of catalog items is displayed in mobile view by default.
> 
> You made this Technologies refactoring look like child's play.

Sure @leecalcote, will do that. 
You are always so good at commending 😊🤩
It was not easy. I did scratch my head for a few days.

**Comment by thisiskaransgit** [comment]
@GaganpreetKaurKalsi @leecalcote, 
 We might have a potential solution for the catalog list in a mobile view waiting for review
- https://github.com/meshery/meshery.io/pull/1186

**Pull request merged**
