### PR TITLE
Improved Catalog Filters

### PR DESCRIPTION
**Pull request by kanishk6103**
**Description**

This PR adds additional features to catalog page filter

**Notes for Reviewers**
- Added more features to catalog page filter

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Added count for categories
- [x] Fixed the heading "No Results Found" to show when no cards are there to show
- [x] Optimized the loop that calculates the category count 
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by kanishk6103** [comment]
Hey @Yashsharma1911 kindly review these changes and do let me know if there's anything missing :D

**Comment by leecalcote** [comment]
Thanks, @kanishk6103!

Line numbers used in comments will become stale and inaccurate over time. Best to use a difference reference in your comments.

**Comment by kanishk6103** [comment]
> Thanks, @kanishk6103!
> 
> Line numbers used in comments will become stale and inaccurate over time. Best to use a difference reference in your comments.

Will keep that in mind from the next time! do you want me to change it now? (also I don't know how to use a difference reference)
@leecalcote

**Comment by vishalvivekm** [comment]
@kanishk6103 
Thank you for your contribution.
Let's discuss this on Websites' call. Adding this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Comment by kanishk6103** [comment]
Hey @vishalvivekm is there anything you want me to change regarding the PR?

**Review by Yashsharma1911 — APPROVED** [review]
Thankyou @kanishk6103 for improving it

**Pull request merged**
