### PR TITLE
Add back to the top button on Landing Page

### LINKED ISSUE #589: Add a back to the top button on Landing Page [Desktop Mode]
**Current State of the Meshery.io site**

Back to the top button is not visible on existing Landing Page in Desktop Mode.

**Desired State of the Meshery.io site**

Add a back to the top button on the handbook to help users scroll through the page.
A typical example can be found on [this site](https://smp-spec.io/).

image
---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Prakhar-Agarwal-byte**
Signed-off-by: Prakhar Agarwal <prakhar@everything.net.in>

**Description**

This PR fixes #589

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vedant-kakde** [comment]
Thanks @Prakhar-Agarwal-byte .
Please checkout  back to the top button on layer5.io we need the same button on this website.

**Comment by Prakhar-Agarwal-byte** [comment]
@vedant-kakde How does it look now?

**Comment by vedant-kakde** [comment]
You've added this one
image

On layer5.io
image

**Review by sayantan1413 — COMMENTED** [review]
I think the effect on https://smp-spec.io/ is better when we slowly scroll from bottom to top and reach at the top of the page the scroll bar animation to disappear is better. So I think we can replicate the same behavior here.

**Comment by Prakhar-Agarwal-byte** [comment]
@sayantan1413 How's it now?

**Review by sayantan1413 — COMMENTED** [review]
Hey @Prakhar-Agarwal-byte the animation seems to work well now but in the below picture you can see I have scrolled that much and still the top to the bottom button is not visible but in https://smp-spec.io/ if you just click the scroll the button appears. So you might have a look there.

Screenshot 2021-12-12 at 10 42 01 PM

**Comment by Prakhar-Agarwal-byte** [comment]
@sayantan1413 I think it's fine now?

**Review by warunicorn19 — APPROVED** [review]
Looking good, Thank you @Prakhar-Agarwal-byte

**Pull request merged**
