### PR TITLE
Update README with badges

### LINKED ISSUE #1484: [Docs]: ADD Badges in Readme
### Current State:
image

### Desired State:
image

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by Killer2OP**
**Description**

This PR fixes #1484 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Killer2OP** [comment]
@leecalcote please review the PR

**Review by leecalcote — COMMENTED** [review]
Thanks, @Killer2OP. Is this light and dark mode compatible?

**Comment by Killer2OP** [comment]
> Thanks, @Killer2OP. Is this light and dark mode compatible?

Yes.

**Comment by Killer2OP** [comment]
@leecalcote any update?

**Comment by leecalcote** [comment]
@Killer2OP, yes, an update: be patient.

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Thanks, @Killer2OP 👍

**Pull request merged**
