### PR TITLE
Fix copy to clipboard button bug in catalog page with better UX.

### LINKED ISSUE #1000: Copy to clipboard button not visible
### Description

The Copy to clipboard is not visible on https://meshery.io/catalog page items.

### Expected Behavior

The button should be visible and working properly.

### Screenshots

https://user-images.githubusercontent.com/66985303/215340454-6bf60be2-957a-453a-91e8-312318d4f842.mov

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by chinu-anand**
**Description**

This PR fixes #1000 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by chinu-anand** [comment]
@leecalcote I created this new PR regarding issue #1000 , I hope this time it doesn't break the site. Please review this.

**Comment by yash37158** [comment]
Hey @chinu-anand just one small suggestion before you break your laptop I suppose 😅, I personally feel it's a bit weird when the cursor pass through the empty space still it shows the tag, the more prominent take can be if the cursor hovers only on “copy url” button.

**Comment by chinu-anand** [comment]
@yash37158 Can you please attach some images or a video demonstrating what the issue is?

**Comment by yash37158** [comment]
Yeah sure 


https://user-images.githubusercontent.com/68152307/222657162-fac3acf7-3b57-4127-a443-677eaf1a558c.mov

**Comment by chinu-anand** [comment]
@yash37158 you are facing this in deploy preview?

**Review by GaganpreetKaurKalsi — APPROVED** [review]
Looks good to me 👍

**Comment by leecalcote** [comment]
Thank you, @GaganpreetKaurKalsi and @chinu-anand

**Pull request merged**
