### PR TITLE
Added back to the top button on Landing Page

### LINKED ISSUE #589: Add a back to the top button on Landing Page [Desktop Mode]
**Current State of the Meshery.io site**

Back to the top button is not visible on existing Landing Page in Desktop Mode.

**Desired State of the Meshery.io site**

Add a back to the top button on the handbook to help users scroll through the page.
A typical example can be found on [this site](https://smp-spec.io/).

image
---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by vedant-kakde**
Signed-off-by: Vedant Kakde <69970950+vedant-kakde@users.noreply.github.com>

**Description**

This PR fixes #589

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
@vedant-kakde good job figuring out the issue with this, but just noticed the chevron doesn't look great at all. For some reason, it looks a little too thick in my opinion. Could you please consider using an SVG instead of this font awesome icon? something which looks similar to the one on the https://smp-spec.io website.

**Comment by leecalcote** [comment]
@vedant-kakde what would you like to do here?

**Comment by vedant-kakde** [comment]
Will do

**Comment by leecalcote** [comment]
Bueller...

**Comment by vedant-kakde** [comment]
@Prakhar-Agarwal-byte is taking up this issue.

**Pull request closed without merging**
