### PR TITLE
Added alt tags to all images for improved accessibility and SEO

### LINKED ISSUE #1369: Add alt tags to all images for improved accessibility and SEO
### Description

Alt attributes within `` tags are used by search engines to understand the contents of your images. They provide a textual description of images, allowing visually impaired users to understand the content and search engines to index images accurately.
Neglecting them will negatively affect the ranking in search results
### Expected Behavior

add alt tags to all images on the following pages. Alt tags should be descriptive and concise, conveying the purpose or context of the image without being overly verbose.
1. homepage
2. programs page
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by blindaks**
**Description**
Added alt tags to all images for improved accessibility and SEO.

This PR fixes #1369

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by abhijeetgauravm** [comment]
hey @blindaks while making commit run this command on your terminal git -s -m "your msg" . It will sign-off your commit.

**Comment by Ghat0tkach** [comment]
Hii @blindaks 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by Ghat0tkach** [comment]
@blindaks  , You havent joined our slack channel yet . Please join to get updates about meeting and discuss about your progress
https://layer5io.slack.com

**Comment by charu1603** [comment]
@blindaks   After making changes, commit with the sign-off flag (-s)!

Use this command: $ git commit -s -m “my commit message w/signoff”

**Comment by RavindraP04** [comment]
@blindaks Are you still facing the issue to signoff  the commits ?

This is what helped me
Now you need to close the existing PR and raise a new one with proper signoff commits

To signoff the commits you can use --signoff or -s while writing the command to commit the changes
Use this command: $ git commit -s -m “my commit message”

For more info you can checkout this one :- https://volunteer.coscup.org/docs/en/dev/how-to-signoff/

**Pull request closed without merging**
