### PR TITLE
Added Resources component New page design implementation for Contributors page #1271

### LINKED ISSUE #1271: New page design implementation for Contributors page
#### Current State of the Meshery.io site

Currently the page https://meshery.io/community/ is empty

#### Desired State of the Meshery.io site

Need to implement the mockup for this page from [Figma design](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=16435%3A39494&mode=design&t=6qls5jOGn5gJKKgm-1)
Contributors can pick separate section to implement the page fast

- [ ] Section-1: Banner section

image

- [ ] Section- 2: Resources section

image

- [ ] Section-3: Handbook section

image

- [ ] Section-4: Discuss forum section

image

- [ ] Section-5: Meshmate section

image

- [ ] Section-6: Calendar section"

image

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Ykumar1415**
**Description**

This PR fixes #1271

**Notes for Reviewers**
Screenshot from 2023-07-13 00-25-24
Screenshot from 2023-07-12 19-46-44

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@Ykumar1415 Let's discuss it on the websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

**Comment by Ykumar1415** [comment]
> @Ykumar1415 Let's discuss it on the websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

ok @vishalvivekm i will add this.

**Review by thisiskaransgit — CHANGES_REQUESTED** [review]
@Ykumar1415, thank you for your efforts, here are some things to consider
- Refrain from making any dependency changes.
- Please fix the changes in the footer.
- The card elements are not redirecting us right now, update them with the appropriate hyperlinks

### For SVGs 
- use the appropriate naming conventions, and utilize the kebab case typing
- there's duplication for shape.svg, also change its name to bookmark or docs.

### In styling 
- Use relative units wherever possible.

**Comment by Ykumar1415** [comment]
> 

@thisiskaransgit can you give me the links on which it should redirect.

**Comment by Chadha93** [comment]
> > 
> 
> @thisiskaransgit can you give me the links on which it should redirect.

@thisiskaransgit

**Comment by thisiskaransgit** [comment]
@Ykumar1415 

Tutorials -> https://layer5.io/learn
Documentation -> https://docs.meshery.io/
Guidelines -> https://layer5.io/community/handbook/contributor-journey#Newcomer%E2%80%99s%20Path
Early Access -> https://play.meshery.io/

**Comment by thisiskaransgit** [comment]
Great job on your pull request @Ykumar1415! Your efforts and contributions to the project are highly appreciated.
Just wanted to inform you that we will be closing this PR as another one with similar changes has been merged. Please know that this decision does not diminish the value of your work.
Keep up the fantastic work, and we look forward to seeing more of your contributions in the future!

**Pull request closed without merging**
