### PR TITLE
Added Integration loader

### PR DESCRIPTION
**Pull request by yash37158**
Signed-off-by: yash37158 <yash37158@gmail.com>

**Description**
Adding a loading spinner on /integrations page of meshery.io so as to show user page is being a loaded.

This PR fixes #
Till now there was no loading spinner functionality on the meshery.io website.
Feature: Added a Loading spinner on the integration page 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@Musab1258 feel free to offer feedback.

**Comment by yash37158** [comment]
@GaganpreetKaurKalsi @Krishna2323  @asubedy Can someone please review the PR ?

**Review by GaganpreetKaurKalsi — CHANGES_REQUESTED** [review]
Hey @yash37158, great work! I really liked the loader. 
Is there a possibility that we can bring the loader to the centre of the page and also `position: absolute` so that it doesn't push the integrations div below while it is present on the screen. It would be great if we could achieve that.

**Comment by yash37158** [comment]
Thanks for your response @GaganpreetKaurKalsi yeah we can definitely achieve that. but I think it will look weird if we place loader on the integrations. let me know what you think about this

**Comment by yash37158** [comment]
After changes, it looks like this

Screenshot 2022-12-27 at 8 20 09 PM

**Comment by yash37158** [comment]
Any updates ? @GaganpreetKaurKalsi @leecalcote

**Comment by GaganpreetKaurKalsi** [comment]
The loader needs to be in centre, that's for sure. But need to make it a little nicer, maybe have the loader animation on a white card or blurring the background till the loader is visible on the screen. What say @leecalcote ? How do you imagine the loader to look like? 
Maybe we can have a discussion on this in Monday's meeting.

**Comment by leecalcote** [comment]
> The loader needs to be in centre, that's for sure. But need to make it a little nicer, maybe have the loader animation on a white card or blurring the background till the loader is visible on the screen. What say @leecalcote ? How do you imagine the loader to look like?
> Maybe we can have a discussion on this in Monday's meeting.

I agree on each point and each suggestion that you've made here, @GaganpreetKaurKalsi . 👍

**Comment by yash37158** [comment]
Make sense, I applied the changes we want and this is how its looking @GaganpreetKaurKalsi 
Screenshot 2022-12-30 at 2 08 51 AM

**Comment by GaganpreetKaurKalsi** [comment]
> Make sense, I applied the changes we want and this is how its looking @GaganpreetKaurKalsi Screenshot 2022-12-30 at 2 08 51 AM

Please push the changes......Let's see the deploy preview once.

**Comment by GaganpreetKaurKalsi** [comment]
Great Great!!!! It looks good now. Just a tiny bit of change required. Change `background-color` for `.loader` to `background-color: rgba(0, 0, 0, 0.5)`. Black color with opacity 0.5 makes the loader more visible to the eyes. Let's have a proper overlay effect. After this change, it should be good to merge 👍 .

**Comment by yash37158** [comment]
Yeah sure, Thanks for your valuable feedback @GaganpreetKaurKalsi  @leecalcote

**Review by GaganpreetKaurKalsi — APPROVED** [review]
Great! Ready to go from my side 👍. 
A green signal from @leecalcote should be the last step now.

**Comment by yash37158** [comment]
Yeah that's good to hear that, a suggestion from @leecalcote would be great

**Comment by leecalcote** [comment]
I yield my vote to @GaganpreetKaurKalsi

**Review by leecalcote — APPROVED** [review]
Oh, I see that @GaganpreetKaurKalsi already approved. Great.

**Pull request merged**
