### PR TITLE
Changed the color of text inside of chip tag

### LINKED ISSUE #1011: [UI] Text inside of chip tag of catalog card is not properly visible
### Description
In the upper right corner of catalog card tag, text is not properly visible

### Current Behavior
https://user-images.githubusercontent.com/71271069/217500674-d276fd31-53d2-4460-b7ad-564037b3f0bc.mov

### Expected Behavior

https://user-images.githubusercontent.com/71271069/217500712-ece36a95-218d-417d-af2b-b0d0c124686a.mov

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Savio629**
Signed-off-by: Savio629 <diassavio629@gmail.com>

**Description**

This PR fixes #1011

**Notes for Reviewers**
Changed the color of text inside of chip tag to black for better visibility.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Yashsharma1911 — APPROVED** [review]
It is working thanks @Savio629

**Comment by UtkarshMishra12** [comment]
@Savio629  Can you please replace the **black(color for text)** with the variables that are defined here [link](https://github.com/meshery/meshery.io/blob/master/_sass/rootvariables.scss) for Black color.

**Comment by Savio629** [comment]
@UtkarshMishra12 There isn't exact black color available in the file. But I have used a similar shade of black present in the file.
Also does it look fine or do I need to make it a little bold.
Cloud Native Catalog _ Meshery - Brave 14-02-2023 20_09_50 (2)

Regarding the variables, there are lot of places where black and white color are directly used instead of using variables...

**Review by UtkarshMishra12 — APPROVED** [review]
LGTM Thanks @Savio629  🥇

**Comment by UtkarshMishra12** [comment]
@leecalcote using this variable is good or we can use black(text) for color directly? 🤔

**Comment by leecalcote** [comment]
> @leecalcote using this variable is good or we can use black(text) for color directly? 🤔

Good question. The variable is ideal here. 👍

**Pull request merged**
