### PR TITLE
Updated svg

### LINKED ISSUE #1588: [Integration logo AMD] - Logo is out of proportion
### Description

Link: [260+ Built-In Integrations](https://meshery.io/)
Section under "260+ Built-In Integrations"

Currently, the AMD integration logo looks out of proportion. 

Adjust the proportions of the logo to accurately reflect the original design.
##### Before
Screenshot 2024-01-20 202522

##### After

amd

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by surajvast1**
**Description**

This PR fixes #1588 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by surajvast1** [comment]
image
@sandramsc Thanks for assigning me this

**Comment by saurabh100ni** [comment]
Hi @surajvast1  ,
Thanks for your PR! I encourage you to share this in the Website Meeting tomorrow at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Comment by sudhanshutech** [comment]
@surajvast1 why created a empty `metadata` file?

**Comment by leecalcote** [comment]
@iArchitSharma, you can explain that these SVGs are define in the Meshery Integrations spreadsheet and how to add a comment in there as the fix, so that the file here isn't overwritten.

**Comment by iArchitSharma** [comment]
@surajvast1, we cannot make any changes to integrations from the codebase because we use a Google Spreadsheet to maintain the integrations, and from there, it is directly fetched into the codebase. Any changes from the codebase can lead to overwriting and may cause trouble

**Comment by iArchitSharma** [comment]
@surajvast1 this is the [spreadsheet](https://docs.google.com/spreadsheets/d/1DZHnzxYWOlJ69Oguz4LkRVTFM79kC2tuvdwizOJmeMw/edit#gid=0) you can add the comment to the cell where you want the changes

**Comment by surajvast1** [comment]
Sure thanks @iArchitSharma

**Pull request closed without merging**
