### PR TITLE
Change install guide to go Kubernetes first

### PR DESCRIPTION
**Pull request by navendu-pottekkat**
Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>

**Description**

This PR is related to switching the default platform to deploy Meshery to Kubernetes. See https://github.com/meshery/meshery/issues/4233

Changes the first install guide to say about Kubernetes installation instead of Docker.

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
This change has me realizing that we don't have a dedicated Docker logo and set of instructions.

**Comment by leecalcote** [comment]
> This change has me realizing that we don't have a dedicated Docker logo and set of instructions.

@alphaX86 this is an issue that we can open up and label with `help-wanted`

**Review by leecalcote — APPROVED** [review]
LGTM

**Comment by alphaX86** [comment]
> > This change has me realizing that we don't have a dedicated Docker logo and set of instructions.
> 
> @alphaX86 this is an issue that we can open up and label with `help-wanted`

👍 I'll open regarding it

**Comment by alphaX86** [comment]
Issue opened! #580

**Comment by alphaX86** [comment]
@leecalcote relating to this one... IG we need to look on the same at layer5 site too, check this out

image

For now, Docker style installation is appearing... Is this good for now?

**Comment by leecalcote** [comment]
@alphaX86, yes, please. If you're comfortable with Gatsby, it would be great if you made this update. If you're not, then this is a good opportunity to be so. Otherwise, will you kindly create an issue in that repo?

**Comment by alphaX86** [comment]
> @alphaX86, yes, please. If you're comfortable with Gatsby, it would be great if you made this update. If you're not, then this is a good opportunity to be so. Otherwise, will you kindly create an issue in that repo?

I'm indeed comfortable with Gatsby due to some experience in React (just I don't work with it due to heavy size of modules) I'll correct them and fix it

**Pull request merged**
