### PR TITLE
[BUG-1673,1690] Resolve horizontal scrolling and add spacing b/w sidebar and catalogs

### PR DESCRIPTION
**Pull request by Muhammed-Moinuddin**
**Description**

This PR fixes # 1673 and 1690

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@Muhammed-Moinuddin 
Let's discuss this on websites call. Add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would :)

**Comment by sudhanshutech** [comment]
@Muhammed-Moinuddin please describe what you are fixing in the pr description and ensure to properly tag the issue you are working on.

**Comment by Muhammed-Moinuddin** [comment]
> @Muhammed-Moinuddin 
> Let's discuss this on websites call. Add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would :)

Noted!

**Comment by Muhammed-Moinuddin** [comment]
> @Muhammed-Moinuddin please describe what you are fixing in the pr description and ensure to properly tag the issue you are working on.

Noted!

**Comment by ritiksaxena124** [comment]
Hey @Muhammed-Moinuddin let's discuss this on today's website meet ([https://meet.layer5.io/websites](https://www.google.com/url?q=http://meet.layer5.io/websites&sa=D&source=calendar&usd=2&usg=AOvVaw1CNpNwmYd_rTFcQa_7fBB5)) if you are available. I have added it as an [agenda item](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit)

**Review by iArchitSharma — APPROVED** [review]
Thanks @Muhammed-Moinuddin

**Pull request merged**
