### PR TITLE
Fixed the default website mode to dark

### LINKED ISSUE #1429: Dark Mode by Default
### Description
The meshery.ioi website is supposed to be in dark mode by default.

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
**Description**

- Refactored the code to make it more readable and easily maintainable.

This PR fixes #1429 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Chadha93** [comment]
@akhilender-bongirwar Thanks for this, few issues with the images 
image
image

**Comment by vishalvivekm** [comment]
@akhilender-bongirwar 
There's flicker in default dark mode :

https://github.com/meshery/meshery.io/assets/110674407/d893f2d8-1fdb-4d43-860e-ab0d3341ad41

Also, when in light mode on reload or on navigating to other pages, the theme changes to dark mode abruptly

**Comment by akhilender-bongirwar** [comment]
Hey @vishalvivekm @Chadha93 , I have fixed the flickering as well as images. Could you please check : )

**Comment by vishalvivekm** [comment]
> Hey @vishalvivekm @Chadha93 , I have fixed the flickering as well as images. Could you please check : )

@akhilender-bongirwar The flickering in the default theme still doesn't seem to go away yet when reloading the page or navigating to another section.

https://github.com/meshery/meshery.io/assets/110674407/546c3647-152c-4c75-a21c-dc858768b8ae

**Comment by akhilender-bongirwar** [comment]
Hey @vishalvivekm, this issue is related to setting the default mode as dark mode for the website. The flickering issue is originally present in the website itself. Please check the video below. Please correct me if I am wrong about this.

https://github.com/meshery/meshery.io/assets/112749383/4900e079-e1cf-477e-93f6-fdade6a8a794

**Comment by saurabh100ni** [comment]
Let's discuss this in tomorrow's website meeting,
Please add it in the Doc, If you would ^^:
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by leecalcote** [comment]
yay! 🎈 @akhilender-bongirwar

**Pull request merged**
