### PR TITLE
Test- Remove catalog display

### PR DESCRIPTION
**Pull request by sachanakshat**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by saurabh100ni** [comment]
hey @sachanakshat  Thanks for raising PR please add this as you agenda item in [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) for Website meet which is starting in 30 minutes.
you can find more details about meet on [community calendar](https://layer5.io/community/calendar)

**Comment by abhijeetgauravm** [comment]
Hey @sachanakshat  Let's discuss the progress on website call today at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by sudhanshutech** [comment]
@sachanakshat its being a lot of time , are you working on it?

**Comment by sudhanshutech** [comment]
following again @sachanakshat are you still on it?

**Comment by sudhanshutech** [comment]
Considering no progress here from a month and no description for the pr  lets close this for now, if you need @sachanakshat we can reopen this later. Thanks

**Pull request closed without merging**
