### PR TITLE
Programs page is covered by footer #429: issue resolved

### PR DESCRIPTION
**Pull request by Josephchinedu**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
You should not be changing the footer CSS directly, it impacts all that pages.
Instead look at the component, which has the issue and the fix should be restricted to that only.

Also, please mention the issue number in the description `This PR fixes #<issue-number>` it will automatically close the issue when the PR is merged.

**Comment by leecalcote** [comment]
@Josephchinedu thanks for working on this one. Will you take @Nikhil-Ladha's suggestions into consideration?

**Comment by Josephchinedu** [comment]
@leecalcote i actually tried to implement meaning @Nikhil-Ladha suggestion, but i don't know to do that without touching the footer CSS. and i know it'll affect other pages.

**Comment by Nikhil-Ladha** [comment]
> @leecalcote i actually tried to implement meaning @Nikhil-Ladha suggestion, but i don't know to do that without touching the footer CSS. and i know it'll affect other pages.

Firstly, you need to rebase your local fork with the latest upstream code. In the current preview, the mailing list div is not even there.
After doing so, the only fix that you need to do is remove this CSS:->
https://github.com/layer5io/meshery.io/blob/master/css/program.css#L119

**Comment by leecalcote** [comment]
Any suggestion on how to proceed?

**Comment by Nikhil-Ladha** [comment]
> Any suggestion on how to proceed?

The solution is being highlighted in the previous comment, now waiting for the update from @Josephchinedu

**Comment by NikhilSharma03** [comment]
@adithyaakrishna I think this one is also related to the footer problem. Can you please check?

**Comment by Jashpatel1** [comment]
The issue has already been solved by another contributor.

**Pull request closed without merging**
