### PR TITLE
Alignment fix of theme toggler

### LINKED ISSUE #1386: Aligning Theme Change Icon in the Navbar
### Description
The theme change icon in the navbar is not properly aligned with the rest of the navbar. Currently, it is slightly positioned upwards, creating a visual misalignment within the navigation bar. 

### Expected Behavior
The theme change icon in the navbar should be in alignment with rest of the navbar.

### Screenshots

image

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by iArchitSharma**
**Description**

This PR fixes #1386

**Before:**
image

**After:**
image

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Ghat0tkach — CHANGES_REQUESTED** [review]
We shouldn't add any more classes to an element; instead, we should modify the existing styles.

**Review by vaibhav-xt — CHANGES_REQUESTED** [review]
@iArchitSharma's approach is incorrect. To resolve this issue, simply remove the `padding: 0 !important;` line from the `img` tag.

**Comment by iArchitSharma** [comment]
@vaibhav-xt Thanks for the help!

**Comment by iArchitSharma** [comment]
@Ghat0tkach Done!

**Review by vaibhav-xt — APPROVED** [review]
LGTM 🚀👏

**Comment by vishalvivekm** [comment]
@iArchitSharma 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

**Comment by Ghat0tkach** [comment]
hey @iArchitSharma 

Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Review by abhijeetgauravm — APPROVED** [review]
Yeah its aligned now !

**Review by Ghat0tkach — CHANGES_REQUESTED** [review]
The logo remains same even in dark mode

image

**Comment by iArchitSharma** [comment]
@Ghat0tkach, I thought the issue was only to fix the alignment of the button?

**Review by Ghat0tkach — APPROVED** [review]

**Comment by leecalcote** [comment]
Snapshots from Safari:

**Current site:**
Screenshot 2023-09-21 at 3 45 46 PM

**Proposed change in this PR:**
Screenshot 2023-09-21 at 3 45 46 PM

**Review by leecalcote — CHANGES_REQUESTED** [review]
@iArchitSharma thanks for this. Will you have another look?

**Comment by iArchitSharma** [comment]
> @iArchitSharma thanks for this. Will you have another look?

ya sure let me see

**Comment by iArchitSharma** [comment]
@leecalcote Check it out how does it look now:
image

**Comment by leecalcote** [comment]
@iArchitSharma thanks. Please address the discrepancy between the two colors used in the menu and the mode switcher icon. 
IMG_8738

**Comment by abhijeetgauravm** [comment]
Hey @iArchitSharma Let's discuss this on website call today at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima)

**Comment by sudhanshutech** [comment]
@iArchitSharma from width `1140px- 840px`screen size
image

**Comment by iArchitSharma** [comment]
> @iArchitSharma from width `1140px- 840px`screen size
> image

Let me take a look on it

**Comment by iArchitSharma** [comment]
@sudhanshutech Fixed it, check it out
image

**Review by abhijeetgauravm — APPROVED** [review]
Looks good to me!

**Comment by vishalvivekm** [comment]
Let's discuss this on the websites call today @iArchitSharma. Let's get others' feedback, too.
I'm adding this in the meeting minutes: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by abhijeetgauravm** [comment]
LGTM // @vishalvivekm @sudhanshutech

**Review by sudhanshutech — APPROVED** [review]

**Pull request merged**
