### PR TITLE
Fix transparent gap in phone Navbar

### LINKED ISSUE #1418: Transparent Space Between Navbar items and Logo in Mobile view.
### Description
When we click on the navbar icon in mobile view, There is a transparent space between logo and navbar items  

### Expected Behavior
The transparent space should not be there.

### Screenshots
Screenshot 2023-09-09 102347

### Enviroment:
 - OS: Windows
 - Browser: Chrome

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Akshun-01**
**Description**
This commit addresses the issue by fixing the transparent gap in the phone Navbar.

This PR fixes #1418

**Notes for Reviewers**
### Before 
image

### After
image

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by abhijeetgauravm — CHANGES_REQUESTED** [review]
hey @Akshun-01 its inconsistence at some screen size(below ~ 355 px)
image

**Comment by Akshun-01** [comment]
Hi @abhijeetgauravm, there was a minor issue with the width property, I fixed it. Could you please review and tell me if any further changes are needed?

**Review by Mohith234 — CHANGES_REQUESTED** [review]
- Do not include these files `Gemfile` and `Gemfile.lock` in your commit

Remove the mentioned files and you are good to go @Akshun-01

**Comment by Akshun-01** [comment]
Hi @Mohith234 , I think I didn't do it the right way. Wasn't I supposed to remove the files and commit and push again ? 
Could you help me with this one

**Comment by Mohith234** [comment]
- If you delete it and commit the changes git tracks this as we need to delete the files in the project itself.

- You can revert the files and then commit the remaining files. It will work fine @Akshun-01

**Comment by Akshun-01** [comment]
Hi @Mohith234 , I reverted the changes in gemfile. You can now review the changes. The navbar is working fine on phone.

**Comment by Mohith234** [comment]
@Akshun-01 All good to go, Just squash the commits into one.

**Comment by Akshun-01** [comment]
Hi @Mohith234 , I squashed the commits.

**Comment by Ghat0tkach** [comment]
hey @Akshun-01 
Let's discuss it on the websites call.
I have already added your agenda as part of today's meeting minutes

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Review by VivekBaldha0712 — COMMENTED** [review]
LGTM !!

**Comment by leecalcote** [comment]
Thank you, all!

**Pull request merged**
