### PR TITLE
Dark mode hovering over the getting started button #1162

### LINKED ISSUE #1162: In Navbar section dark mode is hovering over the getting started button on reloading the page
#### Current Behavior
On reloading the page the in  navbar section the dark mode button is hovering over the getting started button

#### Expected Behavior
both the buttons should be at their right place on reloading the page it does not collide to each other

#### Screenshots/Log

https://github.com/meshery/meshery/assets/95420063/542bbb3a-f48b-4d6d-9ea7-f01a83885c65

s

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

#### To Reproduce
1. Go to :https://meshery.io/
---
I m working on this
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by hemantmm**
**Description**

This PR fixes #1162

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by abhijeetgauravm** [comment]
Hey @hemantmm  Let's discuss this on website call tomorrow at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by hemantmm** [comment]
@vishalvivekm @abhijeetgauravm I missed the meeting because I was out. Apologies. Please review my PR. appreciate your help.

**Comment by hemantmm** [comment]
Hi, @leecalcote can you have a look at my PR?

**Review by Mohith234 — APPROVED** [review]
Looks good to me @hemantmm, Thanks for contributing 🎉

**Comment by abhijeetgauravm** [comment]
Looks good, but can some enhancement be made so that the navbar items won't displace after reloading. Thoughts??

**Review by sudhanshutech — APPROVED** [review]

**Pull request merged**
