### PR TITLE
Consolidated files under assets

### LINKED ISSUE #923: [Chore] Consolidate assets folders including js, css, images
#### Current State of the Meshery.io site
These two folders and their content:

1. https://github.com/meshery/meshery.io/blob/master/js
1. https://github.com/meshery/meshery.io/blob/master/images

#### Desired State of the Meshery.io site
Can be combined under `/assets`.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by BabyElias**
**Description**
Consolidated all contents of js and images folder under assets folder and changed file location at all places where they were referenced.
This PR fixes #923 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @BabyElias

**Comment by leecalcote** [comment]
@BabyElias you can sign your commits by executing these git commands - https://github.com/meshery/meshery.io/pull/1040/checks?check_run_id=11585475707

**Comment by BabyElias** [comment]
@leecalcote There have been some issues with my rebasing and since this is a major change, I'll create a new PR for this. Extremely sorry for the delay caused.

**Comment by leecalcote** [comment]
No sweat, @BabyElias. I completely understand. It’s no small task that you have here.

**Pull request closed without merging**
