### PR TITLE
[Website] Fixed incorrect layer5 extension logo to 5 logo

### LINKED ISSUE #1851: [Website] The Layer5 Cloud extension should have a "5" mark, not Meshery logo
#### Current State of the Meshery.io site
On the [extensions page](https://meshery.io/extensions), the Layer5 Cloud extension should have a "5" logo, not Meshery logo
Screenshot 2024-08-05 at 5 08 05 PM

#### Desired State of the Meshery.io site
The "5" mark can be found at https://layer5.io/company/brand.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by dsawwork**
**Description**

This PR fixes #1851 
Used the brand logo stored in assets itself.

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x ] Yes, I signed my commits.

### CODE REVIEW

**Review by sudhanshutech — CHANGES_REQUESTED** [review]
@dsawwork at card use only logo with 5 not the whole logo. Inside we can have the whole log so that is good.
image

**Comment by dsawwork** [comment]
> @dsawwork at card use only logo with 5 not the whole logo. Inside we can have the whole log so that is good. image

I have update the changes. please check

**Comment by dsawwork** [comment]
> > @dsawwork at card use only logo with 5 not the whole logo. Inside we can have the whole log so that is good. image
> 
> I have updated the changes. please check when possible.

I think the icon is not getting deployed correctly. will check this.

**Comment by Ashparshp** [comment]
@dsawwork Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by dsawwork** [comment]
> @dsawwork Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

Unfortunately I couldn't join the meeting this week. I will try to fix this, doesn't seem to be a big issue.

**Review by leecalcote — APPROVED** [review]
Thanks much, @dsawwork 👍

**Pull request merged**
