### PR TITLE
Centered : Menu Hamburger and Text 

### LINKED ISSUE #926: Menu Hamburger and Text are not centered
#### Current State of the Meshery.io site
1. Go to [Meshery Site](https://www.meshery.io/)
1. If the size of the window is less than normal you will see a hamburger icon and `MENU` text
1. Zoom and check that it's actually not completely centred. Here's a photo
image

#### Desired State of the Meshery.io site

The Hamburger Icon and `MENU` text must be centred for a consistent look.

image

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by SiddheshKukade**
Signed-off-by: Siddhesh Bhupendra Kuakde <littlelord124@gmail.com>

**Description**
Just added `display:flex ` for centering menu & icon 
This PR fixes #926 

**Notes for Reviewers**
#### This PR will fix issue no #926 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by SiddheshKukade** [comment]
Here's the side by side
image

**Comment by SiddheshKukade** [comment]
Hello @Krishna2323 the pull request is ready to ve reviewed 👍

**Comment by SiddheshKukade** [comment]
@leecalcote @Krishna2323 Please let me know if this PR is not valid. I'll close it. no problem.

**Comment by Krishna2323** [comment]
@SiddheshKukade, your PR looks fine but the hamburger is still not centered below 420px of width.

**Comment by SiddheshKukade** [comment]
> @SiddheshKukade, your PR looks fine but the hamburger is still not centered below 420px of width.
> 

I'll look into that ✅

**Comment by UtkarshMishra12** [comment]
@SiddheshKukade Please update

**Comment by leecalcote** [comment]
@tinniaru3005 your review here will be helpful.

**Comment by SiddheshKukade** [comment]
Why this DCO check is failing can anyone please explain, thanks.
image

**Comment by tinniaru3005** [comment]
> @tinniaru3005 your review here will be helpful.

Ya, the changes look good to me.  :)

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
