### PR TITLE
Responsive issue with main menu at 1141px #1749

### PR DESCRIPTION
**Pull request by 26vanshika**
Responsive issue with main menu at 1141px #1749

This PR fixes # The responsive issue pertaining to Safari

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@26vanshika 
Will you please sign off your commits ?
Here's how you can do it: https://github.com/meshery/meshery.io/pull/1756/checks?check_run_id=25387385069

**Comment by vishalvivekm** [comment]
Let's discuss this on Websites's call on Monday. Adding this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Review by captain-Akshay — CHANGES_REQUESTED** [review]
@26vanshika 

https://github.com/meshery/meshery.io/assets/59491379/51f9f54b-4511-4567-8f41-f752711aed0d

**Comment by 26vanshika** [comment]
> @captain-Akshay 
I will take a look

**Comment by 26vanshika** [comment]
@sudhanshutech @vishalvivekm  Could you take a look at this

Screenshot 2024-05-29 at 4 47 42 PM

Screenshot 2024-05-29 at 4 48 09 PM


As you compare the styles part of both the ss we can see that 
@media screen and (max-width: 1140px)
.nav-list {
box-shadow: var(--box-shadow-primary);
max-height: 250px;
overflow-y: scroll;
overflow-x: hidden;
}
this part is causing the issue i suppose, since its absence on the left side is not causing the issue.

**Comment by vishalvivekm** [comment]
> @sudhanshutech @vishalvivekm Could you take a look at this


Let's discuss this on Websites's call on Monday. Please add this Adding this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Thanks!

**Comment by leecalcote** [comment]
Uh-oh... was this not completed? I thought this was done, but I seem to be mistaken. @sudhanshutech will you make an assessment and fix as needed?

**Comment by vishalvivekm** [comment]
> Uh-oh... was this not completed? I thought this was done, but I seem to be mistaken. @sudhanshutech will you make an assessment and fix as needed?

I'll list this as agenda item and request contributors with a Mac to confirm this fix.

**Comment by vishalvivekm** [comment]
> Can I work on this? @vishalvivekm


sure @hargunkaur286, FYI https://github.com/meshery/meshery.io/issues/1749#issuecomment-2129298358

**Pull request merged**
