### PR TITLE
update meshery homepage: video is embeded in the modal

### LINKED ISSUE #628: [Website] Place service mesh patterns demo video into modal
**Current State of the Meshery.io site**
On the index page of meshery.io, the short video linked under the button in this screenshot is directly linked. 

Screen Shot 2021-12-09 at 5 03 56 PM

**Desired State of the Meshery.io site**
Ideally, this video plays in a modal, not as a separate, direct video.

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by shubham-tyagi**
**Description**

This PR fixes #628

**Notes for Reviewers**
please point out if I missed something or if anything else Is needed to be done.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by shubham-tyagi** [comment]
it still requires some work. don't review it yet haha.

**Review by leecalcote — CHANGES_REQUESTED** [review]
This player doesn't seem to work or doesn't work with Safari very well. The fullscreen button is non-standard and not obvious that it functions as a fullscreen.

**Comment by leecalcote** [comment]
The video plays/pauses onClick, but the toolbar has a bit of a challenge displaying, yet. This recording is from Safari.

https://user-images.githubusercontent.com/7570704/147012796-cae4eff8-70bd-40be-94f6-7683737e9b79.mov

**Comment by shubham-tyagi** [comment]
thanks for the feedback @leecalcote. Looking into it right now.

**Comment by leecalcote** [comment]
Merging in the meantime as this is a step forward.

**Pull request merged**
