### PR TITLE
Added flexbox, removed whitespace and aligned tooltip

### LINKED ISSUE #715: Copy to clipboard tooltip is not aligned / scroll always visible
**Description**

1. `Copy to Clipboard` tooltip is not align properly
2. Scroll always visible.

**Expected Behavior**

1. `Copy to Clipboard` tooltip should be aligned properly.
2. Keep the scroll as `auto` like if the content exceeds then only it will be visible else remains hidden in the modal.

**Screenshots**

https://user-images.githubusercontent.com/44670961/171209794-8cd25020-c7d6-4914-be83-5a4160933c03.mp4

**Enviroment:**
 - OS:  Ubuntu
 - Browser: Chrome, firefox

---
[Optional] **To Reproduce**
1. Go to [Meshery Catalog](https://meshery.io/catalog)
2. Click on any card which will open a modal
3. Hover over `Copy Url` button.

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Rohith-Raju**
Signed-off-by: Rohith Raju <rohithraju488@gmail.com>

**Description**
Removed whitespace and aligned tooltip by using flexbox

This PR fixes #715

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
The modal loses it responsiveness.

**Comment by Rohith-Raju** [comment]
Any changes @warunicorn19 @leecalcote  @chinmaym07 @theBeginner86

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
overall looking good, just a couple of items. 
1. There's still a responsiveness issue from 1020px-660px, please do have a look. 
2. There's this small artifact on hover of the copy the button. Could you please remove that? 
 
Screenshot 2022-06-20 at 6 06 46 PM

**Comment by Rohith-Raju** [comment]
Yes @warunicorn19 on it!!

**Comment by Rohith-Raju** [comment]
Hey guys, it's all done 
@warunicorn19 @leecalcote @theBeginner86

**Comment by warunicorn19** [comment]
Some merge conflicts to address.

**Comment by Rohith-Raju** [comment]
@warunicorn19 Can you do it now ?

**Comment by warunicorn19** [comment]
@Rohith-Raju you'll have to work on the styles again here, unfortunately. The changes that you made are not compatible with refactored styles. Also with regards to Merge conflicts you'd have to get rid of the `>>>>HEAD` and the other commit IDs, that's why the build was failing. You could try again in this PR itself or open up a fresh new PR.

**Comment by Rohith-Raju** [comment]
Not a problem @warunicorn19, new pr it is then

**Pull request closed without merging**
