### PR TITLE
pagination for catalog 

### LINKED ISSUE #732: [Catalog] Pagination
**Current State of the Meshery.io site**
All entries are shown on the single page catalog.

**Desired State of the Meshery.io site**
The catalog should contain multiple pages and should be paginated.

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by legendarykamal**
Signed-off-by: Kamal Nayan <95926324+legendarykamal@users.noreply.github.com>

**Description**
Note- Not yet complete.

This PR fixes #732 

**Notes for Reviewers**
This is in progress to create pagination for the catalog

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by asubedy** [comment]
@legendarykamal , this will not work because
1. The Jekyll paginate gem which we use only works on posts, here the patterns are collection, but the blogs are posts hence we use this for paginating the blogs
2. This approach breaks the blogs page and breaks the catalog page too

So we need a different approach here, one thing you can try is manually showing certain number of cards on one link and similarly on the other.

**Comment by legendarykamal** [comment]
@asubedy thanks for the prompt feedback, 
I will try that approach.

**Comment by adithyaakrishna** [comment]
@legendarykamal Any updates on this?

**Comment by legendarykamal** [comment]
after exams, I will finish this ✅

**Comment by leecalcote** [comment]
@Krishna2323, in light of sweeping changes across the site, is this PR still valid (necessary)?

**Comment by leecalcote** [comment]
> @Krishna2323, in light of sweeping changes across the site, is this PR still valid (necessary)?

Please make a call here.

**Comment by Krishna2323** [comment]
@leecalcote, yes, if we don't need to show all the entries at one page. 
@legendarykamal any updates on this?

**Comment by legendarykamal** [comment]
That yes is a little Ambivalent , If we don't want to show all at 1 pg . Then , we need this PR right ?

Updates , I am not in sync with what the sweeping changes are ? as reflected by @leecalcote . So , I will work on this only if its neccessary to this point of time.

**Pull request closed without merging**
