### PR TITLE
feat: introduce sorting to catalogs page

### LINKED ISSUE #1355: Introduce Sorting of Cards in Meshery Catalog
Introduce sort by option as a dropdown in Meshery Catalog, which arranges the cards alphabetically and on the basis of time of update, both in ascending and descending manner.  

For reference take a look at [meshery.layer5.io/catalog](https://meshery.layer5.io/catalog)

### Screenshots / Mockups

---
<h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Lucif3r-in**
**Description**

This PR fixes #1355 

**Notes for Reviewers**
Introduced sorting to catalog page

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by iArchitSharma** [comment]
@Lucif3r-in I see a problem here, when (Z-A) is selected once and than (A-Z) is selected again
See the order of cards

**Comment by Lucif3r-in** [comment]
@iArchitSharma I guess it is fixed now. I have changed the filter to `pattern.name`

**Comment by iArchitSharma** [comment]
@Lucif3r-in make sure that this card sticks to bottom all the time
image

**Comment by Lucif3r-in** [comment]
@iArchitSharma Done🚀🚀.
Changes made:
- Introduced a new attribute status in index.html that fetches if the status of the card (i.e ComingSoon)
- Used status attribute to append the card always at the end of the list irrespective of sorting method

**Comment by iArchitSharma** [comment]
LGTM!
Thanks @Lucif3r-in 

/ @sudhanshutech

**Comment by Lucif3r-in** [comment]
Should we have a search feature similar to meshery cloud?

**Review by abhijeetgauravm — COMMENTED** [review]
But if we sort by Alphabetically(A-Z) here wasm filter one arent getting sorted 
image
Similarly when we are sorting by Alphabetically(Z-A) u can see the inconsistency there!
image

**Comment by Lucif3r-in** [comment]
> But if we sort by Alphabetically(A-Z) here wasm filter one arent getting sorted image Similarly when we are sorting by Alphabetically(Z-A) u can see the inconsistency there! image

I guess as there are two different files we are checking from `card.html` and `wasm-card.html` this issue is happening. Let me check what I can do

**Comment by Lucif3r-in** [comment]
Closing this PR due to errors caused by DCO😑. Will do a new PR

**Pull request closed without merging**
