### PR TITLE
bring-wasm-filters-back

### LINKED ISSUE #1304: [Catalog] No WASM Filters displayed
### Description
Visit https://meshery.io/catalog/webassembly or click the WebAssembly radio button on meshery.io and find that no WASM filters are displayed.

### Expected Behavior

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by vishalvivekm**
**Description**

This PR fixes #1304 

**Notes for Reviewers**
Screenshot 2023-07-22 123728
<br><br>
Screenshot 2023-07-22 123801

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by GaganpreetKaurKalsi** [comment]
Ah great 👍! 
Are we looking to add "Wasm filter" name as well to top-right corner of the card like other cards are having?
@vishalvivekm

**Comment by vishalvivekm** [comment]
> Ah great 👍! Are we looking to add "Wasm filter" name as well to top-right corner of the card like other cards are having? @vishalvivekm

OH yes 
Thanks @GaganpreetKaurKalsi 😄

**Review by GaganpreetKaurKalsi — APPROVED** [review]
Looks great @vishalvivekm 👍 💯

**Review by Chadha93 — APPROVED** [review]
Good @vishalvivekm

**Comment by vishalvivekm** [comment]
> Good @vishalvivekm

Thank you @Chadha93 @GaganpreetKaurKalsi :)

**Pull request merged**
