### PR TITLE
Enhance the twitter feed in the footer

### LINKED ISSUE #861: Enhance the twitter feed in the footer.
**Current Behavior**
The feed in the footer looks odd and it is not consistent with other cards on the website.

**Desired Behavior**
I want to add some CSS style to make it look like this.
expected

**Screenshots / Mockups**
Current styling:
current

**Alternatives**

---
<h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by K0more**
This PR fixes #861 

This PR enhances the twitter feed CSS to have rounded corners.

Signed-off-by: k0more <arch.phenon@gmail.com>

### CODE REVIEW

**Comment by K0more** [comment]
sorry it took this long, I had exams and it took sometime to set up the server environment.

**Comment by K0more** [comment]
Oh btw can you add the hacktoberfest accepted label on this as well, it'd be really appreciated

**Comment by K0more** [comment]
@leecalcote coming in clutch as always 👍

**Review by YashKamboj — COMMENTED** [review]
@K0more LGTM!!! , Great Work

**Review by YashKamboj — APPROVED** [review]

**Comment by K0more** [comment]
> @K0more LGTM!!! , Great Work

Tyty

**Comment by leecalcote** [comment]
Uh-oh. While the Twitter Feed displays with rounded corners in Chrome, it still displays with sharp corners in Safari.

**Comment by leecalcote** [comment]
> Uh-oh. While the Twitter Feed displays with rounded corners in Chrome, it still displays with sharp corners in Safari.

Is this a browser that you have access to?

**Comment by K0more** [comment]
> > Uh-oh. While the Twitter Feed displays with rounded corners in Chrome, it still displays with sharp corners in Safari.
> 
> Is this a browser that you have access to?

Yeah, I don't have a personal ios device but I have a Mac lab in my college, though I'm pretty confused about the css in safari.

**Comment by K0more** [comment]
@leecalcote This issue has been fixed as of issue #818

**Comment by leecalcote** [comment]
> @leecalcote This issue has been fixed as of issue #818

@K0more, ok, good deal. Should we close this PR or is it still needed?

**Comment by K0more** [comment]
> > @leecalcote This issue has been fixed as of issue #818
> 
> @K0more, ok, good deal. Should we close this PR or is it still needed?

I don't think we do, apparently there were some excessive CSS that @legendarykamal fixed which was causing the sharp edges, and some overflow issues.

**Comment by leecalcote** [comment]
> I don't think we need this PR, apparently there were some excessive CSS that @legendarykamal fixed which was causing the sharp edges, and some overflow issues.

Oh, I see. Ok, thank you very much for this help, @K0more. 👍

**Pull request closed without merging**
