### PR TITLE
kuma.svg file is missing #1212

### LINKED ISSUE #1212: kuma.svg file is missing
### Description

Kuma.svg file is missing. 

### Expected Behavior

Not show any errors.

### Screenshots

Screenshot (92)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by vaibhav-xt**
**Description**
I found four images from which I think two are used which are `kuma-color.svg` & `kuma-white.svg` and also I used these images.  The rest are only present in the images folder and not used. 
- kuma-color.svg
- kuma-icon-dark.svg
- kuma-icon-dark.svg
- kuma-white.svg

This PR fixes #1212 

**Notes for Reviewers**
In my opinion, we can delete the rest of the images. I checked the whole website and I think these are not used. 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Review by vishalvivekm — APPROVED** [review]
LGTM.
Thanks @vaibhav-xt :sunglasses:

**Comment by leecalcote** [comment]
The site fails to build...

**Comment by leecalcote** [comment]
Due to Ruby upgrade, perhaps...

**Comment by leecalcote** [comment]
Ruby environment upgraded to 3.2.2 in Netlify. Rebuilding.

**Pull request merged**
