### PR TITLE
Added icons to headings in footer #1543

### LINKED ISSUE #1543: Adding icons to headings in footer
### Description
I would like to request the addition of icons to the headings in the footer for better visual representation and user experience

### Expected Behavior
Users should be able to easily associate each footer heading with its corresponding content through the addition of icons.

### Screenshots
Screenshot (517)

I want to work on this issue. Please assign this issue to me 

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by hemantmm**
**Description**

This PR fixes #1543 

**Notes for Reviewers**

I have added icons to the footer of the meshery.io page

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by hemantmm** [comment]
@leecalcote @ritiksaxena124 would like to have a look at this issue.

**Comment by saurabh100ni** [comment]
Hey @hemantmm ,
Thanks for raising the PR, Please add this as your agenda in [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?pli=1#heading=h.69qskjv558bk) to discuss it in the Website Meeting tomorrow at 6:30 PM IST.

Subscribe to [community calendar ](https://layer5.io/community/calendar)for more details of meetings at Layer5.

**Comment by hemantmm** [comment]
Sorry for not attending the meet!

**Comment by hemantmm** [comment]
Hey, @leecalcote  @saurabh100ni will not be able to attend the meeting due to college at 6 pm when the meeting starts I will be traveling on the bus and reaching home around 7:30 pm.

So, could have a look at the PR?

**Review by vishalvivekm — CHANGES_REQUESTED** [review]
@hemantmm 

image

We might also wanna use white version of the colored logos i.e. that of Meshery, Catalog and etc.

**Comment by leecalcote** [comment]
@vishalvivekm can answer this.

**Comment by hemantmm** [comment]
@vishalvivekm you can check now!

image

**Comment by vishalvivekm** [comment]
@hemantmm closed?

**Comment by hemantmm** [comment]
@vishalvivekm actually by mistake some other files were pushed while pushing the changes that's why I have created a new PR.

**Pull request closed without merging**
