### PR TITLE
Resized and aligned images on blog pages for better UI

### PR DESCRIPTION
**Pull request by Mohith234**
**Description**
- Images have been resized on this [blog post](https://meshery.io/blog/validating-smi-conformance-with-meshery)
- A total of three changes were made.

**Screenshots ( Before and After Changes )** 
## **Change 1**
  image
  image

## **Change 2**
  image
  image

## **Change 3**
image
image

**Notes for Reviewers**
-  @thisiskaransgit suggested making a straight PR for this, so didn't create any issues regarding this.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@Mohith234 

Let's discuss it on the websites call.
Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

**Comment by thisiskaransgit** [comment]
@Chadha93, this quick fix is good to go 🚀

**Review by Chadha93 — CHANGES_REQUESTED** [review]
The whole SMI section can be commented, SMI is no longer supported.

**Comment by Chadha93** [comment]
@thisiskaransgit As we discussed on yesterday's, please ensure the removal of SMI from the website.

**Comment by Chadha93** [comment]
@karnatisrinivas Preview failing...

**Comment by thisiskaransgit** [comment]
@Chadha93, update the branch please, the workflow will work fine

**Review by Chadha93 — APPROVED** [review]
For now, we are pointing it to resources on the layer. Thanks, you @Mohith234

**Pull request merged**
