### PR TITLE
[UI] Modifying Navbar dropdown such that it expands on text click

### LINKED ISSUE #812: [UI] Modifying Navbar dropdown such that it takes full width in mobile view
#### Current Behavior
Navbar dropdown doesn't take full width in mobile view and looks a bit weird.

Screenshot from 2022-06-07 02-05-36

#### Desired Behavior
To modify Navbar dropdown in meshery.io UI such that it takes full width in mobile view with it's items aligned to left. After clicking on Menu the dropdown will roll down from bottom taking full width and items aligned in left side

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by tinniaru3005**
Signed-off-by: Arunima Chaudhuri <arunimachaudhuri2020@gmail.com>

**Description**
- [x] Open sub-menus on click of the title
- [x] Make the width 40%
- [x] Prevent the getting started button from wrapping when the page loads
- [x] Make the nav-menu scrollable
- [x] Navbar width 100% for smaller screens
- [x] Add box-shadow to highlight that it is a menu

This PR fixes #812 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by legendarykamal — CHANGES_REQUESTED** [review]
Looks nice , some little bits to take care of
image

1> the width has some space on the left end.
2> The '+' icon on the right could be moved a little to the left for better UX.

**Comment by tinniaru3005** [comment]
navbar-meshery
Hey @legendarykamal , I guess it looks fine on the preview from my side. Can you please tell me on which device the error is comming. Also the space looks symmetric on both sides I guess.

**Comment by adithyaakrishna** [comment]
@tinniaru3005 On my device, the plus button goes to the right similar to @legendarykamal 's SS above. My device resolution is 2532×1170 pixels (WxH)

**Comment by tinniaru3005** [comment]
> @tinniaru3005 On my device, the plus button goes to the right similar to @legendarykamal 's SS above. My device resolution is 2532×1170 pixels (WxH)

For me, the menu is starting to show at 840px width. Can you please guide me on how can I make the changes?

https://user-images.githubusercontent.com/62856848/200189438-d0e0a945-41ac-44e1-92f4-bdff90a77af9.mp4

**Comment by YashKamboj** [comment]
@tinniaru3005  great work !!!, just one issue I noticed which can be solved in this pr . On many resolutions (like in 830px) the menu covers half the page which is not needed. So why don't you reduce its width.

**Review by YashKamboj — COMMENTED** [review]
@tinniaru3005  great work !!!, just one issue I noticed which can be solved in this pr . On many resolutions (like in 830px) the menu covers half the page which is not needed. So why don't you reduce its width

**Comment by tinniaru3005** [comment]
Hey @YashKamboj, is the width fine now?

**Review by asubedy — CHANGES_REQUESTED** [review]
image
The getting started button is wrapping when the page loads, please change it so that it does not wraps on page load

**Review by asubedy — CHANGES_REQUESTED** [review]
When the user changes from smaller resolution to bigger resolution the position of the menu components changes completely, please have a look at this too.
image

**Review by asubedy — CHANGES_REQUESTED** [review]
I guess we can make the menu scrollable, but make the scrollbar hidden.
image

**Comment by tinniaru3005** [comment]
Hey @asubedy, I guess we can raise an issue for these changes and solve it in a different PR. The issue which I am working on here is related to the navbar dropdown menu and it is solved.

**Comment by tinniaru3005** [comment]
Hey @asubedy, I have made the changes and added the navbar. If I am trying to hide the navbar then it is becoming unscrollable. Can you please give some suggestions on how I can modify the code to hide the scrollbar but still keep the menu scrollable?

**Comment by asubedy** [comment]
@tinniaru3005 you can refer this

https://www.w3schools.com/howto/howto_css_hide_scrollbars.asp

**Comment by tinniaru3005** [comment]
> @tinniaru3005 you can refer this
> 
> https://www.w3schools.com/howto/howto_css_hide_scrollbars.asp

Ya I did it. Thanks :)
Let me know if the changes look fine now

**Comment by Krishna2323** [comment]
@tinniaru3005, pls recheck the PR with recent implementation of dark mode.
One thing I would suggest is, instead of hiding the scrollbar we should show the scrollbar to not to confuse the user.

https://user-images.githubusercontent.com/85894871/204044676-d9d4c5ca-c408-46bc-a7c9-84feed29e988.mp4

**Comment by tinniaru3005** [comment]
Hey @asubedy, What do you think about it? Should I make the scrollbar visible or is it fine?

**Comment by asubedy** [comment]
ok @Krishna2323 does raise a good point, it might be confusing to the user if we don't have scrollbar. Since layer5.io website too have scrollbar on its menu, to drive consistency lets keep the scroll bar on the menu here too. Other's changes look all good

**Comment by tinniaru3005** [comment]
@asubedy does it look fine now?

**Review by asubedy — APPROVED** [review]
Looks Great. 🚀 Thank you @tinniaru3005

**Comment by Krishna2323** [comment]
@tinniaru3005, PR looks nice, just add a background for the scrollbar track and pls check at what breakpoint the navbar is for mobile/tablet view, I don't think it is 1140px.

**Comment by tinniaru3005** [comment]
> @tinniaru3005, PR looks nice, just add a background for the scrollbar track and pls check at what breakpoint the navbar is for mobile/tablet view, I don't think it is 1140px.

Hey, the breakpoint is 1140px. Also, I think transparent looks better. There is no need to give a background.

https://user-images.githubusercontent.com/62856848/204097211-0b163646-7fce-4f1c-b405-afbc654df726.mp4

**Comment by Krishna2323** [comment]
@tinniaru3005, the transparent looks better but how would the user know that, this is scrollbar or a side border or some design. That would be confusing.

**Comment by tinniaru3005** [comment]
Hey @leecalcote does the navmenu changes look fine now?

**Comment by leecalcote** [comment]
I'm tagging in the big guns, @Krishna2323, for comment.

**Comment by tinniaru3005** [comment]
> I'm tagging in the big guns, @Krishna2323, for comment.

Ya sure. Thanks for that :)

**Comment by Krishna2323** [comment]
@tinniaru3005, Your PR is still not ready, it took me to 15 min to figure the correct solution.
Your PR hides the Meshery logo below 600px of width:
Screenshot 2022-12-04 030352
My solution to this:
Screenshot 2022-12-04 030130

You have to change the html file also. If you need any help regarding this pls ask.

**Comment by tinniaru3005** [comment]
Hey @Krishna2323 is it fine now?

**Comment by Krishna2323** [comment]
@tinniaru3005, fine but only below 550px, just add media queries and remove the border for width greater than 1140px.
Screenshot 2022-12-04 034208

**Comment by tinniaru3005** [comment]
@Krishna2323 is it fine now?

**Comment by Krishna2323** [comment]
@tinniaru3005, for smaller width it should display like this:
Screenshot 2022-12-04 030130

And for larger screen's it should stay like it is now:
Screenshot 2022-12-04 035843

**Comment by tinniaru3005** [comment]
@Krishna2323 do you mean the toggle button should be beside the menu as currently it is commung down?

**Comment by tinniaru3005** [comment]
Hey @Krishna2323 can you push the changes into this PR?

**Comment by tinniaru3005** [comment]
@Krishna2323 I have made the changes. Can you confirm if it looks fine now?

**Review by legendarykamal — CHANGES_REQUESTED** [review]
for <560px @tinniaru3005 can we give it a full width from right too ? 
image

**Review by eeshaanSA — CHANGES_REQUESTED** [review]
Unskew the darkmode toggle switch, @tinniaru3005

**Comment by tinniaru3005** [comment]
> Unskew the darkmode toggle switch, @tinniaru3005

Hey can you explain what do mean by unskew. Should I add a padding?

**Comment by tinniaru3005** [comment]
> for <560px @tinniaru3005 can we give it a full width from right too ? image

Can you guide me on how to do it

**Comment by eeshaanSA** [comment]
image
Align it with menu hamburger

**Comment by tinniaru3005** [comment]
@eeshaanSA does it look good now?

**Review by eeshaanSA — DISMISSED** [review]
Looks good, @tinniaru3005 🚀
Thanks

**Comment by Krishna2323** [comment]
@tinniaru3005, pls change this, after that its good to be merged.
Screenshot 2023-01-12 195621

**Comment by tinniaru3005** [comment]
> @tinniaru3005, pls change this, after that its good to be merged. Screenshot 2023-01-12 195621

Change this means. Can u please describe what exactly needs to be changes. It will help me to avoid any confusion

**Comment by Krishna2323** [comment]
@tinniaru3005, it should be white

**Comment by tinniaru3005** [comment]
> @tinniaru3005, it should be white

Okay so the background of the navmenu should be white. Right?

**Comment by Krishna2323** [comment]
@tinniaru3005, the plus icons.

**Comment by tinniaru3005** [comment]
> @tinniaru3005, the plus icons.

Okay. Sure. Will do that today.

**Review by Krishna2323 — DISMISSED** [review]
LGTM 👍.

**Comment by tinniaru3005** [comment]
@Nikhil-Ladha can you please review the PR and if the changes look fine to you merge it.

**Comment by tinniaru3005** [comment]
@leecalcote can you please confirm if the changes look good to you?

**Review by asubedy — APPROVED** [review]
Wow, it has been a long time since this PR opened. All the changes look good to me, if there are any other issues let's move it to some other PR,. Thank you @tinniaru3005 for seeing this through, great work 🚀

**Pull request merged**
