### PR TITLE
enlistment of all platforms

### LINKED ISSUE #470: Enlistment of all platforms missing on Meshery installation page
**Current State of the Meshery.io site**
For now, the site provides instructions for 4 diff platforms for installing Meshery. But this is really outdated! There are many platforms available as compared to https://layer5.io/meshery

image

image

**Desired State of the Meshery.io site**
Add all kinds of platforms on that page, plus keep the info updated and clean

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

### PR DESCRIPTION
**Pull request by NikhilSharma03**
Signed-off-by: Nikhil <nikhilsharmamusic2000@gmail.com>

**Description**
Updated the platform list for installing Meshery.
## Before
Old

### Added 
- AKS
- Minikube
- KinD
- Helm Chart
- Google Kubernetes Engine
- AWS Elastic Kubernetes Service

New

This PR fixes #470 

**Notes for Reviewers**
I used https://layer5.io/service-mesh-management/meshery/getting-started for reference.

119934531-8a8cf480-bfa3-11eb-952c-69ace3562d00

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by alphaX86** [comment]
Nice @NikhilSharma03 I'll ping other reviewers so that they'll check

**Review by alphaX86 — APPROVED** [review]
LGTM 👍 Waiting for other reviewers

**Comment by NikhilSharma03** [comment]
Thank you @alphaX86 . Yeah Sure.

**Comment by leecalcote** [comment]
Hello! Very nice, @NikhilSharma03 😄

**Comment by NikhilSharma03** [comment]
Thank you @leecalcote 😄.

**Comment by leecalcote** [comment]
@NikhilSharma03 will you kindly have a look at the formatting in mobile view?

458BC28E-B1C4-4B9E-A0D7-6C7BAE8443C3

**Comment by NikhilSharma03** [comment]
@leecalcote Sorry actually I was waiting for approval that the list is correct so I can start working on the responsiveness part. But got busy with getNighthawk and forgot 😅.

## After Changes
Screenshot from 2021-06-24 16-05-56

## Note For Reviewer
Let me know if there are any other changes we can make. Thank you.

**Comment by alphaX86** [comment]
@NikhilSharma03 this is very nice now! 😁

@leecalcote out of context, does Meshery support k3s cluster for now?

**Comment by leecalcote** [comment]
> @NikhilSharma03 this is very nice now! 😁
> 
> @leecalcote out of context, does Meshery support k3s cluster for now?

Regarding k3s, @nunix is our resident authority.

**Comment by nunix** [comment]
The demos I've done in the past, were done in majority on k3d.
Now, being on Windows, this means there's a setup beforehand to be done, but K3s should not have any issues running Meshery.

Let's have an hands-on session in the coming weeks, so we check together what roadblocks are there (if any)

**Comment by alphaX86** [comment]
I was taught to use k3s using a VM via Vagrant so I hope that won't be problem in setup....

**Comment by NikhilSharma03** [comment]
@leecalcote Can you please review? Thank you.

**Review by includestdlibrary — APPROVED** [review]
LGTM

**Comment by leecalcote** [comment]
@NikhilSharma03, not a huge issue, but heads-up (scrollbars):
Screen Shot 2021-07-01 at 11 54 56 PM

**Comment by NikhilSharma03** [comment]
Will make sure to fix that in the next PR.

**Pull request merged**
