### PR TITLE
[Ui]  Catalog section responsiveness

### LINKED ISSUE #784: Responsiveness lagging on the catalog section
**Description**
A brief description of the issue.
the responsive design of the meshery.io/catalog has some bugs as shown in the image below:

**Expected Behavior**
A brief description of what you expected to happen.
the logos shouldn't be cropped when in responsive form
**Screenshots**
Add screenshots, if applicable, to help explain your problem.
WhatsApp Image 2022-07-23 at 3 05 29 AM
**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**
1. Go to 'meshery.io/catalog'
2. See error when switched to mobile format

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Rohith-Raju**
Signed-off-by: Rohith Raju <rohithraju488@gmail.com>

**Description**
Made the catalog section responsive 

This PR fixes #784 

**Notes for Reviewers**
Since this [Pr](https://github.com/meshery/meshery.io/pull/767) is yet to merge, I've yet to fix the responsiveness
for the catalog section 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Rohith-Raju** [comment]
image
image

**Review by YashKamboj — CHANGES_REQUESTED** [review]
Please reduce the space between the image and the description
Screenshot 2022-07-27 171111

**Comment by Rohith-Raju** [comment]
Sure @YashKamboj

**Comment by leecalcote** [comment]
https://github.com/meshery/meshery.io/pull/767 Is merged. 👍

**Comment by Rohith-Raju** [comment]
Yep @leecalcote, Working on it.

**Comment by Rohith-Raju** [comment]
Added grid layout to the radio buttons
image

**Comment by Rohith-Raju** [comment]
@YashKamboj @Rohith-Raju as of now cloud native catalog link has been removed from the dop down

**Comment by leecalcote** [comment]
@Rohith-Raju I think we're ok now:

Screen Shot 2022-08-05 at 6 21 02 PM


We do need to fix the padding / margin issue that I left wherein the on hover background color isn't covering the full width of the menu on the righthand side.

**Comment by leecalcote** [comment]
We seem to still have a bit of overlap - 

Screen Shot 2022-08-05 at 6 30 07 PM

**Comment by Rohith-Raju** [comment]
> @Rohith-Raju I think we're ok now:
> 
> Screen Shot 2022-08-05 at 6 21 02 PM
> 
> We do need to fix the padding / margin issue that I left wherein the on hover background color isn't covering the full width of the menu on the righthand side.

@leecalcote Sure,I'll do that

**Comment by Rohith-Raju** [comment]
> We seem to still have a bit of overlap -
> 
> Screen Shot 2022-08-05 at 6 30 07 PM

@leecalcote too many overriding styles. I'll have to change classes, gonna be here for a while

**Review by PIYUSH-MISHRA-00 — APPROVED** [review]

**Review by PIYUSH-MISHRA-00 — APPROVED** [review]

**Comment by Rohith-Raju** [comment]
@leecalcote @YashKamboj

**Comment by YashKamboj** [comment]
@Rohith-Raju adding a collapse button would be a great addition

**Comment by Rohith-Raju** [comment]
@YashKamboj I agree, But aren't we re-designing the entire meshery.io site?

**Comment by Rohith-Raju** [comment]
@leecalcote @YashKamboj  we good ?  


[screen-recorder-sat-aug-13-2022-13-47-36.webm](https://user-images.githubusercontent.com/55309324/184475517-bc0f6a51-0c68-4b81-ad82-f5e6db2df43b.webm)

**Comment by YashKamboj** [comment]
@Rohith-Raju load more looks great!!, Nice work!! But the feature to  filter  the filters not the best feature to add. A collapse button might be a better option. @debo19 views??

**Review by PIYUSH-MISHRA-00 — APPROVED** [review]

**Comment by Rohith-Raju** [comment]
Oh,ok @YashKamboj

**Comment by Rohith-Raju** [comment]
@YashKamboj  @leecalcote  something like this ?
[screen-recorder-thu-aug-11-2022-21-25-55 (1).webm](https://user-images.githubusercontent.com/55309324/185542965-17297f11-1191-45dc-aae4-c9282b720421.webm)

**Comment by leecalcote** [comment]
Demo'ed on today's Websites meeting?

**Comment by Rohith-Raju** [comment]
@leecalcote I couldn't, ran outta time..

**Comment by Rohith-Raju** [comment]
@leecalcote, @YashKamboj now the button looks like this.
image

**Comment by leecalcote** [comment]
Ooooh, I like it! @warunicorn19 @asubedy @YashKamboj how does this strike you?

**Comment by leecalcote** [comment]
@PIYUSH-MISHRA-00, thank you for reviewing this PR. What do you think of the latest, proposed filter icon / button?

**Comment by warunicorn19** [comment]
Looks great!

**Comment by asubedy** [comment]
Ooo, nice, this one looks better 👍

**Review by leecalcote — APPROVED** [review]

**Comment by Rohith-Raju** [comment]
Maybe a lil rounded corners on the button.. What ya'll thinking?

**Comment by Rohith-Raju** [comment]
Thank you folks!!.. Do we get this merged if everything is a go?

**Comment by leecalcote** [comment]
Merge when ready @asubedy @warunicorn19

**Review by asubedy — CHANGES_REQUESTED** [review]
image
@Rohith-Raju while the page is responsive there seems to be some alignment issue on the coming soon card, could you look into this.

**Comment by Rohith-Raju** [comment]
Sure @asubedy

**Comment by Rohith-Raju** [comment]
@asubedy could you check it now ?

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
Screenshot 2022-09-21 at 3 30 57 PM
Screenshot 2022-09-21 at 3 31 03 PM

There are still some responsive issues, and the filters seem to be appearing twice.

**Comment by Rohith-Raju** [comment]
Ok @warunicorn19 , on it!!

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
