### PR TITLE
Fixed : Adding margin on Service Mesh Interface page to adjust UI

### LINKED ISSUE #1021: Adding Margin from Top to Bottom
### Current Behavior

WhatsApp Image 2023-02-13 at 8 41 55 PM

### Desired Behavior
Adding Margin from top to bottom to improve UI  
image

### link :-https://meshery.io/service-mesh-interface
---
<h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Rishikavishnoi**
**Description**

This PR fixes #1021

**Notes for Reviewers**
Adding Margin to the  Legend section on the Service Mesh Interface page
 link:-https://meshery.io/service-mesh-interface

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Avi-88** [comment]
Hi @Rishikavishnoi , the changes look good, but can you please also make the text and icon center aligned within the tab 

image

Also I had a suggestion about the table div, can we remove the legend tab from within the scrollable div and make it centered for smaller screens. Currently it's inside the scrollable div which serves no real purpose and gets cutoff if we scroll. Do let me know your thoughts on this , thanks

image

**Review by eeshaanSA — APPROVED** [review]
Great. LGTM

**Review by tinniaru3005 — APPROVED** [review]
LGTM :)

**Comment by leecalcote** [comment]
Review pending a response to @Avi-88's feedback...

**Comment by Chadha93** [comment]
@Rishikavishnoi  Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by Rishikavishnoi** [comment]
> @Rishikavishnoi Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

Actually Today I didn't attend the meeting

**Comment by Rishikavishnoi** [comment]
@Avi-88 can you please describe more about the changes required?

**Comment by Avi-88** [comment]
> Hi @Rishikavishnoi , the changes look good, but while you are at it can you please also make the text and icon center aligned within the tab
> 
> image
> 
> Also I had a suggestion about the table div, can we remove the legend tab from within the scrollable div and make it centered for smaller screens. Currently it's inside the scrollable div which serves no real purpose and gets cutoff if we scroll. Do let me know your thoughts on this , thanks
> 
> image

Sorry for the delayed response @Rishikavishnoi , as mentioned in the above comment I was just suggesting that the icons and the text in the legend tab aren't center aligned with their container. You can see the incomplete one is stuck at the top of the container , we just need to center them. And the second thing is that the legend tab is included inside the scrollable div which is just meant to be for the table. So when we scroll the table on smaller screens the legend tab gets cutoff , so we need to move it out of the scrollable div and style it accordingly. Let me know if you need some more help, good luck !

**Comment by Chadha93** [comment]
@Rishikavishnoi  Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by Chadha93** [comment]
@Avi-88 Will you this one is addressed with your feedback? Assigning this to you. cc @Rishikavishnoi

**Comment by Avi-88** [comment]
Ok , I'll get this done

**Comment by vishalvivekm** [comment]
> Ok , I'll get this done

would you like to share about your progress? @Avi-88

**Comment by vishalvivekm** [comment]
> > > Ok , I'll get this done
> > 
> > 
> > would you like to share about your progress? @Avi-88
> 
> Oh sorry about that, I was supposed to hand this over to another contributor to work on. I apologize for the confusion, I wont be able to join todays website call, could you maybe bring this up there as a 'call for volunteers' @vishalvivekm ?

Yeah okay @Avi-88

**Comment by vishalvivekm** [comment]
> I'll work on this issue @Avi-88

Great, if you can please comment in the issue's comments #1021  @Savio629

**Comment by leecalcote** [comment]
@Savio629 given your other PR #1125, are we ready to close this PR?

**Comment by Savio629** [comment]
> @Savio629 given your other PR #1125, are we ready to close this PR?

Yeah, we can close this pr @leecalcote

**Comment by Savio629** [comment]
> @Savio629 given your other PR #1125, are we ready to close this PR?

Yeah, we can close this pr @leecalcote

**Pull request closed without merging**
