### PR TITLE
Update homePage.html

### PR DESCRIPTION
**Pull request by rabbanirizwan**
Change current box shadow.

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by GaganpreetKaurKalsi — CHANGES_REQUESTED** [review]
Welcome @rabbanirizwan! Good to see you are looking for some enhancements to work on. Well for me the current `box-shadow` looks good only. The black `box-shadow` is getting too much attention. No need for any change. 
Maybe you can try centre aligning the text vertically to get started.

**Review by Krishna2323 — CHANGES_REQUESTED** [review]
@rabbanirizwan, looks fine in the dark mode but not in light mode. Pls use the box shadow variable.
If you need any help, pls tell.

**Comment by leecalcote** [comment]
@Krishna2323, to one of your earlier questions, "Yes, we need the contributor guide enhanced with dark mode documentation."

**Comment by leecalcote** [comment]
Reference - https://github.com/meshery/meshery.io/issues/922

**Comment by leecalcote** [comment]
> @rabbanirizwan, looks fine in the dark mode but not in light mode. Pls use the box shadow variable.
> If you need any help, pls tell.

@rabbanirizwan are you still working on this feedback? Not hearing from you by end of this week, we'll assume that you've abandoned it. Do send word if you could use some assistance.

**Comment by UtkarshMishra12** [comment]
@rabbanirizwan Progress??

**Pull request closed without merging**
