### PR TITLE
Feat:fixed integration page

### LINKED ISSUE #1181: [UI] Text-invisiblity in integrations page
### Description

Currently the text isnt placed correctly and its also causing invisiblity dark mode

image

### Expected Behavior

We could remove the extra space from the top and use this to utilize the text-boxes.
image
image
image

image
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Ghat0tkach**
**Description**

This PR fixes #1181 

**Notes for Reviewers**
Fixed the invisible text and extra space in the header.
You may wonder why there is so much space in between, The purpose is to manage the overlap of 3-D grids with the main buttons as well as the text bar. 

https://github.com/meshery/meshery.io/assets/59855919/d25a49ec-cc5d-46b9-85de-ed49ed55b4de

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by thisiskaransgit — CHANGES_REQUESTED** [review]
Thanks for this, please make sure the changes are consistent for all screen sizes.

**Comment by Ghat0tkach** [comment]
> Thanks for this, please make sure the changes are consistent for all screen sizes.

yes thanks for the review , currently working for the same

**Comment by Ghat0tkach** [comment]
@thisiskaransgit actually im confused , my current layout is responsive as per the size standards.

https://github.com/meshery/meshery.io/assets/59855919/fa274bf3-d2cf-477d-9d67-b5242ca9cab1

**Comment by Ghat0tkach** [comment]
closing this as it has been completed by #1209

**Pull request closed without merging**
