### PR TITLE
Fixed hover color and removed padding from Programs page

### LINKED ISSUE #605: Newsletter Subscription enhancement on Programs page
**Description**
 On hover, the subscribe button blends with the background completely. (On [Programs](https://meshery.io/programs) page)

https://user-images.githubusercontent.com/85789734/139727744-b019bd94-0863-40c5-bf9b-1bd3a092748a.mp4

**Expected Behavior**

1) Change the hover effect of the subscribe button.
2) Remove the gray band between the footer and the newsletter section.

**Screenshots**

band

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by roman-rezinkin**
# Description
This PR addresses the changing of the hover behavior for the subscribe button located on the programs page. As seen in the original issue, the hover over the subscribe button caused it to blend in with the background, which would cause accessibility issues for users. The other section that this PR addresses, is the padding that existed before the footer section, which I have also removed. If you have any requests for changes, please feel free to comment. 

Signed-off-by: roman-rezinkin <roman.rezinkin@hotmail.com>

This PR fixes #605 
## Original Behavior
https://user-images.githubusercontent.com/85789734/139727744-b019bd94-0863-40c5-bf9b-1bd3a092748a.mp4
## Behavior after fix

https://user-images.githubusercontent.com/17882264/144755388-9f190211-a5ed-4b30-bc3b-d918d926d332.mp4

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by debo19** [comment]
Looks good @roman-rezinkin 🚀 While you're there, I just noticed that in mobile view, the email input is not aligned with the other two. Do you think you can fix that in this PR itself?

align-programs

**Comment by roman-rezinkin** [comment]
Sure thin @debo19, let me look into it 😃

**Comment by roman-rezinkin** [comment]
I have fixed it, just added some small padding on screen sizes under 602px.
#### Image
image

**Review by debo19 — APPROVED** [review]
LGTM 🎉 Thanks @roman-rezinkin

**Review by warunicorn19 — APPROVED** [review]
Looking good, Thank you @roman-rezinkin

**Pull request merged**
