### PR TITLE
Added a Legend below the table in ```smi.html```

### LINKED ISSUE #616: A legend below the table
**Current State of the Meshery.io site**

There is no legend below the table on this  [page](https://meshery.io/service-mesh-interface).

**Desired State of the Meshery.io site**

We need a legend below the table on this [page](https://meshery.io/service-mesh-interface) like we have on this [page](https://layer5.io/service-mesh-landscape)

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by roman-rezinkin**
**Description**
This PR addresses the addition of a Legend below the table in the ```smi.html``` file. I have added images that represent the same status checkmarks as the ones represented in the table. Secondly, I followed the outline that the issue suggested, to try and recreate the legend.

This PR fixes #616 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Mr-DG-Wick** [comment]
Very nice @roman-rezinkin . It just need a few more tweaks. Would you try increasing the width and reduce the height of the Legend box? Would like to see how it looks then.

**Comment by warunicorn19** [comment]
@roman-rezinkin there's also as issue with the table itself, it appears to be non-responsive in mobile view, would you like to take a hand at fixing that as well in this PR?

**Comment by roman-rezinkin** [comment]
> Very nice @roman-rezinkin . It just need a few more tweaks. Would you try increasing the width and reduce the height of the Legend box? Would like to see how it looks then.

I have done so in my latest commit. I also updated the images, so that they do not include a white background, as it introduced some weird spacing.

**Comment by roman-rezinkin** [comment]
> @roman-rezinkin there's also as issue with the table itself, it appears to be non-responsive in mobile view, would you like to take a hand at fixing that as well in this PR?

I am going to take a look into it, and see if I cant fix it :)

**Comment by shubham-tyagi** [comment]
Great work @roman-rezinkin, But I think our legend should be as it is on this [link ](https://layer5.io/service-mesh-landscape). Because I think it would make more sense if we have same legend on both the link moreover small laptop view and tab view is better here  [link ](https://layer5.io/service-mesh-landscape). I guess we should not decrease the height. 


"incompatible" looks out of place (It's not in the middle height wise).


thoughts? @Mr-DG-Wick @warunicorn19

**Review by shubham-tyagi — COMMENTED** [review]
Great stuff, suggested some changes already. Don't do them already let see the views of others on my suggested change if all agree then you can move forward with those changes.

**Comment by Mr-DG-Wick** [comment]
> "incompatible" looks out of place (It's not in the middle height wise).

Yup agreed on this one @shubham-tyagi . It needs fixing.
The new height and width are looking nice to me, given that table is different in this page then on the layer5 page. 

Also, @roman-rezinkin pls align the `Hover for details of test failures.` part in the center. So that equal white space is present on both the top and bottom. See this : 
site_review_legendTable

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
hey @roman-rezinkin, so you are almost there, just a couple of small changes. 
We want the legend to be as similar as possible to the one on layer5.io
Screenshot 2021-11-19 at 3 20 41 PM

So, let's get the legend to be a tad bigger, and the text in the legend to be completely centred. Also, good job on getting the table to be responsive, the horizontal scroll there is really cool😄.

**Comment by roman-rezinkin** [comment]
I have updated the alignment issues, and got the legend to be a tad bigger. Let me know what you guys think @Mr-DG-Wick @warunicorn19 @shubham-tyagi

### Screenshot
image

**Comment by shubham-tyagi** [comment]
Hey @roman-rezinkin, Everything looks great, except for just one thing. On my laptop when I checked for responsiveness I am seeing a line going over the legend, could you check what's going wrong over there ?

**Comment by roman-rezinkin** [comment]
> Hey @roman-rezinkin, Everything looks great, except for just one thing. On my laptop when I checked for responsiveness I am seeing a line going over the legend, could you check what's going wrong over there ?
> 
> 

Ah, maybe some padding is off somewhere. Let me give that a fix!

**Comment by leecalcote** [comment]
Good stuff, @roman-rezinkin. Thanks for working on this.

**Comment by roman-rezinkin** [comment]
I have fixed the padding, where the horizontal scrollbar was on top of the Legend.
Picture: 
image

**Comment by shubham-tyagi** [comment]
Everything looks good @roman-rezinkin, What do you think about having a liner legend for tablet mode? I think a linear legend would fit rightly for tab mode also.

**Comment by roman-rezinkin** [comment]
Updated the width to be 700px, which allows for the legend to be columns instead of rows. 
Picture with change:
image

**Comment by shubham-tyagi** [comment]
Can we have something like this for tablet mode @roman-rezinkin? And what do you think about doing the size of white box inside a bit smaller as it is on https://layer5.io/service-mesh-landscape#smi

**Review by shubham-tyagi — CHANGES_REQUESTED** [review]
Can we have something like this for tablet mode @roman-rezinkin? And what do you think about doing the size of the white box inside a bit smaller as it is in the below image.

**Comment by roman-rezinkin** [comment]
> Can we have something like this for tablet mode @roman-rezinkin? And what do you think about doing the size of the white box inside a bit smaller as it is in the below image.
> 
> 

For sure, let me play around with the formatting of the table. It looks really good in this photo! @shubham-tyagi

**Comment by roman-rezinkin** [comment]
Here is the views for each device: @shubham-tyagi 
Desktop -
Desktop

iPadPro -
iPadPro

Ipad - 
Ipad

iPhoneX -
IPhoneX

**Review by shubham-tyagi — DISMISSED** [review]
Thank You, @roman-rezinkin, LGTM !!!

**Comment by shubham-tyagi** [comment]
@warunicorn19, Could you please see if there is anything else needed to be done here?

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
Just one small change @roman-rezinkin, if you check between 370px and 595px, the table and the legend are overflowing from the screen. I think it'd be best to keep the horizontal scroll there.

Screenshot 2021-12-05 at 10 30 39 PM

**Comment by roman-rezinkin** [comment]
@warunicorn19 I have made the changes, I did not see that break before, but that was probably because I was snapping to specific screen sizing's, so great catch 👍. I have adjusted it so that it will have horizontal scroll right under the iPad max width, which fixes this issue!

**Review by warunicorn19 — APPROVED** [review]
Thank you for this to the end @roman-rezinkin really good work here!

**Pull request merged**
