### PR TITLE
[Catalog] Dynamically load related cards inside the modal

### LINKED ISSUE #705: [Catalog] Create "related" pattern attribute
**Current State of the Meshery.io site**
Each pattern modal will show related patterns, but these are hard-coded, self-references. 

**Desired State of the Meshery.io site**
The json data model needs to evolve to include a `related` attribute, so that pattern ids can be listed in an array.

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by asubedy**
Signed-off-by: asubedy <frexpe@pm.me>

**Description**

This PR fixes #705 

**Notes for Reviewers**
I did not change the json data, instead manipulated on the frontend, if this is not something we wan, then I can revert it and actually change the json data.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
@asubedy can we limit it to 1 or 2 related patterns? and not have the coming-soon ones.

**Comment by leecalcote** [comment]
Merge conflicts...

**Review by warunicorn19 — COMMENTED** [review]
@asubedy if you could just limit it to show one card, then we can merge this PR

**Review by warunicorn19 — APPROVED** [review]
Looking good!

**Pull request merged**
