### PR TITLE
3D integrations page improvement

### LINKED ISSUE #1190: Visualization Sizing on Meshery Integrations Page
### Description
 Upon visiting the [Meshery integrations](https://meshery.io/integrations) page,  the visualization does not fit on the screen properly. This causes some visual elements to be cut off and makes it difficult to view all relevant information.
 
### Expected Behavior
The visualization on the Meshery integrations page should be adjusted so that it fits properly onto the screen

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by GaganpreetKaurKalsi**
### Description

**PR fixes #1190**

This PR includes following fixes
- Adjust all integration cards onto screen in middle for all different views (Table, Sphere, Helix, Grid)
- Position loader inside container containing integration cards.
- Improve UI of View buttons
- Define boundaries for 3d interaction area for better user experience. Currently there is no defined boundary visible to user, so he/she might struggle scrolling the page( user wants to scroll but being unable to find area outside interaction container). I have always struggled.

### See below screenshots for Before/After comparison 👇 👇 

|                                 |                      Before                     |                        After                     | 
| -------------------| ------------------------------- | ------------------------------ |
| **Adjust all cards on screen** | image | image |
| **Fix loader position (position it inside integration container)** | imageimage | image |
| **Button UI and position improvement** | image | image
| **Fix overlapping cards in sphere view, fix Grid view (grid cards overlapping text)** | imageimage | imageimage | 
| **Define boundaries for user interaction (user can interact with the 3D structure anywhere inside the area with dashed border). The 3D structure won't overflow outside the defined region** | image | image | 
| **Dark Mode** | image | image

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Yay! 🙂

**Review by kayceeDev — APPROVED** [review]
For this PR, Everything looks okay to me. LGTM!!

However, on the "All integration page" the animation probably just lags that visual and affects user experience. 

I would suggest that we can leave it simple like what we have in the Layer5.io website (Show a few integrations on the homepage and show the rest when the user clicks on "see all integrations".

Good job @GaganpreetKaurKalsi

**Review by 8rxn — APPROVED** [review]
Looks good to me 🚀

**Comment by 8rxn** [comment]
Great work on the PR @GaganpreetKaurKalsi 


There's one teeny tiny thing that I thought of, and would love to hear everyone's thoughts on this.

Not that it matters much, but usage of font-weight to hover felt just a little unnatural to me, 
with the buttons and everything my mind expected a background and shadow combination effect on hover instead.

**Comment by GaganpreetKaurKalsi** [comment]
> Great work on the PR @GaganpreetKaurKalsi
> 
> There's one teeny tiny thing that I thought of, and would love to hear everyone's thoughts on this.
> 
> Not that it matters much, but usage of font-weight to hover felt just a little unnatural to me, with the buttons and everything my mind expected a background and shadow combination effect on hover instead.

Yeah, I agree. I was trying that with the existing colors available in `rootvariables.scss` but didn't work out. Guess will add some new ones.

**Comment by GaganpreetKaurKalsi** [comment]
Does this look good, @8rxn ?? Let me know if you have some better color suggestions?

SPHERE is the hovered button
image

**Review by sudhanshutech — COMMENTED** [review]
This is good work @GaganpreetKaurKalsi , have you thought on how to improve the page performance because right now due many images in single `data.js` is giving very load to site in integrations page

**Comment by Chadha93** [comment]
Merge conflicts... @GaganpreetKaurKalsi

**Comment by GaganpreetKaurKalsi** [comment]
> This is good work @GaganpreetKaurKalsi , have you thought on how to improve the page performance because right now due many images in single `data.js` is giving very load to site in integrations page

Yeah, the performance is poor. Haven't thought about how to improve it yet.

**Comment by leecalcote** [comment]
Yes, yes, yes, and yes. @GaganpreetKaurKalsi 👏

**Review by Rajivkumawat3 — COMMENTED** [review]
Looks good to me .

**Pull request merged**
