### PR TITLE
Publish the "Learning Paths" blogpost (Issue #2323).

### PR DESCRIPTION
**Pull request by NPDebs**
**DESCRIPTION**
This PR fixes issue [#2323](https://github.com/layer5io/layer5/issues/2323)
A new blog post, with the title "Layer5 Learning Paths" (written by a community member) has been added to the layer5.io website.

Blogpost_Preview

**### Notes for Reviewers**
The blogpost can be found on this path => https://layer5.io/blog/layer5-learning-paths/
Thank you!

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks. Although, this blog post is to be published on layer5.io/blog. 

Also, a fair warning - this draft has not been reviewed for grammar and content, and so, it has yet to be approved as ready for publishing. // @Anita-ihuman

**Comment by Anita-ihuman** [comment]
> Thanks. Although, this blog post is to be published on layer5.io/blog.
> 
> Also, a fair warning - this draft has not been reviewed for grammar and content, and so, it has yet to be approved as ready for publishing. // @Anita-ihuman

Okay, 
I left dropped the draft for review, I did not see any changes, that's why I went ahead with the issue.
@NPDebs Please pause this PR until we have completely reviewed the draft.

**Comment by NPDebs** [comment]
Hi Lee. Thanks for responding so promptly!

My sincere apologies for this terrible oversight. I'm dying of mortification over here! 

A new PR will be ready at the end of the day (on the right repo 😅).
Do let me know if I can contribute in any way to _draft review_ process. Thanks! @Anita-ihuman

**Comment by NPDebs** [comment]
@Anita-ihuman Oh. That's alright.
I'm ready when you are...

**Comment by adithyaakrishna** [comment]
@Anita-ihuman @NPDebs Closing this as per the comment by @leecalcote 
@NPDebs Could you please create a PR in this https://github.com/layer5io/layer5 repo for the blog?

**Comment by NPDebs** [comment]
Sure @adithyaakrishna. 👍🏻

**Comment by adithyaakrishna** [comment]
Awesome, thanks and looking forward to the PR 🚀 :)

**Pull request closed without merging**
