### PR TITLE
Added Remaining Integrations

### LINKED ISSUE #1005: [Integrations UI] Add remaining meshery integrations
### Description
[https://meshery.io/](url) website features only 80 integrations in contrast to the 150 integrations on the [https://layer5.io/](url) website.

### Expected Behavior
All the remaining integrations need to be added to the integrations section on meshery.io website.

## How to Implement

See https://github.com/meshery/meshery.io/issues/1005#issuecomment-1424666387

### Screenshots
**Meshery.io website**
image

**Layer5 wesbite**
image

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by gopivaibhav**
Signed-off-by: Gopi Vaibhav <gopivaibhav0@gmail.com>

**Description**
Added all the integrations so that it matches with [layer5.io](http://www.layer5.io) website

This PR fixes #1005 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks!  

Hmm. The dedicated integrations page doesn’t render in the deploy preview (or at least not on mobile).

**Comment by gopivaibhav** [comment]
> Thanks!
> 
> Hmm. The dedicated integrations page doesn’t render in the deploy preview (or at least not on mobile).

Hi @leecalcote 
When we visit the `/integrations` route in [meshery.io](https://meshery.io/) website, we can clearly see around 150 integrations visible on scrolling and I have rechecked it by inspecting the element class tag where the integration is present.

Screenshot from 2023-02-15 15-47-02

Please let me know if I need to change anything else.

**Comment by leecalcote** [comment]
Hmm. I only see about half of that on the home page...

**Comment by gopivaibhav** [comment]
> Hmm. I only see about half of that on the home page...

I didn't include all the integrations on the homepage because there will be no use of the All Integrations page then. We are displaying some of the integrations on the homepage and hence we are displaying a button to see all the integrations. 
PS- I have updated the number from 80+ to 150+ in the homepage as well to let users know that there are around 150 integrations and they have to visit `\integrations` to see all the integrations.

Please do let me know if this is not a right way to continue @leecalcote .

**Comment by asubedy** [comment]
@gopivaibhav The integrations does not seem to show on Safari
Screenshot 2023-02-17 at 05 01 46

**Comment by gopivaibhav** [comment]
> @gopivaibhav The integrations does not seem to show on Safari

@asubedy Can you please give me a suggestion on how to cross-check integrations on Safari? 
I use Brave browser and it's working on it. Is there any other way of verifying this issue other than downloading the Safari browser in my laptop?

**Comment by leecalcote** [comment]
The issue wouldn’t be specific to Safari. Check the deploy preview link above, which is what reviewers are looking at.

**Comment by leecalcote** [comment]
@asubedy this effort appears to be abandoned. Will you carry it forward?

**Comment by Chadha93** [comment]
@gopivaibhav  Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by leecalcote** [comment]
PR abandoned.

**Pull request closed without merging**
