### PR TITLE
[Features] Updated performance box responsiveness

### LINKED ISSUE #1160: [Features] Box responsiveness issue
### Description

I found a responsiveness issue on https://meshery.io/features.
After checking in the responsive mode, this bug is basically coming for screen sizes less than 406 in width.

### Expected Behavior

The box should properly encompass the text.

### Screenshots

For iPhone 12
image

For iPhone XR
image

### Enviroment:
 - OS: iOS
 - Browser: Safari 
 - Device: Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by aku1310**
**Description**

Updated box height from 40px to 45px to make it responsive for screens having less than 406 width.

This PR fixes #1160 

**Notes for Reviewers**

Before:
image

After:
image

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Review by Savio629 — COMMENTED** [review]
It would look better if you decrease the font size to medium for mobile devices 
medium

**Comment by aku1310** [comment]
> It would look better if you decrease the font size to medium for mobile devices medium

Okay, I will just do that. Thank you!

**Review by Savio629 — COMMENTED** [review]
You need to look out for this dimension 

perf

**Comment by aku1310** [comment]
Hi @Savio629, I've updated the breakpoint to 780px, as I saw 775px - 780px also looked too close to the box as reviewed by you. Thanks for pointing it out!

**Review by thisiskaransgit — APPROVED** [review]
Looks good to merge, thank you for your contribution :tada:

**Review by GaganpreetKaurKalsi — APPROVED** [review]

**Comment by GaganpreetKaurKalsi** [comment]
@aku1310 Nice work 👍  Keep contributing 🚀

**Pull request merged**
