### PR TITLE
added prosebot

### PR DESCRIPTION
**Pull request by Ayush7614**
Signed-off-by: Ayush Kumar [ayushknj3@gmail.com](mailto:ayushknj3@gmail.com)

Added  Prosebot 
*  Checks for grammatical errors in the Docs.
*  Analyzes spelling, prose and inclusive verbiage in Markdown and Text Files.
*  Provides an easy way to analyze documentation changes and ensure a consistency throughout

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
@Ayush7614, the addition of a bot like this seems like a good idea on the surface, but often turns out not to be. Can you provide output of what suggestions we can expect that it will make? Can you run this bot separately and show a report of its findings, so that we can determine whether its inclusion is ideal or not?

**Comment by Ayush7614** [comment]
> @Ayush7614, the addition of a bot like this seems like a good idea on the surface, but often turns out not to be. Can you provide output of what suggestions we can expect that it will make? Can you run this bot separately and show a report of its findings, so that we can determine whether its inclusion is ideal or not?

Hey @leecalcote Firstly Thanks for Reviewing my PR I am adding integration link so you can check



1 . Prosebot [Integration](https://github.com/apps/prosebot)
*  Checks for grammatical errors in the Docs.
*  Analyzes spelling, prose and inclusive verbiage in Markdown and Text Files.
*  Provides an easy way to analyze documentation changes and ensure a consistency throughout

After [installing the GitHub App on your repos](https://github.com/apps/prosebot), this Probot App listens for changes to Markdown files (.md) or text files (.txt) in pull requests and runs various checks against them to provide feedback on the English. Currently, the app checks for spelling, prose and inclusive verbiage. This is done by leveraging existing open source libraries, which you can find [listed below](https://github.com/prosebot/prosebot#credits). Here's how it looks in action:

[](https://user-images.githubusercontent.com/10660468/47381659-87844600-d6ce-11e8-8dc1-add68671dc85.png)image

**Comment by warunicorn19** [comment]
Hey, @Ayush7614 would you like to discuss this topic on the meshery dev call? 
Find the meeting link here: meet.layer5.io
Meeting minutes: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#
if you'd like to add your topic please go ahead.

**Comment by warunicorn19** [comment]
Abandoned PR, closing.

**Pull request closed without merging**
