### PR TITLE
Removed highlighting of 'service mesh' on homepage.

### PR DESCRIPTION
**Pull request by Shivam-AfA**
Signed-off-by: Shivam Sood <shivamsood634@gmail.com>

**Description**

This PR reduces the 'service mesh' keyword on the homepage.

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Shivam-AfA** [comment]
@leecalcote Please review this. I'll open an issue for the Github actions blog post once this is merged.

**Review by leecalcote — CHANGES_REQUESTED** [review]
Relocate, not just hide.

**Comment by Shivam-AfA** [comment]
> Relocate, not just hide.

Okay.

**Comment by Shivam-AfA** [comment]
@leecalcote Do you want another page for Service Mesh Peformance? Or where do you want me to relocate it to?

**Comment by leecalcote** [comment]
@Shivam-AfA you'll want to resend your fork / branch...

**Comment by leecalcote** [comment]
> 

let's try here: /features/service-mesh

**Comment by Shivam-AfA** [comment]
> @Shivam-AfA you'll want to resend your fork / branch...
> 
> Only commits for the PR's change should be included.

Yes. I'll take care of that.

**Comment by leecalcote** [comment]
> @Shivam-AfA you'll want to resend your fork / branch...
> 
> Only commits for the PR's change should be included.

@Shivam-AfA

**Comment by Shivam-AfA** [comment]
I'll close this one, the new one is here: #1017

**Pull request closed without merging**
