### PR TITLE
Added icons to headings in footer #1543

### LINKED ISSUE #1543: Adding icons to headings in footer
### Description
I would like to request the addition of icons to the headings in the footer for better visual representation and user experience

### Expected Behavior
Users should be able to easily associate each footer heading with its corresponding content through the addition of icons.

### Screenshots
Screenshot (517)

I want to work on this issue. Please assign this issue to me 

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by hemantmm**
Signed-off-by: Hemant M Mehta hemant29mehta@gmail.com

**Description**

This PR fixes #1543 

**Notes for Reviewers**

I have added icons to the footer of the meshery.io page

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
Hi @hemantmm,
Today, we've our weekly Websites meeting at 6:30 PM IST : https://meet.layer5.io/websites.
Let's get feedback on your work in today's call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Review by leecalcote — CHANGES_REQUESTED** [review]
Screenshot 2024-01-11 at 4 32 11 PM

I realize that the "blog" icon is not currently included in your PR. It's OK if that is separately addressed.

**Comment by leecalcote** [comment]
@hemantmm please sign-off on your commits.

**Comment by leecalcote** [comment]
@hemantmm are you ready for a final review?

**Comment by hemantmm** [comment]
@leecalcote can you help figure out which icon can be placed for "Cloud Native Resource"?

**Comment by hemantmm** [comment]
@leecalcote I have signed off on my commits

**Comment by vishalvivekm** [comment]
> @leecalcote I have signed off on my commits.
> 
> While rebasing "git rebase HEAD~6 --signoff" I am getting merge conflicts

@hemantmm if you've progressed on the request changes, let's get feedback. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by hemantmm** [comment]
@vishalvivekm @ritiksaxena124 can you suggest an icon for "Cloud Native Resource"?

**Comment by leecalcote** [comment]
> @vishalvivekm @ritiksaxena124 can you suggest an icon for "Cloud Native Resource"?

At the point by which they need to do this, they may as well just implement themselves.

**Comment by sudhanshutech** [comment]
@hemantmm did you get a icon for cloud native resources?

**Comment by hemantmm** [comment]
@sudhanshutech not yet was figuring it out!

**Comment by leecalcote** [comment]
Let's put a deadline on this of Monday. The stale bot is trying to close out the issue given the inactivity here.

**Comment by sudhanshutech** [comment]
@hemantmm we are not getting anywhere here, just hanging. Lets close this one, and get review on the icons first from meetings in the issue and then get them fix. Also read doc for signing off the commits

**Pull request closed without merging**
