### PR TITLE
Fixed the sass-embedded bundle error

### PR DESCRIPTION
**Pull request by Savio629**
**Description**
Fixed the sass-embedded bundle error while running `bundle install`

Slack discussion: https://layer5io.slack.com/archives/C015QJKUMPU/p1690727893886089

Error Message: 
/workspaces/meshery.io (master) $ bundle install
Fetching gem metadata from https://rubygems.org/...........
Your bundle is locked to sass-embedded (1.57.1) from rubygems repository https://rubygems.org/ or installed locally, but that version can no longer be found in
that source. That means the author of sass-embedded (1.57.1) has removed it. You'll need to update your bundle to a version other than sass-embedded (1.57.1)
that hasn't been removed in order to install.

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Savio629** [comment]
@thisiskaransgit @Chadha93

**Comment by Ghat0tkach** [comment]
Hii @Savio629 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by Savio629** [comment]
@Ghat0tkach I don't know if I would be able to join today's meeting. Can you bring this up in today's meeting?

**Review by thisiskaransgit — APPROVED** [review]
Thanks @Savio629 🙌🏼

**Review by Chadha93 — APPROVED** [review]

**Pull request merged**
