### PR TITLE
Migrating k8s.gcr.io to registry.k8s.io

### PR DESCRIPTION
**Pull request by RishabhKodes**
**Description**

This PR is a part of the Umbrella issue, https://github.com/kubernetes/k8s.io/issues/4780

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by RishabhKodes** [comment]
@Chadha93 this needs review. (not sure who to tag so tagging you here) PTAL

**Review by leecalcote — APPROVED** [review]
Thank you very much, @RishabhKodes 👏

**Comment by leecalcote** [comment]
@RishabhKodes will you have a look at the other Meshery repos and seek out an other areas in need of update?

**Comment by RishabhKodes** [comment]
> @RishabhKodes will you have a look at the other Meshery repos and seek out an other areas in need of update?

Yeah, I can do that but might be slow to update all the repositories.

**Pull request merged**
