### PR TITLE
Enhance the features page content

### LINKED ISSUE #1201: [Site] Enhance and update the features page
#### Current State of the Meshery.io site
The whole features page needs to be refactored in terms of UI and content. The content is outdated and needs to be updated with the latest features.

#### Desired State of the Meshery.io site
1. Refer to this feature page on layer5.io - https://layer5.io/cloud-native-management/meshery to implement the new for this site.
2. Also mention Meshery's extensibility features - Meshery Extension, Catalog, Snapshot. 

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by ankur0904**
**Description**

This PR fixes #1201

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by ankur0904** [comment]
@leecalcote Resolve the conflict and made the suggested changes.

**Comment by samyakshah3008** [comment]
@ankur0904 Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)

**Comment by sudhanshutech** [comment]
@ankur0904 lets discuss on website call adding this an agenda

**Comment by ankur0904** [comment]
@samyakshah3008  @sudhanshutech alright

**Comment by ankur0904** [comment]
@samyakshah3008  @sudhanshutech alright

**Comment by leecalcote** [comment]
@ankur0904 sign off on your commits please.

**Review by thisiskaransgit — COMMENTED** [review]
@ankur0904, are you still working on the PR, we also needed to highlight the mystery's extensibility features. as mentioned in the issue description.
> Also mention Meshery's extensibility features - Meshery Extension, Catalog, Snapshot.

Please signal if you are actively working on it or not

**Comment by ankur0904** [comment]
@thisiskaransgit I made the change in content of the page. I am currently learning GO for the backend contribution. No I am not currently working on this issue.

**Comment by thisiskaransgit** [comment]
Since the contributor is not actively working on the issue, closing this PR

**Pull request closed without merging**
