### PR TITLE
revert-breaking-changes

### PR DESCRIPTION
**Pull request by vishalvivekm**
**Description**

Meshery.io/catalog is crashing in iOS safari and the first PR that seems to be having this turns out to be : #1186 
This PR reverts changes done in 1186 to no avail.

screencast from BroswerStack iphone 12 pro: 

https://github.com/meshery/meshery.io/assets/110674407/fd807e02-5456-4004-b9c9-2f53f59b5741

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
https://github.com/meshery/meshery.io/issues/1509

**Comment by iArchitSharma** [comment]
@vishalvivekm its still breaking

**Comment by iArchitSharma** [comment]
Also, this is how it looks in IOS device before this PR i.e #1185 was merged
[A372128D-454E-4747-9E1C-C455DD83AEC8.pdf](https://github.com/meshery/meshery.io/files/13596985/A372128D-454E-4747-9E1C-C455DD83AEC8.pdf)

**Comment by vishalvivekm** [comment]
> Also, this is how it looks in IOS device before this PR i.e #1185 was merged [A372128D-454E-4747-9E1C-C455DD83AEC8.pdf](https://github.com/meshery/meshery.io/files/13596985/A372128D-454E-4747-9E1C-C455DD83AEC8.pdf)

Thanks for confirming @GaganpreetKaurKalsi @iArchitSharma, we now know that we hafta start with the https://github.com/meshery/meshery.io/pull/1186 and that it was indeed the first pr with crashing catalog page.

**Comment by vishalvivekm** [comment]
> Is this PR needed any longer?

It's not. Closing.

**Pull request closed without merging**
