### PR TITLE
fix: add navbar for mobile

### PR DESCRIPTION
**Pull request by Udit-takkar**
Signed-off-by: Udit Takkar <udit.07814802719@cse.mait.ac.in>

**Description**

This PR fixes https://github.com/meshery/meshery.io/issues/969

Screenshot 2023-01-14 at 9 03 53 PM

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by gyancodes — DISMISSED** [review]
Now it all looks good.

**Review by GaganpreetKaurKalsi — COMMENTED** [review]
That looks really nice now. Although there are a few issues. 
The navbar doesn't have a `max-height`. Adding one would help. Also the navbar can have some box-shadow to stand apart. Below are some style suggestions.

image

<br><br>

Also we need to adjust the styles for dark theme as well. Currently it looks like this 
image

**Comment by Udit-takkar** [comment]
@GaganpreetKaurKalsi thanks for the review and suggestion. have made the changes now

**Review by GaganpreetKaurKalsi — APPROVED** [review]
Looks good now 👍 💯

**Review by eeshaanSA — APPROVED** [review]
Looks good, @Udit-takkar :rocket:

**Comment by leecalcote** [comment]
Good!

**Pull request merged**
