### PR TITLE
feat: add search feature to catalog

### LINKED ISSUE #1488: [FEAT] : Search feature for the catalog page
### Current Behavior

In the catalog section of meshery.io [meshery.io/catalog](https://meshery.io/catalog) we do not have search feature for the cards.
### Desired Behavior

We can introduce a searching feature for the catalog page
### Screenshots / Mockups

For reference : [here](https://meshery.layer5.io/catalog)

Comment reference:
@Lucif3r-in do we have an open issue on search for the catalog? If not, do you mind opening one?

We can use https://lunrjs.com or similar.

_Originally posted by @leecalcote in https://github.com/meshery/meshery.io/issues/1481#issuecomment-1789286810_
---
<h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Lucif3r-in**
**Description**

This PR fixes #1488 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Lucif3r-in** [comment]
@abhijeetgauravm When I search something I am getting correct functionality but the catalog container is somehow shrinking according to width of card. Any suggestions?

**Review by abhijeetgauravm — COMMENTED** [review]
Yeah @Lucif3r-in the shrinking nature of search bar doesn't looks good!

**Comment by iArchitSharma** [comment]
@Lucif3r-in some test is failing?

**Comment by Lucif3r-in** [comment]
> Yeah @Lucif3r-in the shrinking nature of search bar doesn't looks good!

Yes, I was asking if you have any suggestions how to resolve it.

**Comment by Lucif3r-in** [comment]
> @Lucif3r-in some test is failing?

I checked the logs but this seems something new to me

**Comment by abhijeetgauravm** [comment]
Hey @Lucif3r-in Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by sudhanshutech** [comment]
@ritiksaxena124 can you suggest some good color that would looks good with dark and light mode

**Comment by abhijeetgauravm** [comment]
Hey @Lucif3r-in Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by abhijeetgauravm** [comment]
Hey @Lucif3r-in Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by leecalcote** [comment]
@Lucif3r-in has this ever been presented per @abhijeetgauravm's requests?

**Comment by abhijeetgauravm** [comment]
Hey @Lucif3r-in  Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by Lucif3r-in** [comment]
Sorry @abhijeetgauravm I couldn't attend today's meet due to my end semester examinations. Hope you understand. Meanwhile your suggestion regarding where to look into for the issue I am facing will be helpful.

**Review by iArchitSharma — APPROVED** [review]
@Lucif3r-in Great work, Thank you

**Pull request merged**
