### PR TITLE
Issue #939 unwanted white background in bee icon

### PR DESCRIPTION
**Pull request by Musab1258**
**Description**

This pr removes the white background that appears with the ebpf logo in the catalog page of the meshery.io website. 

This PR fixes #

fixes issue #939 

**Before**

issue-#939-before

**After**

issue-#939-after

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by UtkarshMishra12** [comment]
@Musab1258 DCO Failing!
Please follow the steps mentioned here [Link](https://github.com/meshery/meshery.io/pull/942/checks?check_run_id=10228871357)

or 

To add your Signed-off-by line to every commit in this branch:

Ensure you have a local copy of your branch by [checking out the pull request locally via the command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: **git rebase HEAD~6 --signoff**
Force push your changes to overwrite the branch: **git push --force-with-lease origin Issue-#939-unwanted-white-background-in-bee-icon**

**Comment by Musab1258** [comment]
Hi @UtkarshMishra12 , the DCO check has passed.

**Comment by Musab1258** [comment]
@leecalcote, is this okay or I still need to make some changes.

**Review by UtkarshMishra12 — CHANGES_REQUESTED** [review]
@Musab1258 Please delete the old SVG file (ebpf-logo.svg) .

**Comment by UtkarshMishra12** [comment]
@leecalcote What about those mixed commits? I think it is not correct. Your thoughts?

**Comment by leecalcote** [comment]
> @leecalcote What about those mixed commits? I think it is not correct. Your thoughts?

You’re right. It’s not OK. @Musab1258 fork is out of sync. This is true of his other PR as well. There are resync instructions in Contributing.MD.

**Comment by Musab1258** [comment]
Ok, I will check the contributing.md.

**Comment by UtkarshMishra12** [comment]
@Musab1258 Please update

**Review by leecalcote — CHANGES_REQUESTED** [review]
@Musab1258, thank you. We do want to stay with SVG as the file format, avoiding rasterized formats like PNG. Will you refactor using the existing SVG, updating it as needed?

**Pull request closed without merging**
