### PR TITLE
clickable filters and patterns icons

### LINKED ISSUE #1321: Filters and Patterns should be Clickable
#### Current State of the Meshery.io site

Currently the patters and filters image in the meshery.io/catalog doesnt perform anything .
#### Desired State of the Meshery.io site
These should be clickable and the action should lead to sorting the filters and patterns respectively

Change the cursor to point whenever we hover filters or patterns
image

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by ShivangRawat30**
**Description**

This PR fixes #1321 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Ghat0tkach — CHANGES_REQUESTED** [review]
image
uh-huh @ShivangRawat30

**Comment by vishalvivekm** [comment]
@ShivangRawat30 Let's discuss it on the websites call on Monday. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by leecalcote** [comment]
@ShivangRawat30 will you update the PR title to be descriptive of the change?

**Comment by ShivangRawat30** [comment]
@leecalcote @Ghat0tkach please review my PR.

**Comment by ShivangRawat30** [comment]
@Ghat0tkach This situation poses a challenge because all the other classes are same, and we need to identify a distinguishing characteristic for the specific division.

**Comment by abhijeetgauravm** [comment]
Hey @ShivangRawat30 Let's discuss this on website call today at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima)

**Comment by abhijeetgauravm** [comment]
Hey @ShivangRawat30  Let's discuss this on website call tomorrow at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Review by sudhanshutech — APPROVED** [review]

**Pull request merged**
