### PR TITLE
change z-index for header

### LINKED ISSUE #1662: [Catalog] Improper z-index for importing catalog item guide modal
### Description

The modal opened when clicking **import any catalog item** has improper z-index property. Its z-index is lower than that of header component.

### Expected Behavior

The modal should be on top (max z-index) like the design pattern card modals.

### Screenshots

| Desktop | Mobile |
|---|---|
|image | image|

### Enviroment:
 - OS: Linux, Android
 - Browser: Chrome
 - Version: Linux 6.6.9-arch1-1 x86_64, Android 10
 - Device: Desktop, Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by SamIsTheFBI**
**Description**

This PR fixes #1662 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Muhammed-Moinuddin** [comment]
Kindly sign your pull request by adding [X] in the checkbox. Also simply just follow these steps to resolve DCO issue: https://github.com/meshery/meshery.io/pull/1671/checks?check_run_id=23141035753

**Comment by leecalcote** [comment]
Thanks for this PR, @SamIsTheFBI!

**Comment by vishalvivekm** [comment]
@SamIsTheFBI 

Let's discuss this on websites call. Add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would :)

**Comment by SamIsTheFBI** [comment]
Yes, surely.

**Comment by sudhanshutech** [comment]
@vishalvivekm @iArchitSharma are we good to go here?

**Pull request merged**
