### PR TITLE
#1505-Thumbnail-clickable

### LINKED ISSUE #1505: [Catalog] Make thumbnail clickable; display full-size image
:help-wanted: on <http://meshery.io/catalog|meshery.io/catalog> -

[Slack Message](https://layer5io.slack.com/archives/C015QJKUMPU/p1701278812084059)

### PR DESCRIPTION
**Pull request by Raj100679**
**Description**

This PR fixes #1505 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
> @leecalcote Done the required changes

Other contributors and maintainers can review.

**Comment by horizenight** [comment]
@Savio629 @leecalcote reviewed and good to go from my side : )

**Review by leecalcote — CHANGES_REQUESTED** [review]
Please only include changes that are material to the issue. The majority of the changes here are non-material to the issue at-hand, making review of this PR more burdensome than it needs to be and risky.

**Comment by Raj100679** [comment]
I guess formatting code have done that, I will make a clean commit in some time, Thanks

**Pull request closed without merging**
