### PR TITLE
[FIX] Changed Name Google Summer of Docs to Google Season of Docs

### LINKED ISSUE #820: Fix program name on meshery.io/programs page
#### Current State of the Meshery.io site
image

#### Desired State of the Meshery.io site
image

Replace the heading "Google Summer of Docs" with "Google Season of Docs".

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Himanshu664**
Signed-off-by: Himanshu Malviya <gs2012023@sgsitsindore.in>

**Description**
Changed Name Google Summer of Docs to Google Season of Docs

This PR fixes #820 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Himanshu664** [comment]
@vedant-kakde Please Review

**Review by vedant-kakde — APPROVED** [review]

**Comment by vedant-kakde** [comment]
LGTM 👍🏻
Thanks @Himanshu664 !

**Review by Chadha93 — APPROVED** [review]
LGTM, Thank you @Himanshu664 and @vedant-kakde

**Comment by leecalcote** [comment]
Whee! 🎈 Congratulations, @Himanshu664

**Pull request merged**
