### PR TITLE
Enhanced Newsletter

### LINKED ISSUE #691: [UI] Enhancing the Newsletter
#### Current Behavior

The newsletter has no color grading at the moment and looks odd.

#### Desired Behavior

It should be more distinct and catchy so that a user would be able to sign-up easily. 

#### Implementation

I would like to contribute to UI of this newsletter component as an OpenForce22 participant. 

# Mockups
## Before
old
## After
newsletter

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Ardent10**
Signed-off-by: Zakariya khan <zak786khan@gmail.com>

**Description**

This PR fixes  #691 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 
In this PR I fixed two issues.

Issue(1) : Compatibility issue with running command make site that executes two commands in present makefile. 
Fix: Look at my Gemfile it need 3 dependencies to be installed separately(At least that is what I did). These fixes work for windows(NO WSL). They are taken from stackoverflow and official jekyll discussion forums. 
Note:  The updated dependencies in the gemfile works in windows and it worked for me.  

issue(2): Enhancing the Newsletter 

Here is the implementation as @leecalcote  needed. 

image

### CODE REVIEW

**Review by Abhijay007 — CHANGES_REQUESTED** [review]
@Ardent10 there are some responsiveness issues in tablet view that needs to be addressed 

image

image

**Comment by Ardent10** [comment]
> @Ardent10 there are some responsiveness issues in tablet view that needs to be addressed
> 
> image
> 
> image

Sure.

**Comment by Ardent10** [comment]
It is updated now

**Comment by leecalcote** [comment]
The latest changes look good in my iPhone.

**Review by leecalcote — COMMENTED** [review]
What is “.Jekyll-metadata” for? Can this be removed?

**Comment by Ardent10** [comment]
> The latest changes look good in my iPhone.

Glad to hear this. 😀

**Comment by debo19** [comment]
@Ardent10 lets discuss your updates on the websites call today.

**Review by YashKamboj — CHANGES_REQUESTED** [review]
@Ardent10 Great Work!!! . Just Need some padding in the dedicated page for the mailing list
Screenshot (30)
.

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
> @Ardent10 Great Work!!! . Just Need some padding in the dedicated page for the mailing list
> Screenshot (30)
> .

This item is fixed, but we still have a couple responsive issues.

**Comment by leecalcote** [comment]
Let's merge and allow other active contributors to pick those issues up.

**Comment by Ardent10** [comment]
Thankyou @leecalcote for making my PR a valuable one.
As I have understood how the project works I would like to work more and be a part of this community.

**Comment by leecalcote** [comment]
@Ardent10, you're welcome. Sure, that'd be great. Many resources to get you going: https://layer5.io/community/newcomers

**Pull request merged**
