### PR TITLE
Fixed Unresponsive code snippets on getting started page

### LINKED ISSUE #1025: Cli command not responsive
### Expected Behavior
terminal should expand to show commands or commands should shrink to be more visible. 

### Screenshots
A573961B-DF6B-4AA3-91F1-36F2B56AF4B8

### Enviroment:
 - OS: iPhone 
 - Browser: Safari
 - Version: 
 - Device: Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Avi-88**
All Code snippets on  getting started page are now responsive and the styling for the snippet component has been updated for a better look and feel

This PR fixes #1025 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by chinu-anand — CHANGES_REQUESTED** [review]
When shrinking the font changes to small and strains the eyes. Instead of making the code snippet responsive make it scrollable if the size overflows, and fix the text size to be more readable.

**Comment by Avi-88** [comment]
> When shrinking the font changes to small and strains the eyes. Instead of making the code snippet responsive make it scrollable if the size overflows, and fix the text size to be more readable.

Sorry for the delayed response @chinu-anand , thanks for the feedback. I've made the necessary changes , do check them and let me know if any further change is required, thanks

**Review by chinu-anand — CHANGES_REQUESTED** [review]
image

It's still not as expected, from the view of a mobile user it's a four-line code but in reality, it's a two-line code, you should make it more of a like this, control overflow and make it scrollable -

image

**Comment by Chadha93** [comment]
@Avi-88 Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by Avi-88** [comment]
> @Avi-88 Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

Sure , I'll add it for tomorrows call.

**Comment by leecalcote** [comment]
Nice!

**Comment by leecalcote** [comment]
Thank you, gents.

**Pull request merged**
