### PR TITLE
update meshery homepage: removed extra whitespace from the callout card

### LINKED ISSUE #635: fix size of call-outs
**Description**
callouts

**Expected Behavior**
Remove whitespace on the bottom of resource cards on [meshery.io](https://meshery.io/)

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by shubham-tyagi**
Signed-off-by: shubham-tyagi <raj.tyagi2000@gmail.com>

**Description**

This PR fixes #635

**Notes for Reviewers**
Please point out if I missed something or if anything else is needed to be done.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
@shubham-tyagi the sass file you made changes to is for the service-mesh-patterns callout, I think the extra white space is appearing due to the same class names, could you please change the class name in the callout and in its respective sass file. I think it's callout-cards.scss

**Comment by shubham-tyagi** [comment]
Thanks @warunicorn19 , actually the class in callout-card.scss was inheriting it's height from the class in pattern.scss so initially I changed pattern.scss .

**Review by debo19 — APPROVED** [review]
LGTM 🎉 Thanks @shubham-tyagi

**Comment by warunicorn19** [comment]
Thank you @shubham-tyagi

**Pull request merged**
