### PR TITLE
Testing blog page

### LINKED ISSUE #1533: Any blog isn't visible on the blog page of the site
### Description

Any blog isn't visible on the blog [page](https://meshery.io/blog) of the [site](https://meshery.io/)
image

### Expected Behavior

All the blogs should be visible on the blog [page](https://meshery.io/blog) of the [site](https://meshery.io/).
### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox Edge
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Savio629**
**Description**

This PR fixes #1533 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Lucif3r-in** [comment]
@Savio629 Sadly we cannot test this through netlify deploy😔

**Comment by Savio629** [comment]
@Lucif3r-in Sure?
This is my deploy: https://deploy-preview-1540--mesheryio-preview.netlify.app/blog/

This is a previous deploy of #1538: https://deploy-preview-1538--mesheryio-preview.netlify.app/blog

**Comment by Savio629** [comment]
Yup I read about it, The issue is with paginator(jekyll-paginate-v2) and gh pages compatibility.
Check this out: https://talk.jekyllrb.com/t/paginate-not-showing-page-2/2122/6

**Comment by Savio629** [comment]
I feel adding paginate_path instead of permalink should do the trick.
More about it: https://talk.jekyllrb.com/t/paginate-not-showing-page-2/2122/6
@Lucif3r-in @leecalcote

**Comment by leecalcote** [comment]
Please keep experimenting. We can merge even if we're not sure if it'll work, because 1) it's currently broken and 2) you can't tell unless you deploy into GH prod...

**Comment by leecalcote** [comment]
> @Savio629 You had removed the paginator which was causing this bug to happen, so it worked.

The issue with this being that there's no pagination, then, which is fine so long as we write our own.

Writing our own will take 20 minutes, so... do that next, if this doesn't work.

**Pull request merged**
