### PR TITLE
Text overlapping solved on page : /catalog

### LINKED ISSUE #876: Text is overlapping with the Debugging the Data Plane box from  771px to 856px on page: /catalog
#### Description

Text is overlapping with the (Debugging the Data Plane) box from  771px to 856px on page: /catalog
Issue

#### Expected Behavior

After

#### Enviroment:
 - OS: Windows
 - Browser: Chrome 
 - Version: 
 - Device: Desktop

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by UtkarshMishra12**
**Description**

This PR fixes #876 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by UtkarshMishra12** [comment]
@Harshit-Dandriyal I have made the necessary changes, you can check it and let me know about it.😊

**Comment by UtkarshMishra12** [comment]
@Rohith-Raju Sure, I'll update it now.

**Comment by UtkarshMishra12** [comment]
@Rohith-Raju You can check it now and let me know about it.😊

**Review by Harshit-Dandriyal — DISMISSED** [review]

**Review by adithyaakrishna — DISMISSED** [review]
LGTM, thanks @UtkarshMishra12 :)

**Review by Rohith-Raju — DISMISSED** [review]

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks, @UtkarshMishra12. Feedback:

1. All labels should be dealt with uniformly. NSM should not be a special case.
2. Please use `text-overflow: ellipsis;` to cut off the overflowing text rather than allowing a long name to disrupt the display of the selection UI. Use `alt` attribute (or similar) to show a tooltip with the item's full name on hover.

**Comment by leecalcote** [comment]
@UtkarshMishra12 feedback above.

**Comment by leecalcote** [comment]
What method? white-space: normal? No, that doesn't help implement the feedback that I've given.

**Comment by leecalcote** [comment]
@Krishna2323 in light of sweeping changes across the site, is this PR still valid (necessary)?

**Comment by leecalcote** [comment]
> @Krishna2323 in light of sweeping changes across the site, is this PR still valid (necessary)?

@Krishna2323?

**Comment by leecalcote** [comment]
@UtkarshMishra12 what do you want to do here? // @GaganpreetKaurKalsi

**Review by GaganpreetKaurKalsi — COMMENTED** [review]
These styles would fix the issue 
image

**Pull request closed without merging**
