### PR TITLE
New PR for Unused CSS

### LINKED ISSUE #896: Website: Consolidate duplicative and unused CSS
**Current Behavior**
This site has much unused CSS and some overlapping CSS.

**Desired Behavior**
Use of SASS is preferred. Ideally, most of the CSS (by line count) is removed from the site. This can be done piecemeal over multiple PRs.

---
<h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by THEBOSS0369**
This PR fixes #896 
This is the new PR for this PR https://github.com/meshery/meshery.io/pull/1880

**Description**
 have added a script by which, now user don't have to change the file name in any file he/she just have to update the file name in the terminal. 

I have added an **unused component name-btn** so after running this in the terminal, it will automatically delete all the unnecessary  css component that is not in used. If you want to check any other file just change **blog.scss**  to file you wanted to check  **anything-you-want.scss** and it will done its work.

Run this in terminal
`node check-unused-css.js blog.scss`

This will be prompted in terminal after execution of the script

`Success: The file 'blog.scss' was processed successfully.
The output has been saved to './output/blog.scss'
NOTE: ALL THE UNUSED CSS IS REMOVED FROM THE UPDATED FILE` 

Before running the script, i added an **name-btn** unused component in website
before testing

It is removed after execution of code
after testing

Note : The updated file will be saved in the output directory.

**Notes for Reviewers**
I found that many of the unused css styles are the ones that are used by pressing or hovering component like a button it has many styles like hovering OR on pressing different styles is used. so its style will be unused until the component is not in used.

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ashparshp** [comment]
@THEBOSS0369, Thank you for your contribution!
Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please consider adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk) || [meeting link](https://meet.layer5.io/websites).

**Comment by THEBOSS0369** [comment]
> @THEBOSS0369, Thank you for your contribution!
> Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).
> 
> Please consider adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk) || [meeting link](https://meet.layer5.io/websites).

Hey @Ashparshp ! This PR has already been discussed. Sudhanhu asked me to either revert back the unnecessary changes from the previous PR and i wasn't able to revert back so i created a new One! Also the Previous Pr for this has been asked to reviewed from reviewers.

**Comment by vishalvivekm** [comment]
@THEBOSS0369 extraneous commits

**Comment by THEBOSS0369** [comment]
@sudhanshutech @vishalvivekm ! Can you take a look?

**Pull request closed without merging**
