### PR TITLE
Added support for dark mode in twitter timeline widget in Footer Element closes #1242

### LINKED ISSUE #1242: No dark mode for twitter Widget
#### Current Behavior
There is no dark mode for twitter timeline in footer at meshery.io

#### Desired Behavior
The twitter timeline should also change with dark mode of site

#### Purposed Solution
The theme of widget can be changed according to the guidelines given here:
https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/guides/cms-best-practices 

#### Screenshots/Logs
image

### PR DESCRIPTION
**Pull request by ranjanmangla1**
**Description**

This PR fixes #1242 

**Notes for Reviewers**
I have added dark mode functionality for twitter timeline widget for dark mode.

Implementation details: 
first, i had tried using changing the data-theme attribute of the <a> tag of twitter widget, it was working but it required reloading the page to see the changes, so it was not feasible at all.
Now, what I have done is for dark mode and light mode, whenever toggle happens, it creates a new widget and then appends to the page, so no refresh is required.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### Screenshots: 
- dark mode
image

- light mode
image

### CODE REVIEW

**Comment by Savio629** [comment]
@thisiskaransgit @vishalvivekm Even tho meshery has some tweets on it's profile it's displaying "Nothing to see here - yet" 🤔

Also @ranjanmangla1 there's a slight delay while switching to light/dark modes

**Comment by ranjanmangla1** [comment]
> @thisiskaransgit @vishalvivekm Even tho meshery has some tweets on it's profile it's displaying "Nothing to see here - yet" thinking
> nothing to see here yet is happening on meshery.io too, @Savio629 

> Also @ranjanmangla1 there's a slight delay while switching to light/dark modes
yeah, I know, that is because whenever a toggle happens, a new widget is created and then it is appended to the page. This is the only solution that is working, other wise, the page has to be reloaded to see the changes. I have added implementation details in the pr description.
Out of the 3 possible solutions, I figured out, this is the only solution that is working well

**Comment by ranjanmangla1** [comment]
hey @Savio629, so what changes I have to make in this pr to be merged?

**Comment by samyakshah3008** [comment]
@ranjanmangla1  Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)

**Comment by ranjanmangla1** [comment]
@samyakshah3008 , hey Samyak, can you review this pr, in past two website meetings this has been an agenda but could not be discussed on both occassions due to lack of time?

**Comment by samyakshah3008** [comment]
Sure man, let me look into it today.

**Comment by Chadha93** [comment]
@thisiskaransgit, I'm removing `prhold` label, as twittter issue is resolved now

**Comment by Chadha93** [comment]
@ranjanmangla1 Merge conflicts to resolve...

**Comment by thisiskaransgit** [comment]
Thanks for the PR, but since the widget is not working, due to twitter's new open-access policy, we'll be closing this issue. Thank you for your efforts though.

**Pull request closed without merging**
