### PR TITLE
Gem: Updated ruby version to 2.7.5

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**
The latest version of ruby-3.* is not yet available in rvm, so updating it to the next latest available version.
Other gems are taken care of by dependabot. Therefore, no need for manual updates.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
> build is failing because of the mismatch of ruby versions. @Nikhil-Ladha it's working fine for you locally yes?

Works fine for me locally.
Trying to understand the issue in the case of netlify,

**Comment by leecalcote** [comment]
These netlify failures are occurring on other PRs, too.

**Comment by Nikhil-Ladha** [comment]
So, even after changing the version to 2.7.0 the build is failing :/

**Comment by Nikhil-Ladha** [comment]
Ok, found the issue.
Comments are not allowed in a JSON file, and the wasm.json file was having one which led to the failure in parsing.

**Comment by Nikhil-Ladha** [comment]
apparently, the build was failing from 26th Feb 👀

**Comment by Nikhil-Ladha** [comment]
Phew! 😌

**Comment by warunicorn19** [comment]
Huh, I dont remember me doing that 😅.

**Review by warunicorn19 — APPROVED** [review]

**Comment by warunicorn19** [comment]
Thank you @Nikhil-Ladha , merge at -will

**Comment by Nikhil-Ladha** [comment]
> Huh, I dont remember me doing that sweat_smile.

Now let's not blame the old man anymore. We should understand the pain and move ahead 😆

**Pull request merged**
