### PR TITLE
Used required attribute in the input fields of Newsletter form

### LINKED ISSUE #653: Need validation for the Newsletter form
**Description**
A brief description of the issue.
There is no validation of the input fields in the newsletter form .
https://meshery.io/
**Expected Behavior**
A brief description of what you expected to happen.
should not proceed without any input

**Screenshots**
Add screenshots, if applicable, to help explain your problem.

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by MukulKolpe**
**Description**

This PR fixes #653

**Notes for Reviewers**
Used required attribute in the input fields of Newsletter form so that form should not proceed without all required inputs.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by YashKamboj** [comment]
@MukulKolpe not working

**Comment by YashKamboj** [comment]
@MukulKolpe  you can check https://github.com/layer5io/getnighthawk/pull/234 for reference

**Comment by YashKamboj** [comment]
@MukulKolpe it is still redirecting.

**Comment by MukulKolpe** [comment]
yes...I'm trying to figure out the reason. Do you see any obvious issues in the code?

**Comment by YashKamboj** [comment]
@MukulKolpe It is working but the css is changed

**Comment by MukulKolpe** [comment]
@YashKamboj can you please review this...

**Review by YashKamboj — APPROVED** [review]

**Review by warunicorn19 — APPROVED** [review]
Looking good, Thank you @MukulKolpe

**Comment by MukulKolpe** [comment]
Thank you @YashKamboj and @warunicorn19 ⚡

**Pull request merged**
