### PR TITLE
Updated  CSS on Page : meshery.io/blog

### PR DESCRIPTION
**Pull request by UtkarshMishra12**
Signed-off-by: Utkarsh Mishra <nasautkarsh@gmail.com>

**Description**
Updated  CSS on Page: meshery.io/blog

This PR fixes #

**Notes for Reviewers**
Before:
image

Now:
image

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by GaganpreetKaurKalsi — COMMENTED** [review]
How about we change the image as well with the one we use on layer5, @leecalcote.

image

**Comment by eeshaanSA** [comment]
@GaganpreetKaurKalsi, shouldn't the image shrink for the mobile view? Looks way too big. 
image

**Comment by GaganpreetKaurKalsi** [comment]
> @GaganpreetKaurKalsi, shouldn't the image shrink for the mobile view? Looks way too big. image

Correct, need to size the image according to mobile as well.

**Comment by eeshaanSA** [comment]
@UtkarshMishra12

**Comment by leecalcote** [comment]
Great feedback.

**Comment by GaganpreetKaurKalsi** [comment]
Any updates @UtkarshMishra12?

**Comment by leecalcote** [comment]
@UtkarshMishra12 I've put this item as a point of discussion for tomorrow's meeting.

**Comment by UtkarshMishra12** [comment]
Now:  @leecalcote 

https://user-images.githubusercontent.com/67385503/210272444-aa59e38a-0d9c-416e-95f0-b2fb275954a1.mp4

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
