### PR TITLE
Section 5 of Community page

### LINKED ISSUE #1271: New page design implementation for Contributors page
#### Current State of the Meshery.io site

Currently the page https://meshery.io/community/ is empty

#### Desired State of the Meshery.io site

Need to implement the mockup for this page from [Figma design](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=16435%3A39494&mode=design&t=6qls5jOGn5gJKKgm-1)
Contributors can pick separate section to implement the page fast

- [ ] Section-1: Banner section

image

- [ ] Section- 2: Resources section

image

- [ ] Section-3: Handbook section

image

- [ ] Section-4: Discuss forum section

image

- [ ] Section-5: Meshmate section

image

- [ ] Section-6: Calendar section"

image

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by lanzkrish**
**Description**
Fixes #1271

Added Section 5 of the Community page

**Notes for Reviewers**

link to the preview:
https://master--peppy-otter-ff5ecf.netlify.app/community/
image

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@lanzkrish Let's discuss it on the websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

**Review by sudhanshutech — APPROVED** [review]
There still some styling needed but can be raised another issue for that improvement, for now we can merge this

**Review by Rexford74 — APPROVED** [review]

**Review by thisiskaransgit — APPROVED** [review]
We will be soon moving ahead with merging each section. Looks good to merge, thank you for your contribution :tada:

**Comment by Chadha93** [comment]
merge conflicts... @lanzkrish

**Comment by thisiskaransgit** [comment]
Big thanks for this PR @lanzkrish! Your commitment to our project is remarkable, and we're grateful for all your efforts.
Just a quick update: Another pull request with similar changes has been merged, so we'll be closing yours. Please know that it doesn't undermine the significance of what you've done.
We admire your involvement in our community. Keep shining bright with more incredible contributions down the line!

**Pull request closed without merging**
