### PR TITLE
Add Metabit Logo  w/signoff

### LINKED ISSUE #1094: Add Metabit Trading logo to adopters list
### Current Behavior
Metabit Trading is Meshery's latest adopter (see https://github.com/meshery/meshery/pull/7433)

### Desired Behavior
Metabit Trading logo should be displayed alongside others.

---
<h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by therajatrai**
**Description**

This PR fixes #1094 

**Notes for Reviewers**

*Screenshot of the Metabit Trading logo to adopters list*

image

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Much appreciated, @therajatrai. The image quality here is horrific, though. We'll need a higher quality copy of the logo.

**Comment by therajatrai** [comment]
@leecalcote, I have asked Gen Yang for help on the logo. Will commit.

**Comment by therajatrai** [comment]
@leecalcote I have updated the logo,

Here is the preview : 

image

**Review by chinu-anand — APPROVED** [review]
Nice work @therajatrai. Thanks

**Comment by therajatrai** [comment]
@chinu-anand They have hover effects, they get colored on hover.

**Review by vishalvivekm — APPROVED** [review]
LGTM. Thanks @therajatrai

**Comment by leecalcote** [comment]
> @leecalcote, is this dull look of logos by default intentional? because at a glance it gave me feedback of something like "a disabled button" or something like "they are previous adopters but not now". In my opinion, it would be better to make those logos look colourful if there were no specific reasons to do that.

Good question. Many other websites will make the collection of logos chromatic. The design here is in reflection of that.

**Comment by leecalcote** [comment]
Yay, @therajatrai! 🎈

**Pull request merged**
