### PR TITLE
[FIX/UI] Twitter Feed Overflowing Fixed

### LINKED ISSUE #824: Scrolling Option inside the twitter column
image

This "Tweets from mesheryio" box should occupy just a certain height and width, and there should be a scrolling option right inside the box.

### PR DESCRIPTION
**Pull request by Prathamesh-Shanbhag**
Signed-off-by: Prathamesh-Shanbhag <prathameshshanbhag074@gmail.com>

**Description**

This PR fixes #824 & Solves issue for overflowing twitter feed

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by adityyaa-10** [comment]
@Prathamesh-Shanbhag  adding some screenshots would be great I feel.

**Comment by Prathamesh-Shanbhag** [comment]
Sure @adityyaa-10 Thanks for pointing that out!

- Twitter Feed is now inside a bounded container with round edges.
image

**Comment by vedant-kakde** [comment]
LGTM Good job! 👍🏻
Thanks, @Prathamesh-Shanbhag !

**Review by vedant-kakde — APPROVED** [review]

**Comment by Prathamesh-Shanbhag** [comment]
- And this is the behavior of the container on smaller devices.
WhatsApp Image 2022-08-31 at 10 50 02 PM

**Comment by vedant-kakde** [comment]
@leecalcote please approve the changes

**Review by adityyaa-10 — APPROVED** [review]

**Comment by legendarykamal** [comment]
Sorry @Prathamesh-Shanbhag but did you check this PR initially https://github.com/meshery/meshery.io/pull/818 
It was opened 5 days ago :sweat_smile:

**Review by warunicorn19 — APPROVED** [review]
LGTM. Thanks @Prathamesh-Shanbhag

**Pull request merged**
