### PR TITLE
[FIX Catalog]: search bar collapsing on not-found

### LINKED ISSUE #1512: [BUG]: The catalog search feature is misbehaving
### Description
The catalog search goes into an irrecoverable state when none of the search matches.

### Expected Behavior
Show that there is nothing and add recovery

### Screenshots
image

### Enviroment:
 - OS: Linux
 - Browser: Chrome Firefox
 - Version: latest
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Shurtu-gal**
**Description**
- Fixed the search bar collapsing on not-found
- Added a "No results found"

This PR fixes #1512 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Lucif3r-in** [comment]
Hey @Shurtu-gal , nice work there.
The code has been updated after your PR, please pull changes and make required changes as this issue hasn't been fixed in the updated code😊

**Comment by Shurtu-gal** [comment]
Thanks for the heads up @Lucif3r-in. I have updated this.

**Comment by Lucif3r-in** [comment]
LGTM🚀

**Comment by Lucif3r-in** [comment]
@Shurtu-gal Good one. LGTM🚀

**Review by leecalcote — APPROVED** [review]
Thanks, @Shurtu-gal and @Lucif3r-in

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Yay, @Shurtu-gal! 🎈

**Pull request merged**
