### PR TITLE
Error: YAML Exception Reading #1208

### LINKED ISSUE #1208: Error: YAML Exception Reading
### Description

On running the command `make site` it shows me an error. A small update needs to both files. 
Screenshot (86)

##### [Here is the link to one of the files:](https://github.com/meshery/meshery.io/blob/master/collections/_catalog/deployment/2df29b2b-7e5e-4d8b-a5b3-3dea569f4d25.md) 
Screenshot (88)

### Expected Behavior

Don't show any errors. 

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by vaibhav-xt**
**Description**
By adding quotes it fixes this error. 
Screenshot (86)

This PR fixes #1208 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
build page failing with this error: (I dont think it is due to this PR)
```
3:23:43 PM: Your Ruby version is 2.7.5, but your Gemfile specified 3.2.2
```

**Comment by leecalcote** [comment]
@theBeginner86 these changes will be overwritten on push from the Meshery Catalog. What would you like to do here?

**Comment by theBeginner86** [comment]
> @theBeginner86 these changes will be overwritten on push from the Meshery Catalog. What would you like to do here? Form validation needed in the rjsf form for publishing… or to simply use | and put all of those variable’s values on a separate line.

The logic to handle this would directly go inside of the [Add Catalog Workflow](https://github.com/meshery/meshery.io/blob/master/.github/workflows/add-catalog.yml). So, when adding these entries we would be using `|` for potential multiline items like compatibility, pattern info, pattern caveat etc.

Thank you for pointing this out. I'll take care of this item in my open PR: https://github.com/meshery/meshery.io/pull/1259

**Comment by theBeginner86** [comment]
We can close this as this is to programmatically fixed using the workflow.
Already taken care of this in this PR https://github.com/meshery/meshery.io/pull/1259.

Thanks @vaibhav-xt for raising this PR

**Pull request closed without merging**
