### PR TITLE
Consolidated images under assets folder

### LINKED ISSUE #923: [Chore] Consolidate assets folders including js, css, images
#### Current State of the Meshery.io site
These two folders and their content:

1. https://github.com/meshery/meshery.io/blob/master/js
1. https://github.com/meshery/meshery.io/blob/master/images

#### Desired State of the Meshery.io site
Can be combined under `/assets`.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by BabyElias**
**Description**
Consolidated images under Assets folder and updated image locations throughout.
This PR fixes #923 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Chadha93** [comment]
@BabyElias  Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by BabyElias** [comment]
> @BabyElias Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

Yup, sure!

**Comment by BabyElias** [comment]
@Chadha93

**Review by Chadha93 — DISMISSED** [review]
LGTM

**Comment by BabyElias** [comment]
@Nikhil-Ladha Can you please review this PR?

**Pull request closed without merging**
