### PR TITLE
[UI] Horizontally footer content fixed vertical represented on mobile…

### LINKED ISSUE #492: [UI] Need some modifications
**Current State of the Meshery.io site**
Modification relates to `mobile view` in general:
1. [x] Needs to add Community Forum point at appropriate section [Community]
2. [ ] Alignment of `Created by LAYER5 and it's open source community` needs to set, i.e, flexible to current state - G
3. [ ] Horizontally footer content must be vertical represent - A
4. [ ] Menu issue - H

**Current State of the Meshery.io site**

 </br>
----
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

### PR DESCRIPTION
**Pull request by AKSHATNEMA**
**Description**
Fixed: [UI] Horizontally footer content fixed vertical represented on mobile…

This PR fixes #492 

**Notes for Reviewers**
Ready to merge! 🙂

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 
**Preview**
Layout5

### CODE REVIEW

**Review by Jashpatel1 — CHANGES_REQUESTED** [review]
On larger screens, the center align property is hindered. Please fix it.

After your changes:
Capture

Before
Capture1

**Comment by AKSHATNEMA** [comment]
@Jashpatel1 I have made some changes to improve the view as you said. Please clarify the one you want. 





In the second image, I have removed the dots present before them to have a more look clear. Please give your suggestions about these.

**Comment by Jashpatel1** [comment]
> @Jashpatel1 I have made some changes to improve the view as you said. Please clarify the one you want.
> 
> 
> 
> 
> 
> In the second image, I have removed the dots present before them to have a more look clear. Please give your suggestions about these.

We can go with the second one

**Review by Jashpatel1 — APPROVED** [review]
Looks good. Thanks @AKSHATNEMA

**Pull request merged**
