### PR TITLE
removed unused styles

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chatterjee <speak2adi@gmail.com>

**Description**
Will Refactor some catalog styles in this PR, switched the position of the switch and the cross. 
This PR fixes #

**Notes for Reviewers**
`DO-NOT-MERGE`

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
I’m just realizing that there is no menu/filers available in mobile view.

**Comment by warunicorn19** [comment]
Almost reduced 500 lines

**Comment by warunicorn19** [comment]
@leecalcote i made some changes here to the individual pages, added the date and made the chips clickable. Could you please take a look? Then we can merge.

**Comment by leecalcote** [comment]
Filters in mobile view is needed. That can be a different PR, if you like,
@warunicorn19

**Comment by leecalcote** [comment]
The clickable category label works in modal view ✅. It doesn’t work in grid view, would be nice to have, but isn’t urgent.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
