### PR TITLE
#1505-Clickable thumbnail

### LINKED ISSUE #1505: [Catalog] Make thumbnail clickable; display full-size image
:help-wanted: on <http://meshery.io/catalog|meshery.io/catalog> -

[Slack Message](https://layer5io.slack.com/archives/C015QJKUMPU/p1701278812084059)

### PR DESCRIPTION
**Pull request by Raj100679**
**Description**

This PR fixes #1505 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Yashsharma1911 — COMMENTED** [review]
Thankyou @Raj100679, can you confirm is this works on both places, one with catalog modal and one when you click on read more and you get redirect to a detailed page of that selected catalog, we also have catalog image over there too.

**Comment by Yashsharma1911** [comment]
Can you make the cross icon color kepple green on hover, also if you can make the background of image more darker of blurry not too much but little more it would be helpful

Screenshot 2023-12-23 at 7 47 28 AM

By kepple greeen I mean

Screenshot 2023-12-23 at 7 47 53 AM

**Comment by Yashsharma1911** [comment]
It would be helpful if you add thumbnail support here too @Raj100679 

Screenshot 2023-12-23 at 7 52 00 AM

**Comment by Yashsharma1911** [comment]
If modal is open and I click on image it opens image view however if I click outside it closes modal which kind of it should not close modal instead only close image or even if it closes modal when I open it again by clicking on catalog card it opens the image view also which it should not ideally.

You might like to use event listener or window.onclick function to track that and make display none if user clicks outside

https://github.com/meshery/meshery.io/assets/71271069/a4d81fc1-d915-4380-a1ad-14dece3fc0fa

**Comment by Raj100679** [comment]
@Yashsharma1911 Will check it and fix it, Thanks

**Comment by Yashsharma1911** [comment]
> @Yashsharma1911 Will check it and fix it, Thanks

Thankyou

**Comment by Raj100679** [comment]
@Yashsharma1911 I am trying it for long time, can you help me with this

**Comment by Yashsharma1911** [comment]
Can you specify what help you need?

**Comment by Raj100679** [comment]
@Yashsharma1911 The one where the modal image should be closed , when clicked outside of image, I tried adding eventlistener to it, we can talk about it on slack

**Comment by Yashsharma1911** [comment]
You can use window.onclick on that you can make display none of image view, does this help

**Comment by Yashsharma1911** [comment]
@Raj100679 I think we are close enough to merge this PR can you share if you need help or if you fixed above-requested changes

**Comment by Raj100679** [comment]
@Yashsharma1911 Sorry I was out for a trip , will check if i can work out this with windows.event listener, if not then I will ping you on slack

**Comment by Yashsharma1911** [comment]
> @Yashsharma1911 Sorry I was out for a trip , will check if i can work out this with windows.event listener, if not then I will ping you on slack

Thankyou

**Comment by Raj100679** [comment]
https://github.com/meshery/meshery.io/assets/85561967/a8f7ec9c-bedc-42fa-b752-8d9417e1cb33

@Yashsharma1911 , see I have changed some things , it is taking long time to reload but I guess when we will deploy it will work fine

**Pull request closed without merging**
