### PR TITLE
Add handbook section

### LINKED ISSUE #1271: New page design implementation for Contributors page
#### Current State of the Meshery.io site

Currently the page https://meshery.io/community/ is empty

#### Desired State of the Meshery.io site

Need to implement the mockup for this page from [Figma design](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=16435%3A39494&mode=design&t=6qls5jOGn5gJKKgm-1)
Contributors can pick separate section to implement the page fast

- [ ] Section-1: Banner section

image

- [ ] Section- 2: Resources section

image

- [ ] Section-3: Handbook section

image

- [ ] Section-4: Discuss forum section

image

- [ ] Section-5: Meshmate section

image

- [ ] Section-6: Calendar section"

image

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Mohith234**
**Description**

This PR fixes #1271 

**Notes for Reviewers**

- Added Section 3 of the Community page 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by sudhanshutech** [comment]
any screenshots?

**Comment by Mohith234** [comment]
Sorry, forgot to add 

image

**Comment by Mohith234** [comment]
- Made the image look 3D 
- Used the handbook logo from the PR mentioned by @Savio629. I believe that's not an issue  

### Screenshot
image

**Comment by vishalvivekm** [comment]
@Mohith234 Let's discuss it on the websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

**Comment by thisiskaransgit** [comment]
@Mohith234, update the branch, please...

**Review by Chadha93 — DISMISSED** [review]
Thank you @Mohith234

**Comment by Chadha93** [comment]
Merge conflicts.... @Mohith234

**Comment by Savio629** [comment]
// @Mohith234 
meshissue

**Comment by Mohith234** [comment]
Fixed the issue and Solved Merge conflicts
- Changed the layout type
- Changed some CSS code

**Comment by Savio629** [comment]
@Mohith234 Can you do something for this width?
ch

**Comment by Mohith234** [comment]
@Savio629 Should I make the book to display at the bottom or Should I reduce the font size and width of the book container ?

**Comment by Savio629** [comment]
Try to display the book below the text

**Comment by Mohith234** [comment]
### Screenshot for Reference 

image

// @Savio629

**Pull request closed without merging**
