### PR TITLE
fixing Overlapping filter menu with other component in mobile view

### LINKED ISSUE #1171: Overlapping filter Menu with filter Button and Design Catalog Component
### Description

Overlapping filter Menu with filter Button and Design Catalog Component . In Mobile view
https://meshery.io/catalog/deployment
### Expected Behavior

Their should be space between both the filter button and Design catalog component

### Screenshots

ISSUE
meshery_issue

Expected Outcome
meshery_solution

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Cvr421**
**Description**
fixing Overlapping filter menu with filter button and Design catalog component in mobile view
This PR fixes #1171

**Notes for Reviewers**
Issue
meshery_issue
Expected outcome
recent2

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- Yes, I signed my commits.

### CODE REVIEW

**Review by GaganpreetKaurKalsi — COMMENTED** [review]
Looks fine, though I prefer the distance between the button and the overlay is less so it looks like the overlay belongs to the button. 
How about we settle at 0.3rem, what say?

**Comment by Cvr421** [comment]
> Looks fine, though I prefer the distance between the button and the overlay is less so it looks like the overlay belongs to the button. How about we settle at 0.3rem, what say?

I think you are right @GaganpreetKaurKalsi  0.3rem looks good . it feels like overlay belongs to the button
I'll make it to 0.3 rem

**Comment by Cvr421** [comment]
Hii @GaganpreetKaurKalsi I have changed the distance to 0.3rem please review and let me know your opinion
Thank you.

**Comment by vishalvivekm** [comment]
> Hii @GaganpreetKaurKalsi I have changed the distance to 0.3rem please review and let me know your opinion Thank you.

@Cvr421 Let's discuss this on websites call, add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would :).

**Comment by Cvr421** [comment]
> > Hii @GaganpreetKaurKalsi I have changed the distance to 0.3rem please review and let me know your opinion Thank you.
> 
> @Cvr421 Let's discuss this on websites call, add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would :).

ok no problem i'll do it

**Comment by thisiskaransgit** [comment]
@Cvr421  Update the branch please, to showcase the recent changes

**Comment by Cvr421** [comment]
> @Cvr421 Update the branch please, to showcase the recent changes
ok

**Comment by Cvr421** [comment]
> @Cvr421 Update the branch please, to showcase the recent changes

@thisiskaransgit 
Hii karan anything need to change in this PR. I have updated the branch. please let me know your suggestion .

**Review by thisiskaransgit — APPROVED** [review]
Looks good to merge, thank you for your contribution :tada:

**Review by Chadha93 — APPROVED** [review]
Thank you @Cvr421, @GaganpreetKaurKalsi @thisiskaransgit

**Pull request merged**
