### PR TITLE
Text on programs pages made visible

### LINKED ISSUE #994: Text is not visible on every page of programs (i.e change its color in dark mode)
### Description

Text is not visible on every page of programs (i.e change its color in dark mode) 
[Link](https://meshery.io/programs)

### Expected Behavior

The text should be visible in dark mode.

### Screenshots

Now:
image

Desired:
image

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Adi-ty**
**Description**
This PR makes the text visible on the programs pages.

This PR fixes #994 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Adi-ty** [comment]
@UtkarshMishra12 can you please provide a review here

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks.

Let's be explicit about the color that we are choosing to use and let's ensure the both light and dark mode are considered for.

**Comment by Adi-ty** [comment]
We will need to decide which colors to switch to in dark mode as current colors are making text invisible do you have any specific colors in mind?

**Comment by Adi-ty** [comment]
Or should I try different colors?

**Pull request closed without merging**
