### PR TITLE
Website performance

### LINKED ISSUE #529: [Performance] Improve website performance
**Description**
The current website homepage is getting too long which is impacting its performance.
Possible fixes:
- Remove all instances of unnecessary commented out code in production
image
- Too many images and gifs are increasing the load time. we could use lazy loading for images. Reference: https://web.dev/browser-level-image-lazy-loading/
- Provide height and width attributes to images.
- Currently, there is a lot of empty space on the homepage. It could be redesigned to represent information in a more crisp and concise manner.
- Use of async and defer for non-critical javascript files
-  Use of advanced optimization techniques like preload, prefetch, etc. Reference: https://css-tricks.com/prefetching-preloading-prebrowsing/
- Add missing Cache Expiry headers to static assets

**Expected Behavior**
Full score in all the parameters in Lighthouse Report

**Screenshots**
image

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by Blakelist7**
**Description**
This PR adds `lazy loading` to the site and removes unnecessary commented code.

This PR fixes #529 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
Heads up: merge conflict.

**Comment by Blakelist7** [comment]
> Heads up: merge conflict.

@warunicorn19 have a look now

**Comment by leecalcote** [comment]
Thank you, @Blakelist7. Could you take a moment to expound on the mechanics of how lazy loading is being implemented?

**Comment by leecalcote** [comment]
@Blakelist7 I see now - https://www.w3schools.com/tags/att_img_loading.asp. Good deal.

**Comment by Blakelist7** [comment]
> Thank you, @Blakelist7. Could you take a moment to expound on the mechanics of how lazy loading is being implemented?

Sure, as mentioned in the issue (#529) itself I referred [web dev](https://web.dev/browser-level-image-lazy-loading/).
I also used dev tools to see if it was functioning or not, and it was : )

**Comment by Nikhil-Ladha** [comment]
Can you share the performance benefit here?

**Comment by Nikhil-Ladha** [comment]
Also, we have a merge conflict do resolve them.

**Comment by Blakelist7** [comment]
> Can you share the performance benefit here?

Performance benefit as increase in website performance or benefit of using lazy loading?

If it's the first one could you help me on how to check the performance locally or online?

**Comment by Nikhil-Ladha** [comment]
> > Can you share the performance benefit here?
> 
> Performance benefit as increase in website performance or benefit of using lazy loading?
> 
> If it's the first one could you help me on how to check/compare the performance locally or remotely?

Performance of the site can't be measured correctly because of the env difference in netlify vs our prod env. But, you could share the working of lazy loading as you found in the dev tools, compared to current site.

**Comment by Blakelist7** [comment]
https://user-images.githubusercontent.com/54525960/134056600-be593d55-ccc5-4aa4-a71c-7cc2563f0427.mp4


**Without** the use of `lazy loading`
The following recording shows that the site loads all the images and gifs instantaneously which sometimes results in loss of data as user might not visit a particular image/gif. Also, this increases the loading time of the site.

**Comment by leecalcote** [comment]
@Blakelist7 great explanation. I simply wasn't aware of this being an HTML5 (HTML native) capability. This is great.

**Comment by Blakelist7** [comment]
https://user-images.githubusercontent.com/54525960/134057987-1e645125-ed81-412b-b7a6-14b25bb6974c.mp4
When using `lazy loading` All images that are above the fold—that is, immediately viewable without scrolling—load normally. Those that are far below the device viewport are only fetched when the user scrolls near them. So, this actually saves us some data.

**Comment by Blakelist7** [comment]
> @Blakelist7 great explanation. I simply wasn't aware of this being an HTML5 (HTML native) capability. This is great.

Thanks @leecalcote but all the credit goes to @Aman-Codes 🎉

**Comment by leecalcote** [comment]
Good stuff here, @Blakelist7 🎈

**Pull request merged**
