### PR TITLE
Reduced integration cards in homepage

### LINKED ISSUE #1371: Reduce the initial number of Integrations card
### Current Behavior
Currently, the Meshery.io homepage contains a large number of initial integration cards, which can negatively impact the payload and loading time of the website. This issue aims to address the payload concern by reducing the number of initial integration cards displayed on the homepage.

### Desired Behavior
Upon visiting the Meshery.io homepage, the number of initial integration cards should be reduced (for reference visit layer5.io), resulting in a decreased payload and improved loading performance.

### Screenshots / Mockups

---
<h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Ishwar-Zatke**
**Description**
 Reduced integration cards in homepage.  
The number of integration cards is reduced to 30 in the homePage-integrations.html

\
image

\
This PR fixes 
#1371

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ghat0tkach** [comment]
@Ishwar-Zatke , Thanks for your contribution however Please ensure that you went thorough the issue comments.

We follow assignment in chronological order . Please take care of these things from near future

**Comment by Ghat0tkach** [comment]
Since this is your first Pull Request , 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by ritiksaxena124** [comment]
@Ishwar-Zatke Thank you for your contribution you did great but make sure like @Ghat0tkach said ask for an assignment, get assigned then start working on the issue.

Will you shift the "See all integrations" below the integration cards?

**Comment by Ishwar-Zatke** [comment]
@ritiksaxena124 , Instruction noted, will follow the flow from here onwards. I had also updated the changes u asked for, Can you review it?

**Comment by ritiksaxena124** [comment]
Looks good to me @Ishwar-Zatke 🙌 well done

**Review by ritiksaxena124 — APPROVED** [review]

**Review by abhijeetgauravm — APPROVED** [review]
Looks good!

**Comment by saurabh100ni** [comment]
let's discuss this item on today's website meeting,
please add this agenda in the docs if you would :): https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk

**Comment by iArchitSharma** [comment]
@Ishwar-Zatke Was this PR discussed in the website meeting?

**Comment by abhijeetgauravm** [comment]
Hey @Ishwar-Zatke Let's discuss this on website call today at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima)

**Comment by Mohith234** [comment]
@sudhanshutech Ready to merge, It's been stale for a long time.

**Comment by abhijeetgauravm** [comment]
> Looks good to me @Ishwar-Zatke 🙌 well done



> @sudhanshutech Ready to merge, It's been stale for a long time.

// @vishalvivekm @sudhanshutech

**Comment by iArchitSharma** [comment]
@abhijeetgauravm https://layer5io.slack.com/archives/C015QJKUMPU/p1697478343561099

**Comment by iArchitSharma** [comment]
This issue has been solved in PR [#1467](https://github.com/meshery/meshery.io/pull/1476)

**Pull request closed without merging**
