### PR TITLE
Fixed responsive issue on catalog page

### LINKED ISSUE #1392: Import any catalog item responsive issue
### Description
Import any catalog item window is not properly responsive for a mobile device. 

WhatsApp Image 2023-08-31 at 10 14 31 (1)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Mohith234**
**Description**

This PR fixes #1392 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Feedback?

**Comment by vaibhav-xt** [comment]
@Mohith234, please provide us with your latest updates regarding this issue.

**Comment by Mohith234** [comment]
### Attaching Screenshot for reference

image

**Review by vishalvivekm — APPROVED** [review]
LGTM.
Thanks @Mohith234

**Pull request merged**
