### PR TITLE
GIF on homepage needs to be updated

### LINKED ISSUE #1231: [Update] GIF on homepage needs to be updated
### Current Behavior
The GIF on the [meshery.io](https://meshery.io/) website in the hero section is old 

gif-update

### Desired Behavior
The GIF on the meshery.io website in the hero section needs to be updated with the newer look of [meshery](https://playground.meshery.io/)

---
<h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by vaibhav-xt**
**Description**

This PR fixes #1231 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by ritiksaxena124** [comment]
Hey @vaibhav-xt the GIF is moving way too fast, hard to see what is happening, could you please slow down the speed so that actions are visible

**Review by HarshDobariya79 — COMMENTED** [review]
Thank you @vaibhav-xt for the PR. But I think @ritiksaxena124 is right about reducing the speed of GIF. Another thing is if it is possible to reduce the **size** of the GIF without compromising on the **quality** much because this GIF is the **heaviest resource** of the **home page** which is responsible for the slow performance on lower bandwidths.

**Comment by samyakshah3008** [comment]
@vaibhav-xt  Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)

**Review by leecalcote — APPROVED** [review]

**Comment by vaibhav-xt** [comment]
@leecalcote Thanks 😊 for merging the pull request 🚀.

**Pull request merged**
