### PR TITLE
[meshery] Deprecate cpx adapter

### PR DESCRIPTION
**Pull request by hexxdump**
**Description**
Remove references to CPX adapter from the install script
Continuation of efforts from - https://github.com/meshery/meshery/pull/7520

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by nishantwrp — APPROVED** [review]
lgtm. btw, this change is not related to mesheryctl, right?

**Comment by hexxdump** [comment]
> lgtm. btw, this change is not related to mesheryctl, right?

corrected the description.

**Review by leecalcote — COMMENTED** [review]
We seem to be missing app-mesh

**Comment by hexxdump** [comment]
> We seem to be missing app-mesh

Its covered under this switch case, are we deprecating app-mesh as well? @leecalcote 

`traefik|app)
                adapterString="$adapterString -a meshery-$adapter-mesh "`

**Review by leecalcote — APPROVED** [review]
Much appreciated, @hexxdump 👍

**Pull request merged**
