### PR TITLE
fixed the issue of Text is not visible in dark mode #1112

### PR DESCRIPTION
**Pull request by Sumitmaithani**
**Description**
fixed the issue of Text is not visible in dark mode #1112
This PR fixes [#1112](https://github.com/meshery/meshery.io/issues/1112) 

**Notes for Reviewers**
Jwt Filter _ Meshery - Google Chrome 4_16_2023 11_42_40 PM
Jwt Filter _ Meshery - Google Chrome 4_16_2023 11_42_20 PM
Jwt Filter _ Meshery - Google Chrome 4_16_2023 11_43_15 PM
Jwt Filter _ Meshery - Google Chrome 4_16_2023 11_42_54 PM

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [*] Yes, I signed my commits.

### CODE REVIEW

**Comment by Sumitmaithani** [comment]
@vishalvivekm Please review the changes.

**Comment by leecalcote** [comment]
@Sumitmaithani thanks for this. Your PR has slipped under the radar until now. Let's get it reviewed. 👍 // @ritiksaxena124 @thisiskaransgit

**Comment by Sumitmaithani** [comment]
@leecalcote Thank you for bringing attention to my PR.

**Comment by ritiksaxena124** [comment]
LGTM 👍, Thank you @Sumitmaithani for your contribution and Keep Contributing 😎

**Comment by leecalcote** [comment]
@Sumitmaithani, ideally, this styling is applied in the `include` file - in the reusable template.

**Comment by Sumitmaithani** [comment]
@leecalcote Thanks for the feedback! 🙌 I appreciate your suggestion and will definitely keep that in mind for next time. 😊

**Comment by leecalcote** [comment]
@Sumitmaithani, good deal. Let's make next time now. Will you open a new issue and apply this change?

**Comment by Sumitmaithani** [comment]
@leecalcote 👍 Sure thing, let's do it!

**Pull request merged**
