### PR TITLE
Improve Lighthouse Score of Meshery.io Home Page

### LINKED ISSUE #973: Low Lighthouse score of Meshery.io
### Description
meshery.io is failing the Core Web Vitals Assessment

Mobile performance score is between 20-40

Check here:- https://pagespeed.web.dev/report?url=https%3A%2F%2Fmeshery.io%2F&form_factor=mobile

### Expected Behavior
The landing page should pass the Core Web Vitals Assessment

### Screenshots

Screenshot 2023-01-15 at 9 32 57 PM

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by shubhusion**
**Description**

Fixes #973 

This PR addresses issue #973 by significantly improving the Lighthouse scores for Meshery.io Home Page on both mobile and desktop platforms.

**Changes Included:**

- Enhanced the Accessibility score for Meshery.io Home Page
- Implemented lazy loading to boost performance.
- Optimized images by converting GIFs to WebM format and PNGs to WebP.
- Preconnected to required origins for faster resource loading.

**Lighthouse Score Comparison:**

| Platform | Current Website | After Updates |
|----------|-----------------|---------------|
| Mobile   | Current Mobile Score | Updated Mobile Score |
| Desktop  | Current Desktop Score | Updated Desktop Score |

**Note:** The Lighthouse scores were compared with the latest deployed preview of Meshery.io.

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin):**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ashparshp** [comment]
@shubhusion, Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by amitamrutiya** [comment]
Hey, @shubhusion Why the score for best practice and SEO decreased after update?

**Comment by shubhusion** [comment]
> Hey, @shubhusion Why the score for best practice and SEO decreased after update?

**Best Practices:**
The score decreased due to another issue, specifically #1877.

**SEO:**
The SEO score dropped because the configuration for the deployed PR preview differs slightly from the main site. Indexing is not allowed in the PR previews, which is the primary reason for the lower SEO score. This issue will be resolved on the main site, where page indexing is allowed.

**Comment by shubhusion** [comment]
@Ashparshp can you review this pr ?

**Comment by Ashparshp** [comment]
@shubhusion, what's the update about this issue?

**Pull request closed without merging**
