### PR TITLE
Patterns catalog

### PR DESCRIPTION
**Pull request by warunicorn19**
**Description**
Updates to the service-mesh-patterns catalog
This PR fixes #

**Notes for Reviewers**

**[WIP] still trying to figure how to get the filter to work**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Screenshot from Safari on mobile. 
image

**Comment by warunicorn19** [comment]
Uh-oh! Forgot to check responsiveness.

**Comment by warunicorn19** [comment]
Spent the last 4 hours trying to figure out how to filter, still no luck 🥲. Will try again tomorrow

MAJOR ITEMS LEFT: 

- [ ] figure out how to filter
- [ ] hit count

**Comment by warunicorn19** [comment]
for sure @sayantan1413

**Pull request merged**
