### PR TITLE
[Catalog] Updates on the Catalogs

### PR DESCRIPTION
**Pull request by asubedy**
Signed-off-by: asubedy <frexpe@pm.me>

**Description**
This PR addresses the changes:
1. Changed the `add-catalog` workflow.The workflow now adds the Design ID on the front matter, and now the catalog items are saved with pattern name
2. The Design ID that is shown on the webpage is now referenced from the design id that comes from the server this change is replicated on the related design mini card too
3. The text on the chips that show pattern type are now visible
4. Duplicate designs are are deleted (They were appearing because same designs were saved with `designId.md` as well as `patternName.md` hence creating the duplicates. I deleted the `designId.md` files
5. The catalog items were rendered multiple time (probably to do something about pagination {load more items} but it was breaking things than making it) which is changed now. Catalog items are rendered single time
6. Manually added designID field on the existing designs front matter

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by Revolyssup — COMMENTED** [review]
I don't see the workflow changes and also why are the existing markdown files deleted?

**Comment by asubedy** [comment]
@Revolyssup Yep I just added the workflow file I missed to commit the change. There were two files with same design id one saved with `<design-id>.md` other saved with `<design-name>.md`. Hence in the catalog we were getting duplicate items with same name hence I remove the files with `<design-id>.md` I also changed the workflow to now save design with design -name.

**Review by leecalcote — APPROVED** [review]
Outside of @asubedy's concern over conflicting pattern names, this LGTM.

@Revolyssup We need a schema defined for exported designs. This schema should include information from MeshModel Integrations (e.g. an array of model / component details for proper categorization and presentation) and from Meshery Server / Remote Provider (e.g. user id, and profile URL, so that avatar and link to profile can be included).

**Comment by Revolyssup** [comment]
> Outside of @asubedy's concern over conflicting pattern names, this LGTM.
> 
> @Revolyssup We need a schema defined for exported designs. This schema should include information from MeshModel Integrations (e.g. an array of model / component details for proper categorization and presentation) and from Meshery Server / Remote Provider (e.g. user id, and profile URL, so that avatar and link to profile can be included).

Okay, I am creating an issue for this and assigning it to myself.

**Review by Revolyssup — APPROVED** [review]

**Pull request merged**
