### PR TITLE
[Site] Updated Getting Stated Section w/signoff

### PR DESCRIPTION
**Pull request by NikhilSharma03**
Signed-off-by: Nikhil <nikhilsharmamusic2000@gmail.com>

**Description**
- Updated Getting Started Section as given in the mockup design
- Fixed scroll bar for smaller devices
  
124222683-d57cb900-dac7--8091-2728172e76ef

## After Changes

Screenshot from 2021-07-04 19-09-36

Screenshot from 2021-07-04 19-09-40

Screenshot from 2021-07-04 19-09-17

## Notes for Reviewers
Let me know if there are any other changes we can make.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by NikhilSharma03** [comment]
@leecalcote I think we can close this PR. Should I proceed with that. Thank you.

**Comment by leecalcote** [comment]
@Nikhil-Ladha the updated scrollbars is great. Can we move forward with just that update, leaving the rest for future consideration as we work through site updates?

**Comment by NikhilSharma03** [comment]
@leecalcote Yeah Sure. I will undo the other changes except the scrollbar.

**Comment by NikhilSharma03** [comment]
Updated the scrollbar and undid the other changes.

**Comment by leecalcote** [comment]
These scrollbars look awesome, @NikhilSharma03

**Pull request merged**
