### PR TITLE
Changes the background color for the choose the platform section

### LINKED ISSUE #1735: Add a better background color to Choose your platform section on homepage
### Current Behavior
The background color of a section that comes up when you click on any of the platforms under the `Choose your platform` section is the same as that of the whole section. 
image

### Desired Behavior
Change the background color of that inner section that pops up

---
<h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by shailpujan88**
**Description**

This PR fixes #1735 

**Notes for Reviewers**
Changed the background color for both light mode and dark mode for the choose the platform section.

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by shailpujan88** [comment]
Hey @ritiksaxena124 Please find the attached screenshots for both the light and dark modes.

image

image

**Comment by shailpujan88** [comment]
@leecalcote Can you suggest me a few background colors for the light mode?

**Comment by iArchitSharma** [comment]
Thanks @shailpujan88 bg color looks good but lets wait for what @ritiksaxena124 has to say

**Comment by shailpujan88** [comment]
Hey @ritiksaxena124, @iArchitSharma @leecalcote Please find the attached screenshots for both the light and dark modes. I have made the changes as told in the website meeting.

image

image

**Comment by leecalcote** [comment]
@shailpujan88, please try again.

**Comment by shailpujan88** [comment]
Hey @leecalcote Please find the attached screenshots for light mode. Can this background color works?

image

**Comment by leecalcote** [comment]
I don’t mean to make you go back-and-forth, but if you will drop any greens, any blues, or yellows and just use charcoal, greys, and blacks, I think we will be hitting our lot closer to home. See what happens when you use just a single color, not two.

**Comment by shailpujan88** [comment]
@leecalcote  Please find the attached screenshots for light mode. The color I used is a medium gray shade. It is not too dark and not too light. Can this background color works?
 
image

**Comment by sudhanshutech** [comment]
@Rexford74 looks good this colors?

**Comment by vishalvivekm** [comment]
Thank you for your contribution @shailpujan88
Let's discuss this on Websites's call on Monday. Adding this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Comment by sudhanshutech** [comment]
@Rexford74 🕧, looks good?

**Pull request merged**
