### PR TITLE
Enhance dark mode compatibility of 'Sort By' and 'Search' input fields

### LINKED ISSUE #1939: [Website] [Catalog] Enhance dark mode compatibility of "Sort By" and "Search" input fields
#### Current State of the Meshery.io site
On https://meshery.io/catalog, these two fields can be enhanced with a dark/light mode color variable

Screenshot 2024-10-27 at 6 31 23 PM

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by hymmns**
**Description**

This PR fixes #1939 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks. Which issue does this fix?

**Comment by hymmns** [comment]
Yeah apologies for not including it in the description.
It fixes issue #1939

**Comment by vishalvivekm** [comment]
@hymmns 
Thank you for your contribution!
Let's discuss this during the website call on Monday at 6:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by hymmns** [comment]
Thanks @vishalvivekm ,
Will do.

**Pull request merged**
