### PR TITLE
Added Section 4 of Community page discuss forum

### LINKED ISSUE #1271: New page design implementation for Contributors page
#### Current State of the Meshery.io site

Currently the page https://meshery.io/community/ is empty

#### Desired State of the Meshery.io site

Need to implement the mockup for this page from [Figma design](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=16435%3A39494&mode=design&t=6qls5jOGn5gJKKgm-1)
Contributors can pick separate section to implement the page fast

- [ ] Section-1: Banner section

image

- [ ] Section- 2: Resources section

image

- [ ] Section-3: Handbook section

image

- [ ] Section-4: Discuss forum section

image

- [ ] Section-5: Meshmate section

image

- [ ] Section-6: Calendar section"

image

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by ranjanmangla1**
**Description**

This PR fixes #1271 

**Notes for Reviewers**
Completed Section 4

image

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by ranjanmangla1** [comment]
@thisiskaransgit can you review this pr?

**Comment by vishalvivekm** [comment]
@ranjanmangla1 Let's discuss it on the websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

**Comment by thisiskaransgit** [comment]
@ranjanmangla1, the workflow is working now, update the branch please

**Comment by Chadha93** [comment]
Merge conflicts @ranjanmangla1 .....

**Comment by thisiskaransgit** [comment]
Kudos for submitting this PR @ranjanmangla1 🙌🏼  ! We truly appreciate your dedication and hard work towards the project.
I wanted to give you a heads-up that we'll be closing this PR since it has been incorporated by another one. But please remember, your contribution is valuable and makes a difference!
Thank you again for being part of our community!

**Pull request closed without merging**
