### PR TITLE
feat: updated calendar section

### LINKED ISSUE #1202: [Site] Enhance Community Calendar page
#### Current State of the Meshery.io site
The content, styles, and links need to be enhanced with the latest information. 

#### Desired State of the Meshery.io site
1. Eliminate the extra whitespace between the header and the community calendar section. 
image
2. Update the link for the welcome guide to - https://layer5.io/community/newcomers.
3. Don't use italics in the community links section.
4. Add a CTA (Call to action) for newcomers welcome, ref - https://layer5.io/community/calendar

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by thisiskaransgit**
**Description**

This PR fixes #1202

image

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by HarshDobariya79 — COMMENTED** [review]
Thank you for this PR @thisiskaransgit. The updated section below the calendar looks good. Just one thing I've noticed is there's still some space between the header and the community calendar section in the build preview (issue point 1). I'm not sure if it is intended or not, but can you please check that out? Rest LGTM.

**Comment by vishalvivekm** [comment]
@thisiskaransgit Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)

**Comment by leecalcote** [comment]
We might be intermingling Meshery and Layer5 too much.

**Comment by Chadha93** [comment]
> We might be intermingling Meshery and Layer5 too much.

Yea, since new pages are being worked on, we will probably update this graphic later and point those links to meshery.io new pages.

**Review by Chadha93 — APPROVED** [review]
Thank you @thisiskaransgit

**Pull request merged**
