### PR TITLE
Added a new section and link to the CNCF Hosted Projects w/signoff

### LINKED ISSUE #549: Add link to CNCF Meshery Community
**Desired State of the Meshery.io site**
Find a good spot on the site to add a link to this community - https://community.cncf.io/meshery-community/

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by AnshumanDhiman**
Signed-off-by: AnshumanDhiman <67755381+AnshumanDhiman@users.noreply.github.com>

**Description**

This PR fixes #549 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Zain-Muiz** [comment]
Heyy @AnshumanDhiman . Good work ! Just wanted to confirm, Is this PR doing the same work as done in #553 ? If it is, Could you please close that other PR and we can focus on this. Also it would be great if you can update the description of this PR to attach Screenshot of the work you've done. ( Something like the other PRs description.)

**Review by warunicorn19 — CHANGES_REQUESTED** [review]
@AnshumanDhiman good stuff, just noticed the image looks a bit small compare to the others used in that section. Maybe consider using something like this 

Screenshot 2021-09-15 at 1 50 09 PM

or you could just take your own screenshot, this is just to keep the consistency in image size.

**Comment by Zain-Muiz** [comment]
@warunicorn19 , Also, I was just wondering that since no of group members are mentioned in the image, Is it a good choice to have a image with that number there ? ( The number is gonna remain static there, and so someday we would have to keep changing it again. ) . What are your opinions ? @AnshumanDhiman  @warunicorn19

**Comment by warunicorn19** [comment]
@Zain-Muiz yes good catch🤔. We wouldn't want the no. Of member to be shown. Okay we need to figure this one out.

**Comment by leecalcote** [comment]
This should not be added to the main page. @AnshumanDhiman let's start getting your proposed updates into Figma for review before implementation so that:

1) we can give holistic consideration as to the layout of the site
2) we avoid churn

**Comment by AnshumanDhiman** [comment]
oopsie my bad @leecalcote 😅 let me come with another idea on how to fit this into the page

**Comment by leecalcote** [comment]
> oopsie my bad @leecalcote 😅 let me come with another idea on how to fit this into the page 

Sounds real good, @AnshumanDhiman 👍

**Comment by warunicorn19** [comment]
@AnshumanDhiman considering our page is already too long right now, and there's already a callout for this CNCF group, I'll close this PR. Sorry for the miscommunication.

**Pull request closed without merging**
