### PR TITLE
add wasm filter to the technology filters

### PR DESCRIPTION
**Pull request by Touriist**
**Description**

This PR 

image

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
@Touriist thanks for ensuring that WASM Filters are visible to site visitors.

**Comment by Touriist** [comment]
> @Touriist thanks for ensuring that WASM Filters are visible to site visitors.

needs some fixes, thank you. updating..

**Comment by Touriist** [comment]
done 
image

**Review by vishalvivekm — APPROVED** [review]
LGTM. Thank you @Touriist

**Pull request merged**
