### PR TITLE
Fixed visible underline on hover.

### LINKED ISSUE #1233: [Bug] Visible underline on hover of "GitHub Star" on homepage
### Description
A small green underline is visible on hover of "GitHub Star" on the [meshery.io](https://meshery.io/) website homepage under GIF

issue-2

### Expected Behavior
Remove the underline

### Environment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by DevilsAutumn**
**Description**

This PR fixes #1233 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ghat0tkach** [comment]
LGTM 🙌

**Review by ritiksaxena124 — APPROVED** [review]
Nice work @DevilsAutumn 👌. Thank you for contributing. Hope to see more contributions from your side.

**Comment by DevilsAutumn** [comment]
> Nice work @DevilsAutumn 👌. Thank you for contributing. Hope to see more contributions from your side.

Thanks 👍

**Review by thisiskaransgit — APPROVED** [review]
Looks good to merge, thank you for your contribution :tada:

**Comment by samyakshah3008** [comment]
@DevilsAutumn  Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)

**Comment by DevilsAutumn** [comment]
> @DevilsAutumn  Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)

Sorry I don't understand what exactly you mean by "discuss" here. Is there anything still left in the PR?

**Comment by vishalvivekm** [comment]
> > @DevilsAutumn  Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)
> 
> Sorry I don't understand what exactly you mean by "discuss" here. Is there anything still left in the PR?

We've weekly websites meeting at 5:30 PM IST. Let's get this PR reviewed on the call.
Please do attend the meeting to discuss your efforts here. Add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) @DevilsAutumn

**Review by HarshDobariya79 — COMMENTED** [review]
Nice work @DevilsAutumn. Just one general question out of curiosity. The code responsible for the underline is present at https://github.com/meshery/meshery.io/blob/master/_sass/elements.scss#L24-L27, are we using underlines for links anywhere on the site🤔? 
// @girishranganathan

**Pull request merged**
