### PR TITLE
Removed transform property of buttons

### LINKED ISSUE #1128: Make buttons UX consistent across the site
### Description

Currently the ux of  buttons in meshery site is not consistent as all buttons are same in ui. Somewhere we have hover, somewhere we have hover and scaling and this is making ux a bit bad and creating ui bugs.

https://user-images.githubusercontent.com/90546692/233201764-943a33cc-6666-4494-9065-6b4f54c6a0b6.mp4

https://user-images.githubusercontent.com/90546692/233201995-5c5f4504-f3f7-4421-895e-07a8d25c5ebe.mp4

in https://meshery.io/blog

https://user-images.githubusercontent.com/90546692/233202401-a5d3afb8-846b-49a9-b830-3910cedc1ba5.mp4

### Expected Behavior

for now expected behaviour across all buttons should be in homepage https://meshery.io/ in `view catelog` button has
image

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Saksham294**
**Description**

This PR fixes #1128 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Saksham294** [comment]
@sudhanshutech Hey I have made the desired changes, kindly check. Thanks

**Review by senali-d — COMMENTED** [review]
Thank you for the PR @Saksham294 

Some changes that can be worked on:

https://meshery.io/talks-and-presentations page "Find video and slides here" button still not fixed.

https://user-images.githubusercontent.com/52546856/234038452-db6a4ccc-3699-4590-a55b-2c14c2ce5e91.mp4

**Comment by vishalvivekm** [comment]
Are you done incorporating changes suggested by @senali-d ? 
Add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) ,  and sound off on your updates ;)

**Comment by Saksham294** [comment]
@senali-d Can you check if the changes made are fine? If yes then we can merge this PR.

**Review by senali-d — CHANGES_REQUESTED** [review]
@Saksham294 Still "Find video and slides here" button issue was there.

Ref: https://github.com/meshery/meshery.io/pull/1140#pullrequestreview-1398257994

**Comment by vishalvivekm** [comment]
@Saksham294  Let's not put it off any further.
will you come up with a update on websites call ? please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#)

**Comment by Saksham294** [comment]
@senali-d I have done the required changes, it was the border on hover creating the issue. Kindly check, thanks
@vishalvivekm I can add this item to tomorrow's call, however I won't be able to join it.

**Review by senali-d — COMMENTED** [review]
@Saksham294 LGTM
// @vishalvivekm

**Comment by Saksham294** [comment]
@Chadha93 We can merge this if the changed made are fine

**Review by thisiskaransgit — APPROVED** [review]
Looks good to merge, thank you for your contribution :tada:

**Pull request merged**
