### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by shadow0500**
Add some additional info and convert lower cases into upper case so it looks much professional.

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@shadow0500 

It would be great if, in the future, you could avoid making direct PRs without prior discussion. Please first open an issue or share your ideas or proposed changes on [discuss forum](https://discuss.layer5.io) or in the appropriate [slack channel](https://slack.meshery.io) as this helps prevent any unintended issues or conflicts.

- Uppercasing the front-matter variables here is not required and may cause unintended results ( which here's a blank [homepage](https://deploy-preview-1184--mesheryio-preview.netlify.app/)).

Please join the [community](https://slack.meshery.io) and star 🌟  the [repo](https://github.com/meshery/meshery), let's find another issues you can work on in the community.
// @thisiskaransgit

**Comment by shadow0500** [comment]
> @shadow0500
> 
> It would be great if, in the future, you could avoid making direct PRs without prior discussion. Please first open an issue or share your ideas or proposed changes on [discuss forum](https://discuss.layer5.io) or in the appropriate [slack channel](https://slack.meshery.io) as this helps prevent any unintended issues or conflicts.
> 
> * Uppercasing the front-matter variables here is not required and may cause unintended results ( which here's a blank [homepage](https://deploy-preview-1184--mesheryio-preview.netlify.app/)).
> 
> Please join the [community](https://slack.meshery.io) and star 🌟 the [repo](https://github.com/meshery/meshery), let's find another issues you can work on in the community.
> 
> This PR can be closed. // @thisiskaransgit

Okay , I will take care of it from the next time and thank you so much for your feedback and response

**Comment by leecalcote** [comment]
Thanks for the effort here, @shadow0500. Let’s find you something else to work on. These changes are not desired. Please see the “help wanted” hyperlink in the readme for a list of issues to work on.

**Comment by shadow0500** [comment]
okay @leecalcote  I will look for some other issues and let you know if I can work on that  or not and thank you so much for the feedback.

**Pull request closed without merging**
