### PR TITLE
fixed heading alignment in footer

### LINKED ISSUE #1530: Alignment issue in the footer
### Description

I have identified an alignment issue with the item heading in the footer. The elements in the footer are not properly aligned, causing a visual inconsistency.

Screenshot (518)

### Expected Behavior
Screenshot (517)

I want to work on this issue , please assign it to me .

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by charu1603**
**Description**
Heading alignment fixed in the footer  
Screenshot (517)

This PR fixes #1530 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by abhijeetgauravm — APPROVED** [review]
LGTM, @charu1603. Thanks for the contribution!

**Comment by leecalcote** [comment]
Even better than this, would be to have icons for each of the headings.

**Comment by leecalcote** [comment]
> Even better than this, would be to have icons for each of the headings.

Are you up to this challenge, @charu1603?

**Comment by leecalcote** [comment]
@abhijeetgauravm will you open a new issue for this subsequent enhancement?

**Comment by charu1603** [comment]
Sure , I will add the icons for each heading

**Comment by abhijeetgauravm** [comment]
> Yeah , that's a better solution. I will add the icons for each heading. Can I open a new issue for this ?

Yeah @charu1603 open a new issue if you would!

**Pull request merged**
