### PR TITLE
fix #1402

### LINKED ISSUE #1402: Lack of Spacing Between Next and Previous Blog Links in Blog Pagination
### Description
We can see the links for the next and previous blog are attached together for all the blogs in the website https://meshery.io/blog
Screenshot 2023-09-02 225200

### Expected Behavior

There should be enough gap between both the previous and next links for the good visibility and also for good user interaction (UX).

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Narottamchy**
**Description**
Lack of Spacing Between Next and Previous Blog Links in Blog Pagination #1402

This PR fixes #1402 

Signed-off-by: Narottamchy <narottamchy5134@gmail.com>

### CODE REVIEW

**Comment by Narottamchy** [comment]
fix#1402

please review the changes and accept the pull request

@Chadha93 
@leecalcote

**Comment by VaibhavMalik4187** [comment]
Please squash the commits into one commit, update the commit message and the commit description.

**Review by Mohith234 — APPROVED** [review]
Looks good to me! @Narottamchy 🚀

Also a fair warning. Do not create PRs without being assigned.  First, ask for an assignment and then work on that issue.

**Comment by vishalvivekm** [comment]
Hi @Narottamchy 
Please go through the [contributing guidelines](https://layer5.io/community/handbook/contribution) and code of conduct outlined in the [community handbook](https://layer5.io/community/handbook). Also refer to https://layer5.io/community/handbook/faq to know how to approach working on issues within the community.

A descriptive PR title would be helpful.

**Review by vishalvivekm — APPROVED** [review]
LGTM
Thanks @Narottamchy 🚀

**Pull request merged**
