### PR TITLE
Fixed eBPF logo for dark-mode

### LINKED ISSUE #1470: Add a dark-mode version of eBPF logo on meshery catalog page
Currently the eBPF logo is not visible accurately [on](https://meshery.io/catalog)

Screenshot 2023-10-19 195715

Add a suitable dark mode image following the guidelines of eBPF logo mentioned [here](https://ebpf.foundation/brand-guidelines/)

### PR DESCRIPTION
**Pull request by sidharthbh8**
**Description**
Changed eBPF in dark mode logo according to [brand guidelines](https://ebpf.foundation/brand-guidelines/)
This PR fixes #1470

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
// @shreyas0410

**Comment by Shreyas0410** [comment]
Was working on this [issue](https://github.com/layer5io/layer5/issues/5070) where this was suggested
`let's not use the all white version, though. Instead add a white stroke or some other background to help increase the contrast. The all white version of the logo will not complement the other three that are in color.` 
Maybe the same applies here?

**Comment by Mohith234** [comment]
Appreciate your enthusiasm @sidharthbh8

Some points to consider for the PR
1. We shouldn't be using the all-white logo, instead, we need to add some strokes as mentioned by @Shreyas0410 
2. `Gemfile.lock` shouldn't be committed
3. Please do not create any PRs unless the issue is assigned to you. Ask for assignment before contributing.

**Comment by Mohith234** [comment]
@sidharthbh8 Update the PR and Let's discuss this on website call today at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Comment by leecalcote** [comment]
Merge conflict…

**Comment by iArchitSharma** [comment]
@sidharthbh8 are you still there?

**Comment by sudhanshutech** [comment]
@sidharthbh8 there should be no change in gemfile.

**Comment by sudhanshutech** [comment]
As the contributor being inactive and issue also getting stales we should close this and get reassigned or @sidharthbh8 you can open a new one if you want. Mostly i see that the issue is no needed because the current logo seems to be good unless we don't have proper ebpf logo in dark mode.

**Pull request closed without merging**
