### PR TITLE
Catalog for Service Mesh #664

### LINKED ISSUE #664: Not mobile friendly: service mesh catalog
**Current State of the Meshery.io site**
The catalog on [meshery.io/catalog](http://meshery.io/catalog) is mobile challenged in two ways:

The catalog needs improvement to be mobile friendly both 1) in terms of the topmost patterns and filters icons/sections and 2) the catalog filters not displaying.

Screen Shot 2022-02-03 at 8 56 23 PM

---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by ashutosh887**
**Description**

This PR fixes #664

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@ashutosh887 thanks. It's difficult to review your changes with this many lines changed. It's not clear that that lines changes are material changes either. I wonder if you might submit commits with only changes to lines that you've made....?

The mobile view will need the view filters collapsed - 

Screen Shot 2022-02-16 at 11 39 26 PM

**Comment by YashKamboj** [comment]
@ashutosh887 it will be great if you make an option to collapse it in the mobile view

**Review by YashKamboj — CHANGES_REQUESTED** [review]

**Comment by ashutosh887** [comment]
@leecalcote 
I made changes in only two files

It shows many changes because there was an extra space at Line Number 1 in catalog-features.scss

**Comment by YashKamboj** [comment]
@ashutosh887 yeah but it gets really difficult to reviews as there is difference in every line

**Comment by ashutosh887** [comment]
checking it @leecalcote

**Comment by leecalcote** [comment]
Thanks. Note the merge conflict.

**Comment by leecalcote** [comment]
Checking in...

**Comment by leecalcote** [comment]
@warunicorn19 I assume this PR is abandoned. Will you assist in determining whether to carry it forward or close out?

**Comment by warunicorn19** [comment]
Yes sir @leecalcote

**Pull request closed without merging**
