### PR TITLE
Catalog open-modal margin issue w/signoff

### LINKED ISSUE #1391: Catalog open-modal margin issue
### Description
I found a bug on open-modal. margin should be zero (width < 700px) it should same as the desktop. 

sdfs (3)

### Expected Behavior
margin should be zero.
> expected 
Screenshot (280)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---

 
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by harish343**
**Description**

This PR fixes #1391

**Catalog open-modal margin issue**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vaibhav-xt** [comment]
Big kudos, @harish343 You've got this issue sorted. One suggestion: Skip those lines instead of zeroing them. 👍👌

**Comment by harish343** [comment]
Hey @vaibhav-xt I removed those lines. how can I run Netlify deploy preview again.

**Comment by vaibhav-xt** [comment]
Hello @leecalcote & @Ghat0tkach, it's good to merge & waiting for your response.

**Review by Chadha93 — APPROVED** [review]
Thank you @harish343.

**Pull request merged**
