### PR TITLE
Added Logo

### LINKED ISSUE #844: Add meshery & slack logo to the readme
#### Description

There are logos in README.md that have very low contrast in light/dark mode.
i.e Meshery Logo (In Dark Mode and Light Mode) & Slack Logo in Light Mode 
#### Expected Behavior

Changing the logos for dark/light mode with high contrast

#### Screenshots

Screenshot (466)
Screenshot (467)
Screenshot (468)

#### Enviroment:
 - OS: Windows
 - Browser: Chrome 
 - Version: 
 - Device: Desktop

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by UtkarshMishra12**
Signed-off-by: Utkarsh Mishra <nasautkarsh@gmail.com>

**Description**
Changed the Meshery logos for dark/light mode with high contrast
This PR fixes #844

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
Will you please confirm that this is the same code (verbatim) of the other readmes in the repos in the `Meshery` org?

**Comment by UtkarshMishra12** [comment]
Yes, the code I have used is taken from the [README.md](https://github.com/meshery/meshery/blob/master/README.md) of Meshery Repo as suggested by Kamal in other issue also [link](https://github.com/meshery/meshsync/issues/150)

**Comment by legendarykamal** [comment]
> Will you please confirm that this is the same code (verbatim) of the other readmes in the repos in the `Meshery` org?

although this creates a dependency that the image should be there in main meshery/meshery repo with using this https://raw.githubusercontent.com/meshery/meshery/master/.github/assets/images/meshery/meshery-logo-dark-text-side.svg but @leecalcote that seems fair to me as it is our main repo and we don't have to manually add the same logo to each repo.

**Review by legendarykamal — DISMISSED** [review]
Tested and works fine for both light and dark mode . ⭐

**Comment by UtkarshMishra12** [comment]
@leecalcote he(Kamal) has tested the changes.

**Comment by leecalcote** [comment]
> > Will you please confirm that this is the same code (verbatim) of the other readmes in the repos in the `Meshery` org?
> 
> although this creates a dependency that the image should be there in main meshery/meshery repo with using this https://raw.githubusercontent.com/meshery/meshery/master/.github/assets/images/meshery/meshery-logo-dark-text-side.svg but @leecalcote that seems fair to me as it is our main repo and we don't have to manually add the same logo to each repo.

@legendarykamal you're right. I neglected to be more precise that the desire is for images to be locally referenced (as they are stored in each repo), but that the rest of the html/markdown was to be identical. Ideally, even the references are identical - - they would be if relative references were used.

**Comment by UtkarshMishra12** [comment]
@leecalcote  What should I do now, Can you guide me with this PR?

**Comment by leecalcote** [comment]
I'll defer to @legendarykamal.

**Comment by UtkarshMishra12** [comment]
Hey, @leecalcote  so I have to take the Logo image from the local repo(store the media inside the repo, and refer to its path for showing it on Readme.md), not from the other repo?

**Comment by legendarykamal** [comment]
yes @UtkarshMishra12  store it locally and then use relative referencing to render it.

**Comment by UtkarshMishra12** [comment]
@leecalcote @legendarykamal  As per your suggestion, I have stored the logos locally and then used relative referencing to render them.
Let me know your thought on it.

**Review by legendarykamal — DISMISSED** [review]
LGTM 🛩️ , good to go .

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Why does the filename have "new" in it?
Does a file with the same already exists? If yes, why not reuse it?
If not, then please remove "new" from the filename

**Comment by UtkarshMishra12** [comment]
@Nikhil-Ladha I'll remove the new from the filename.

**Comment by UtkarshMishra12** [comment]
@Nikhil-Ladha Changes are done🙌

**Review by Nikhil-Ladha — APPROVED** [review]
Looks good

**Comment by legendarykamal** [comment]
sharp eye @Nikhil-Ladha ✅ 👏

**Pull request merged**
