### PR TITLE
[Chore] Remove old chart

### PR DESCRIPTION
**Pull request by miacycle**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by fitzergerald — APPROVED** [review]
Was there an operator chart, too?

**Comment by miacycle** [comment]
I just looked, @fitzergerald. No, this is it.

**Review by winkletinkle — APPROVED** [review]
I give it a tinkle.

**Comment by ritzorama** [comment]
The rizzler says, "LTGM".

**Review by ritzorama — APPROVED** [review]

**Pull request closed without merging**
