### PR TITLE
Added icon in the footer #1437

### LINKED ISSUE #1437: icon adjustment in the footer
### Current Behavior
There is a icon for only calendar it is looking bad let me fix that .

### Desired Behavior
 By removing calendar icon or add other element icon also helps the footer to look good .

### Screenshots / Mockups
calender

### PR DESCRIPTION
**Pull request by hemantmm**
**Description**

This PR fixes #1437 

**Notes for Reviewers**

I have added icons to the footer of the meshery.io page

icons

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by hemantmm** [comment]
Hi, @leecalcote can you have a look at it?

**Comment by abhijeetgauravm** [comment]
Hey @hemantmm  Let's discuss this on website call tomorrow at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by leecalcote** [comment]
Thank you, @hemantmm

**Review by sandramsc — COMMENTED** [review]
@hemantmm Thank you for your contribution. The additional icons under the **Community** section reflect the initial goal of the issue. 

Reading the initial issue description I understand it to be that all link texts in the footer will have icons added next to them. Is there a particular reason why the **Getting Started** (heading & links), **Resources** (heading & links (all)) and **Socials** heading do not have icons assigned in this PR?

**Comment by hemantmm** [comment]
@sandramsc it's not an issue adding the remaining icons in the **Getting Started** (heading & links), and **Resources** (heading & links (all)).

**Review by sudhanshutech — APPROVED** [review]
it looks good for now, lets move forward with this because the pr will get hold up otherwise. @hemantmm please open other issue for icons to other footer links as said by @sandramsc  and we will assign to you

**Pull request merged**
