### PR TITLE
navbar dropdown mobile view width fix

### LINKED ISSUE #812: [UI] Modifying Navbar dropdown such that it takes full width in mobile view
#### Current Behavior
Navbar dropdown doesn't take full width in mobile view and looks a bit weird.

Screenshot from 2022-06-07 02-05-36

#### Desired Behavior
To modify Navbar dropdown in meshery.io UI such that it takes full width in mobile view with it's items aligned to left. After clicking on Menu the dropdown will roll down from bottom taking full width and items aligned in left side

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by amRohitKumar**
**Description**

This PR fixes #812 

**Notes for Reviewers**

Now navbar dropdown will take full width below 568px.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Rohith-Raju** [comment]
@amRohitKumar, clicking the meshery logo should take us back to the homepage but it opens the menu 

[screen-recorder-wed-aug-24-2022-10-43-49.webm](https://user-images.githubusercontent.com/55309324/186335369-8b624ee5-d9f3-4dd2-bb19-3ccbcd98b157.webm)

**Comment by Rohith-Raju** [comment]
@amRohitKumar Screenshot of the deploy preview from my phone...
Browser: Chrome 
Os: Andriod, poco m2 pro

WhatsApp Image 2022-08-24 at 10 37 45 AM (2)

**Comment by amRohitKumar** [comment]
> @amRohitKumar, clicking the meshery logo should take us back to the homepage but it opens the menu
> 
>  screen-recorder-wed-aug-24-2022-10-43-49.webm

I'll try to fix this up

**Comment by leecalcote** [comment]
Ready for another review? Or has too much changed with the menu, @Rohith-Raju ?

**Comment by Rohith-Raju** [comment]
@amRohitKumar clicking the logo takes you to the home page. That's working fine. The menu should drop down only when you click on the hamburger icon. even the empty space between the logo and the icon is clickable
[screen-recorder-thu-sep-22-2022-05-03-49.webm](https://user-images.githubusercontent.com/55309324/191628276-4eacccc6-f86d-4976-86f0-961675e908f5.webm)

**Review by Rohith-Raju — CHANGES_REQUESTED** [review]

**Comment by Rohith-Raju** [comment]
> @amRohitKumar Screenshot of the deploy preview from my phone... Browser: Chrome Os: Andriod, poco m2 pro
> 
> WhatsApp Image 2022-08-24 at 10 37 45 AM (2)

This issue is still persisting.

**Comment by leecalcote** [comment]
I didn’t realize until now how about this issue is. Mobile users are not able to navigate the site. We need to make sure this gets fixed quickly. @amRohitKumar 

@Rohith-Raju will you fix immediately? We have let this issue ride for too long.

**Comment by Rohith-Raju** [comment]
Ok @leecalcote, @amRohitKumar fell free to ask for help if you run into any.

**Comment by leecalcote** [comment]
@Rohith-Raju will you move forward with a separate PR now, please?

**Comment by leecalcote** [comment]
There’s no time to waste.

**Comment by Rohith-Raju** [comment]
@leecalcote sure

**Pull request closed without merging**
