### PR TITLE
remove extra whitespace in responsive view

### PR DESCRIPTION
**Pull request by JayKay24**
**Description**

This PR fixes [#1238](https://github.com/meshery/meshery.io/issues/1238)

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks, @JayKay24!

**Review by officialarmannqureshi — APPROVED** [review]
Excellent work, @JayKay24! I have thoroughly reviewed all the changes, and I can confirm that they effectively address and eliminate issue #1341. Great job!

**Review by thisiskaransgit — CHANGES_REQUESTED** [review]
Thanks much @JayKay24, container style change won't be necessary here, the real scope of improvement here would be to keep the cards' gap consistent for all device widths alongside updating the section margin/padding consistent between ~700px.  Please look into it.

**Comment by Ghat0tkach** [comment]
hey @JayKay24 

 Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by JayKay24** [comment]
@leecalcote @thisiskaransgit @officialarmannqureshi  There seems to already be a fix for this in production. This PR could be redundant.

**Comment by thisiskaransgit** [comment]
@JayKay24. the scope of enhacement that I mentioned is still there

**Pull request closed without merging**
