### PR TITLE
Patterns filter

### PR DESCRIPTION
**Pull request by warunicorn19**
**Description**
After several attempts, I wasn't able to get any success with the multiple filters, so added a basic filter for the time being. 
This PR fixes #

**Notes for Reviewers**
Just an attempt to try filtering, if it doesn't look good will close PR.  

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
@leecalcote @debo19 I just added a basic filter functionality right now since the link to this page is on the KubeCon China Slide deck, please let me know if this looks okay for now or not.

**Comment by leecalcote** [comment]
Looks like there is a little bit of overlap. image

**Comment by leecalcote** [comment]
Otherwise, yes.

**Comment by warunicorn19** [comment]
@leecalcote i was going for that look😅, signifying `All`

**Comment by warunicorn19** [comment]
okay, I'll change that to some other icon, maybe the service-mesh-patterns icon? @leecalcote

**Comment by leecalcote** [comment]
Ha! It... didn't quite hit the mark.  To move quickly, you could try https://thenounproject.com/icon/select-all-1800023/

**Comment by warunicorn19** [comment]
PR updated @leecalcote.

**Review by sayantan1413 — DISMISSED** [review]
Yes, @warunicorn19 this code looks good to me. But there are a lot of code repetitions that can be improved later.

**Comment by warunicorn19** [comment]
@sayantan1413 i agree.

**Pull request merged**
