### PR TITLE
Reusable video modal and pattern video

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: leecalcote <leecalcote@gmail.com>

### Approach
- small javascript file; simple, direct dom interaction.
- reusable Jekyll "component" for playing video in a modal.

### Functionality
- Reusable video modal: `includes/video-modal.html` - supply it the video title and source.
- Video modal takes sits about 8rem from top of screen, takes up 80% width of screen (it is responsive).
- Video auto plays on modal open; pause on mouse click or on dismiss of modal (pause, not stop).
- Modal dismissible via close (x) or clicking anywhere else.

### Opportunity for enhancement:
- Capture ESC key; pause video; close modal.
- Functionality to start or start the video on press of spacebar.

### CODE REVIEW

**Comment by warunicorn19** [comment]
The the modal is getting chopped of for me.
Screenshot 2021-12-31 at 4 17 37 PM

**Comment by shubham-tyagi** [comment]
Yeah, @leecalcote, you have actually made the code so much simpler and easy to debug but I also encountered a similar issue like @warunicorn19.

**Comment by leecalcote** [comment]
@warunicorn19 good highlight. I think an improvement is possible. Under this implementation, users might need to scroll down a bit depending on their screen size ratio.

**Comment by warunicorn19** [comment]
Actually it doesn't fit on scroll either, the modal remains fixed.

**Comment by leecalcote** [comment]
Smaller screens may have trouble. At some point, people will have to just maximize the video to see it.

**Comment by warunicorn19** [comment]
Okay.

**Review by warunicorn19 — APPROVED** [review]
LGTM!

**Comment by leecalcote** [comment]
I have just tried ~82 different combinations of styles trying to get the modal content vertically centered and size appropriate so that all of the width fits irrespective of browser size. I toss in an update, which I _think_ is a slight improvement.

If either of you would like to attempt vertically center, please do. Otherwise, merge at-will.

**Comment by shubham-tyagi** [comment]
I am gonna try to make it vertically center.

**Review by warunicorn19 — APPROVED** [review]
Let's merge, for now, @shubham-tyagi you can work on it separately

**Pull request merged**
