### PR TITLE
Fix: modal styles updated for dark theme and minor alignment issues

### PR DESCRIPTION
**Pull request by samyakshah3008**
## **Description**

- On the community website of Meshery, in the resources -> talks and presentation -> when we click on "find video and slides here" button, we display a modal. 
- The bug was modal was not configured with the styling which we wish to display for dark theme. This PR aims to fix this particular issue + minor alignment issues as a bonus. 
- Head over to https://deploy-preview-1199--mesheryio-preview.netlify.app/talks-and-presentations to check out the changes. 

## Checklist of changes made: 

- [X] Change the background color for dark theme: changed to `--color-primary-dark` from rootvariables.scss
- [X] Change the color for dark theme of header title 
- [X] Fix alignment issues of cross button
- [X] Made the anchor link of modal to bold for better visibility
- [X] Made html element `small` to bold for better visibility 
- [X] Removed `!important` from the modal file where I worked
- [X] When we click outside modal or on cross button, modal will be closed. Fixed the bug which was "close of modal if we click on any text of modal"
## This PR fixes #

#1196 

### Previous buggy design (for dark theme): 

image

### Updated fresh fixed design (for dark theme): 

image

### Updated fresh fixed design (for light theme): 

image

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Savio629** [comment]
@samyakshah3008 When clicking on the popup anywhere, the popup should not close. Instead, the close button or clicking outside of the popup should be the actions that close it.

**Comment by samyakshah3008** [comment]
Good catch @Savio629 
Fixed it if we click anywhere on modal, the modal will not be closed. 
Yet to figure out if we click outside the modal it should close.

**Comment by samyakshah3008** [comment]
@Savio629 I have worked on your suggested changes, can you please check again?

**Comment by vishalvivekm** [comment]
@samyakshah3008 Let's discuss this in websites call. Add this as agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would :)

**Review by Savio629 — COMMENTED** [review]
LGTM 👍

**Review by DarrenDsouza7273 — APPROVED** [review]
Amazing work @samyakshah3008

**Comment by samyakshah3008** [comment]
@Shivam-AfA I got a approval from Darren and Savio, can you please look into it? If it looks good then we can push this into prod 😄

**Comment by Shivam-AfA** [comment]
@Chadha93

**Review by Chadha93 — APPROVED** [review]
Such a nice and commendable write-up @samyakshah3008  :clap:

**Comment by samyakshah3008** [comment]
> Such a nice and commendable write-up @samyakshah3008 👏

Thanks a lot, Gaurav! ✨

**Pull request merged**
