### PR TITLE
[Site] Extra lfx text removed 

### LINKED ISSUE #791: [Site] Remove the extra LFX text
**Description**
Remove the extra LFX text 
bug

**Expected Behavior**
Just keep the LFX logo, remove the extra text highlighted. 

**Screenshots**
Add screenshots, if applicable, to help explain your problem.

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by legendarykamal**
Signed-off-by: Kamal Nayan <geniusamansingh@gmail.com>

**Description**
Removed the extra LFX text
This PR fixes #791 

**Notes for Reviewers**
Screenshot from 2022-07-30 11-00-19

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
Yes, I signed my commits.

### CODE REVIEW

**Review by Chadha93 — APPROVED** [review]
LGTM :1st_place_medal:

**Comment by Chadha93** [comment]
@legendarykamal Yay!! Keep these contributions of yours coming. 💪

**Comment by legendarykamal** [comment]
Sure @Chadha93  I love this community 😃🙌

**Comment by leecalcote** [comment]
🎈🥳

**Pull request merged**
