### PR TITLE
Add Star Button to Meshery

### LINKED ISSUE #1183: Add "Star the Repository ⭐ " button for Meshery
### Current Behavior
Add a button on the HomePage to redirect the user to the [Meshery](https://github.com/meshery/meshery) Repository 

---
<h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Saksham294**
**Description**

This PR fixes #1183 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Gautam-666** [comment]
1. Maybe use #00B39F, instead of yellow because the text is not visible in light mode.
2. Can you check the hover effect in dark mode? It is not working correctly in dark mode.

**Comment by Saksham294** [comment]
Hey @Gautam-666 ! Thanks for the suggestions 
I was thinking that maybe we can make the drop shadow color as #00B39F or change the color of button on hover just like in the case of other buttons on the page. I have changed the background color of the button from yellow to #00B39F though.

**Comment by Gautam-666** [comment]
I got your point @Saksham294 but issue with yellow colour was that it wasn't really attracting the attention of the viewer in Light mode especially.

**Review by thisiskaransgit — CHANGES_REQUESTED** [review]
1. Use the github social-icon image for this, adding another svg would be unnecessary 
2. To keep the consistency of the styles, use the existing ones

**Comment by Saksham294** [comment]
> 1. Use the github social-icon image for this, adding another svg would be unnecessary
> 2. To keep the consistency of the styles, use the existing ones

2. You mean to remove the current CSS styles I added and make them using existing ones right?

**Comment by thisiskaransgit** [comment]
@Saksham294, yes

**Comment by vishalvivekm** [comment]
@Saksham294 
If you could incorporate the suggested changes, we can discuss this in websites call tomorrow. Be sure to add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk)

**Comment by leecalcote** [comment]
IMG_8624
Looks good on mobile.

**Review by leecalcote — APPROVED** [review]
Thank you, gents. LGTM

**Comment by Savio629** [comment]
@Saksham294 Can you just check the following  hovering issue between the buttons?

https://github.com/meshery/meshery.io/assets/91362589/effaec1e-3bfe-4410-b0f1-9f1a60ca6b81

**Comment by Saksham294** [comment]
@Savio629 the issue is while hovering the anchor tag. If we want to fix this we have to change the a: hover. However this will change the effect for other elements as well. Another way is to add another class to this anchor tag

**Pull request merged**
