### PR TITLE
Errors removed 

### LINKED ISSUE #1628: Removing errors from the website main page
### Current Behavior
The homepage of the website is generating errors every few seconds. And it keeps pilling up.

### Desired Behavior
The homepage should function without generating errors

### Screenshots / Mockups
image2

---
<h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by surajvast1**
**Description**

This PR fixes #1628 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@surajvast1 Thank you.
Let's discuss this in Websites meeting please: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

**Comment by sudhanshutech** [comment]
@surajvast1 how are you sure about the following error is due to the following change

**Comment by surajvast1** [comment]
Hey @sudhanshutech   
Nice Question 
As you see in the image 
image

the issue is  due to slick carousel which was used in the slider component  
image

so i  found out that slick carousel is used in footer.html file inside     this path _include > footer.html 
and the attribute slidesToScroll was set to 0.5 and it expected a integer value so changing that removes the error 
I was having a liittle issue with my ubuntu so couldnt answer before thanks for understanding. I hope it clarifies

**Comment by surajvast1** [comment]
@sudhanshutech

**Review by vishalvivekm — APPROVED** [review]

**Comment by vishalvivekm** [comment]
Thanks a bunch @surajvast1.
The errors are gone :smile:

**Comment by surajvast1** [comment]
Thanks @vishalvivekm means a lot 😄

**Pull request merged**
