### PR TITLE
[Docs] Update the getting started Helm steps

### LINKED ISSUE #840: [Docs] Update the getting started Helm steps
**Current State:**
image

**Desired State:**
update the helm getting started state to be :

```
kubectl create ns meshery
helm repo add meshery https://meshery.io/charts
helm install meshery-operator meshery/meshery-operator -n meshery 
helm install meshery meshery/meshery -n meshery
```

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by K0more**
**Description**

This PR fixes #840 

**Notes for Reviewers**
Added the command to fix for helm in getting started doc

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 
Signed-off-by: K0more <arch.phenon@gmail.com>

### CODE REVIEW

**Review by CyrineG — DISMISSED** [review]
LGTM! I don't think I have the permissions to get this merged so requesting @leecalcote 's review as well

**Comment by CyrineG** [comment]
@K0more can you edit the the copy to clipboard text to reflect the new changes too?
image

**Comment by K0more** [comment]
@CyrineG okay! just lmk the details.

**Comment by K0more** [comment]
@CyrineG I have updated the clipboard, could you review this for any suggestions.

**Comment by leecalcote** [comment]
FYI - @CyrineG is on leave for a day or two.

**Review by leecalcote — APPROVED** [review]
Beautiful, @K0more. Thank you. 👍

**Comment by leecalcote** [comment]
yay, @K0more! 🎈

**Pull request merged**
