### PR TITLE
[Docs] Updated the wrong links to new correct links in catalog page

### LINKED ISSUE #1600: [Docs] Broken link on catalog page
### Description
The link in the **help-modal** in the **Meshery UI** section is broken.

Steps to reproduce 
- Go to [catalog page](https://meshery.io/catalog)
- Click on **import any catalog item**
- In the Meshery UI section the link in the docs is broken.

In addition to this, in the **Meshery CLI** section the link in `docs` leads to a wrong page.

### Expected Behavior
- Link in the **Meshery UI** should lead to [this page](https://docs.meshery.io/guides/configuration-management/importing-apps#import-apps-using-meshery-ui).
- Link in the **Meshery CLI** should lead to [this page](https://docs.meshery.io/guides/configuration-management/importing-apps#import-apps-using-meshery-cli).

### Screenshot
Docs broken link in modal in catalog

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by ASK-03**
**Description**
This PR fixes #1600 

- Removed wrong link and added correct link in  **Meshery UI & Meshery CLI** modal on catalog page
- When clicked a new page is opened rather than redirecting the user

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by sudhanshutech — COMMENTED** [review]
why change in this file [.jekyll-metadata](https://github.com/meshery/meshery.io/pull/1605/files#diff-c202638828c25867d7bb694c1140ed73a4e64557fdf69737fad98f6f067a6244) for ?

**Comment by sudhanshutech** [comment]
remove unnecessary lint formatting, because its kind difficult to see the actual change

**Comment by ASK-03** [comment]
> why change in this file [.jekyll-metadata](https://github.com/meshery/meshery.io/pull/1605/files#diff-c202638828c25867d7bb694c1140ed73a4e64557fdf69737fad98f6f067a6244) for ?

It is changing whenever I modify the content of the files and execute the `make site` command.

**Comment by ASK-03** [comment]
> remove unnecessary lint formatting, because its kind difficult to see the actual change

Okay! I have made the changes. I will create the pull request shortly.

**Pull request closed without merging**
