### PR TITLE
Fix: blog page

### LINKED ISSUE #1712: [UI] Blog page
### Description
On the blog page, the page number, the next page, and the previous page action buttons should have proper spacing between them, rather than being directly connected to the footer.

### Expected Behavior
There should be proper spacing between the last line and the footer.

### Screenshots

Currently, it appears like this:

image

Expected:

image

### Environment:

 - OS: Windows
 - Browser: Chrome
 - Device: Desktop

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by psankhe28**
**Description**

This PR fixes #1712

Screenshot:
image

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — COMMENTED** [review]
Use flex, please.

**Comment by psankhe28** [comment]
I've made some changes involving flex. @leecalcote, could you please review them? If there are any mistakes or improvements needed, I'd appreciate your feedback. Thank you!

**Comment by vishalvivekm** [comment]
@psankhe28 
Let's discuss this on websites call today. I've added this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#).
Meeting details: https://meet.layer5.io

**Comment by psankhe28** [comment]
Due to DCO issue, I am closing this and opening a new PR. Sorry for the inconvenience.

Please find the new PR here: #

**Pull request closed without merging**
