### PR TITLE
Fixed The Repeated Call of Layer5 In the used By Section 

### PR DESCRIPTION
**Pull request by DarrenDsouza7273**
**Description**
Fixed The Repeated Call of Layer5 In the used By Section As discussed in the weekly meeting

This PR fixes #1152 

Before :-
image

With this PR changes :-
image

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by vishalvivekm — APPROVED** [review]
LGTM.
Thanks @DarrenDsouza7273

**Comment by DarrenDsouza7273** [comment]
@thisiskaransgit all the mentioned issues for the issue are fixed already in my pr

**Review by GaganpreetKaurKalsi — APPROVED** [review]
Good to merge 👍 Thanks @DarrenDsouza7273

**Comment by DarrenDsouza7273** [comment]
no worries @GaganpreetKaurKalsi

**Pull request merged**
