### PR TITLE
Fix: Issue #1373 [Improve Text Styling Of Integration Cards]

### LINKED ISSUE #1373: Improve Text Styling
### Current Behavior
Text is showing out of the box, which also looks very bad.

### Desired Behavior
The text should be inside the box

### Screenshots/Logs
image

### Environment

- Browser: Chrome 
- Host OS: Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by kituuu**
**Description**

This PR fixes #1373 

**Notes for Reviewers**
Suggest alternate/better approach if any.

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@kituuu will you update the PR title to be descriptive of the change?

**Comment by kituuu** [comment]
> @kituuu will you update the PR title to be descriptive of the change?

is it fine now?

**Review by abhijeetgauravm — COMMENTED** [review]
Currently the text color in Integration Card in meshery.io site we can see is
image
But now in preview text color is black and text also not looking properly indented.
image

**Review by GaganpreetKaurKalsi — CHANGES_REQUESTED** [review]
Hey @kituuu, 
the same point as @abhijeetgauravm.

Also the desired behaviour would be showing 3 dots(ellipses) in case the content is overflowing. The card can support 4 lines of content, therefore lets try clipping the text if it exceeds 4 lines (see image for reference)

Please take care of the font-weight and color as well. They should not change.


image

**Comment by kituuu** [comment]
> Hey @kituuu, 
> the same point as @abhijeetgauravm.
> 
> Also the desired behaviour would be showing 3 dots(ellipses) in case the content is overflowing. The card can support 4 lines of content, therefore lets try clipping the text if it exceeds 4 lines (see image for reference)
> 
> Please take care of the font-weight and color as well. They should not change.
> 
> 
> image
> 

Okie, got it. I will do the font weight and colour stuff. Can you tell me how to use both ellipsis and word break together. When I add word break, all the words break instead of ellipsis on the last word.

**Comment by GaganpreetKaurKalsi** [comment]
@kituuu, for truncating you can explore the `line-clamp` property in css

**Comment by kituuu** [comment]
> @kituuu, for truncating you can explore the `line-clamp` property in css

Can you check now, I have made the changes.

**Comment by Ghat0tkach** [comment]
Hi @kituuu 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Review by leecalcote — APPROVED** [review]
Thanks, @kituuu 👍

**Pull request merged**
