### PR TITLE
added single filtering

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chatterjee <speak2adi@gmail.com>

**Description**
Added single field filtering, haven't completed doing all pages yet still working on this PR. 
This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
From some reason the radio buttons are functioning, but not showing as unchecked. 

https://user-images.githubusercontent.com/7570704/148150150-88604fe7-b038-46c5-90be-c227fde61756.mov

**Comment by warunicorn19** [comment]
Yes @leecalcote I'm working on fixing that.

**Review by leecalcote — CHANGES_REQUESTED** [review]
Too redundant. Please use either layout, include, or single query multiple inner loops to avoid all this redundancy.

**Comment by warunicorn19** [comment]
@leecalcote could you please take another look?

**Comment by warunicorn19** [comment]
Let's merge for now @leecalcote we can again work on refactoring later on.

**Pull request merged**
