### PR TITLE
feat:added recognition programme blog

### PR DESCRIPTION
**Pull request by Ghat0tkach**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@Ghat0tkach 
Let's discuss it on the websites call.
Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

**Comment by leecalcote** [comment]
Unfortunately, this is a Layer5-centric post that I don't consider works over here. If you have written a follow up summary to the announcement that we discussed, that'd work well on layer5.io.

**Comment by Ghat0tkach** [comment]
Thanks for the feedback @leecalcote , will do it!

**Comment by leecalcote** [comment]
Thanks, @Ghat0tkach!

**Pull request merged**
