### PR TITLE
Enhanced The style of the Scrollbar.

### LINKED ISSUE #1067: [UI] Enhance the styling of the scroll bar
#### Current Behavior
The default scrollbar in the Edge browser does not meet the desired aesthetic standards, prompting the need to enhance its appearance through appropriate design measures.

#### Desired Behavior
Revamp the scroll bar by implementing a new design that aligns with the aesthetic requirements.

#### Implementation
Incorporate CSS properties for the scroll bar to ensure consistency in appearance across all browsers.

#### Mockups
image

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Gautam-666**
**Description**

This PR fixes #1067
Screenshot (23)
Screenshot (24)

**Notes for Reviewers**
Haven't tested the changes on Mac. 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [✅ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Gautam-666** [comment]
What should I do now to pass that DCO test??

**Comment by shadow0500** [comment]
@Gautam-666  you can try this https://github.com/apps/dco

**Review by Savio629 — COMMENTED** [review]
LGTM 👍

**Comment by Savio629** [comment]
I see you forgot to signoff
You can try running `git commit —amend —no-edit ---signoff` and then `git push --force-with-lease origin <yourbranchname>`

**Comment by Gautam-666** [comment]
> I see you forgot to signoff You can try running `git commit —amend —no-edit ---signoff` and then `git push --force-with-lease origin <yourbranchname>`

this is not working I tried to do this.

**Comment by Gautam-666** [comment]
Also if possible just check the scrollbar on a Mac device.

**Comment by Savio629** [comment]
You can check the changes for mac devices using this website: https://www.browserstack.com/test-on-safari-browser
Changes are not applied to mac devices but it looks good in it's default scrollbar...

**Comment by vishalvivekm** [comment]
@Gautam-666 Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by Gautam-666** [comment]
Creating a new pull req with DCO

**Pull request closed without merging**
