### PR TITLE
Fixed overflow issue 

### LINKED ISSUE #1332: Overflow issue on meshery/community page for specific width
### Description
Overflow issue on meshery/community page

### Slack Discussion: 
https://layer5io.slack.com/archives/C015QJKUMPU/p1690614669705379
### Screenshots

mesheryissue_720

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by aaronsgeorge**
**Description**
Fixed overflow issue  occuring at community.html

This PR fixes #1332

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by samyakshah3008 — APPROVED** [review]
Great work @aaronsgeorge 
Next time please attach some visual screenshots or videos to help reviewer for a good review. 
I have checked from the live deployed link and it seems to be working fine. 
Good to merge ✅

**Comment by aaronsgeorge** [comment]
Thank you , ill be using visuals of the changes that my code has made in the upcoming PRs

**Comment by Ghat0tkach** [comment]
hey @aaronsgeorge 


 Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by thisiskaransgit** [comment]
Thanks @aaronsgeorge, we'll be closing this PR since it has been incorporated by another one. But please remember, your contribution is valuable and makes a difference!

**Pull request closed without merging**
