### PR TITLE
Replace Community Guide Link

### LINKED ISSUE #1054: Invalid Community Guide
### Description
in home page under the section that contains community meetings and community calendar links ,the link for community Guide is redirected to a google docs link that is showing 'Sorry, the file you have requested has been deleted.', also to note the url for the google docs contains the edit slug in  it "https://docs.google.com/document/d/17OPtDE_rdnPQxmk2Kauhm3GwXF1R5dZ3Cj8qZLKdo5E/edit"

### Expected Behavior
The  link should be opening a valid Google docs file

### Screenshots
Screenshot from 2023-03-04 11-28-09

### Enviroment:
 - Browser:   Firefox

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by sai-prasad-1**
**Description**

This PR fixes #1054 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by GaganpreetKaurKalsi — APPROVED** [review]
Looks good 👍  Great work spotting error and fixing @sai-prasad-1

**Comment by GaganpreetKaurKalsi** [comment]
Another issue that I see, 
we can remove the href from `div.go-corner` as the `a.card` is already taking you to the page. Having href on div doesn't make sense and has no use.
image

Would you care to open an issue for the same, @sai-prasad-1? How about fixing it as well?

**Comment by sai-prasad-1** [comment]
> Another issue that I see, we can remove the href from `div.go-corner` as the `a.card` is already taking you to the page. Having href on div doesn't make sense and has no use. image
> 
> Would you care to open an issue for the same, @sai-prasad-1? How about fixing it as well?

Sure @GaganpreetKaurKalsi  , i would open an issue for the same

**Comment by sai-prasad-1** [comment]
> Another issue that I see, we can remove the href from `div.go-corner` as the `a.card` is already taking you to the page. Having href on div doesn't make sense and has no use. image
> 
> Would you care to open an issue for the same, @sai-prasad-1? How about fixing it as well?

okay @GaganpreetKaurKalsi , i will create a issue and fix the same

**Review by leecalcote — APPROVED** [review]

**Review by leecalcote — COMMENTED** [review]
I don't see a new issue created based on @GaganpreetKaurKalsi's feedback, @sai-prasad-1.

**Pull request merged**
