### PR TITLE
Changes made to the icons and text of all the catalogs

### PR DESCRIPTION
**Pull request by Anand-Theertha**
**Description**

The current design for the pattern and filter catalogs are right indented. This PR fixes this issue by making it more appealing. Refer to the screenshots below.

 Current Design:

before

Better Design:

alignment

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Anand-Theertha** [comment]
@leecalcote Do you think this is ready to merge? 😃

**Comment by leecalcote** [comment]
@meshery/meshery-site-contributors, what do you think?

**Comment by Anand-Theertha** [comment]
@Gaurav Chadha @Eeshaan Sawant @Krishna Gupta

**Comment by Anand-Theertha** [comment]
@Krishna2323 @eeshaanSA What do you guys think? 😄

**Comment by leecalcote** [comment]
I have yet to find that my opinion differ from @GaganpreetKaurKalsi’s perspective. Her review here
Is ideal.

**Comment by Krishna2323** [comment]
@Anand-Theertha, this works well but it's not the right way to center a item, for the bottom you should use percentage and you should set the left to 50% and add a property "transform: translateX(-50%)" , and pls try to use rem instead of px.

**Review by GaganpreetKaurKalsi — COMMENTED** [review]
That's a lot of pressure @leecalcote. I'll still take the risk to present my point of view.

That text which we are trying to align is kind of a serial number/id from what I can see or a unique-code, neither it is a heading nor a subheading or an important text that needs to be brought to focus. So having it in the centre makes me feel we are trying to bring it to attention which I guess we don't want. Having it align to corner, aligns it to the chip at the top pretty well. 

Although we can still improve the placement of the text. Below is the ideal alignment for me.
image


@leecalcote of-course you can disagree.

I see an issue with the title in here. In some cards the title is almost touching the card edge. We can try having some padding/margin between the title and the card edge and have ellipses in case text overflows with a tooltip to show the full title. Or we can even leave the tooltip, as we can see the full title in the modal content for that card.
image

Modal contents ain't fully responsive as well 
image

**Comment by GaganpreetKaurKalsi** [comment]
I see there's an open issue for title overflow already.

**Comment by leecalcote** [comment]
@GaganpreetKaurKalsi your analysis and suggested path forward in the first two points is spot on.

@gr455 can we stop publishing catalog content sans whitespace in their titles, pretty please? 🥺  // @harkiratsm @Revolyssup

**Review by leecalcote — APPROVED** [review]

**Review by leecalcote — CHANGES_REQUESTED** [review]
@Anand-Theertha there's a lot of good feedback in here from @Krishna2323 and @GaganpreetKaurKalsi. Will you be working to incorporate this feedback?

**Comment by Anand-Theertha** [comment]
Hello @leecalcote. Yeah! I'll try to do this the right way as Krishna suggested.

**Comment by Chadha93** [comment]
// @Anand-Theertha Merge conflicts?

**Comment by Anand-Theertha** [comment]
These are the changes that I have made on the master branch for another issue. How can I revert these changes to the ones made in the PR? // @Chadha93

**Comment by Chadha93** [comment]
@Anand-Theertha Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by leecalcote** [comment]
@Anand-Theertha merge conflict...

**Comment by Chadha93** [comment]
@Anand-Theertha Updates? Will you continue this PR? Some minor changes...

**Pull request closed without merging**
