### PR TITLE
Added meshery-design-embed extension to Meshery Extensions

### LINKED ISSUE #1890: [FEATURE] Add Meshmap Embedding Design feature on Extensions page
### Current Behavior

Currently, there is no extension card for the Meshmap embed design extension.
### Desired Behavior

Add an extension card for Meshmap embed design extension.
### Screenshots / Mockups

---
<h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Aviral0702**
**Description**

This PR fixes #1890 
Added Meshery design embed extension to meshery.io/extensions.

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ashparshp** [comment]
@Aviral0702, Thank you for your contribution! Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT). Please consider adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk) || [meeting link](https://meet.layer5.io/websites).

**Comment by vishalvivekm** [comment]
@Ashparshp 
We still  see nothing once clicking on the logo in the extension modal, would you make sure to have opened an issue on this?
image

**Comment by Ashparshp** [comment]
@vishalvivekm, https://github.com/meshery/meshery.io/issues/1883

**Comment by vishalvivekm** [comment]
> @vishalvivekm, #1883

Thanks.
I see @Aviral0702 has taken up the item. Do you have any update that you want to share today @Aviral0702 ? If yes, please add to agenda items.

**Pull request merged**
