### PR TITLE
Enhance the icon collection for Helm plugin

### PR DESCRIPTION
**Pull request by bhushan354**
**Description**

This PR fixes #
https://github.com/meshery/meshery.io/issues/1915

**Notes for Reviewers**
I have implemented the basic structure necessary to add the new extension on the meshery.io/extensions/ page. However, the content displayed in the pop-up still needs to be updated, and the light theme also requires modifications.

image

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@bhushan354 Thank you for your contribution!
Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Review by leecalcote — COMMENTED** [review]
What happens when the site visitor is using light mode?

**Comment by leecalcote** [comment]
> What happens when the site visitor is using light mode?

@bhushan354?

**Comment by bhushan354** [comment]
@leecalcote  I’m still working on it. Also, I wanted to ask why the changes I made to the code, like the UI updates, aren't reflecting on localhost.

**Comment by bhushan354** [comment]
i am having this problem from many days

**Comment by leecalcote** [comment]
Exclude —incremental and —livereload from your build command.

**Comment by bhushan354** [comment]
https://github.com/user-attachments/assets/23cf0965-2566-42d0-a6a5-ca5834861ae3

**Comment by bhushan354** [comment]
@leecalcote its working now and updating according to local changes , thanks for the help !!

**Comment by sudhanshutech** [comment]
@bhushan354 any updates?

**Comment by bhushan354** [comment]
@sudhanshutech someone has already added the helm plugin 
[Screencast from 2024-11-23 21-45-29.webm](https://github.com/user-attachments/assets/acf690db-d9ba-4240-800b-8aced2c47389)

**Comment by bhushan354** [comment]
@sudhanshutech  someone has already added the helm plugin extension 
https://meshery.io/extensions

**Pull request closed without merging**
