### PR TITLE
docs: fix typo in ./collections/_posts/2022-01-26-pipelining-service-…

### PR DESCRIPTION
**Pull request by suravshrestha**
**Description**

This PR fixes typo `specfications -> specifications`

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by abhijeetgauravm — APPROVED** [review]
Hey @suravshrestha its good practice to create an issue before making a direct PR. But no sweat LGTM!

**Comment by saurabh100ni** [comment]
Thanks for raising PR, Let's discuss this in the Website call today at 5:30 PM IST.
Please add this as your agenda in [Docs](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk)

**Review by Mohith234 — APPROVED** [review]
Thanks for the quick fix @suravshrestha, Yay 🎈!

A quick heads up - Please do create an issue before making a PR

**Comment by suravshrestha** [comment]
> Thanks for the quick fix @suravshrestha, Yay 🎈!
> 
> A quick heads up - Please do create an issue before making a PR

Thank you, @Mohith234 . I will create an issue before opening a pull request in the future.

**Review by vishalvivekm — APPROVED** [review]

**Pull request merged**
