### PR TITLE
small size thumbnail issue solved

### LINKED ISSUE #771: [Catalog] Small-sized video displayed
**Description**
Only a thumbnail of the video displays.

**Expected Behavior**
Full-sized video should display.

**Screenshots**
Screen Shot 2022-07-14 at 2 18 15 PM

**Enviroment:**
 - Browser: Safari

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by manikmmalhotra**
Signed-off-by: manikmmalhotra <manikmalhotra2113@gmail.com>

**Description**
small sized video solved also made the responsive design of video player issue solved

This PR fixes #771 
Screenshot from 2022-07-18 01-53-34

**Notes for Reviewers**
Always open for suggestions and improvements. Please point me out if anything should be added/corrected.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Ready for review @asubedy

**Review by asubedy — CHANGES_REQUESTED** [review]
@manikmmalhotra It seems like we are still facings same problem
https://user-images.githubusercontent.com/51183483/179986323-2ba9f003-f544-412c-88c2-2e8dda8a5d9a.mov

**Comment by manikmmalhotra** [comment]
@asubedy i got it , it's throwing the error when we run for the first time after that it's working, i'll fix this

**Comment by leecalcote** [comment]
@manikmmalhotra do you have access to Safari?

**Comment by manikmmalhotra** [comment]
> @manikmmalhotra do you have access to Safari?

yes @leecalcote just there's a issue in my os i was working on it now I'll solve it by tonight

**Comment by manikmmalhotra** [comment]
@asubedy @leecalcote sorry for the delay i had some issue in my local system, i've tried multiple things for this issue finally solved it, also i removed the link tag for this video component which was causing the video to go on full screen mode and couldn't get any workaround on this

**Review by warunicorn19 — APPROVED** [review]
LGTM! Thank you @manikmmalhotra

**Pull request merged**
