### PR TITLE
[Site] Updated Home Page 

### PR DESCRIPTION
**Pull request by NikhilSharma03**
**Description**
Updated the Home Page Section style as given in mockup design.

## Changes Made
- Updated Background color
- Updated NavBar Color
- Updated Buttons color
- Updated Image position
- Take care of responsiveness for smaller devices

## After Changes

Screenshot from 2021-07-03 13-24-10

Screenshot from 2021-07-03 13-24-14

Screenshot from 2021-07-03 13-25-22

## Notes for Reviewers

Let me know if there are any other changes we can make.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
@NikhilSharma03 have you also changed the logo of community bridge to LFX on this PR?

**Comment by leecalcote** [comment]
@NikhilSharma03 has done a nice job here. Tagging with `issue/willfix`

**Comment by Mr-DG-Wick** [comment]
What is the status on this one?

**Comment by warunicorn19** [comment]
@Mr-DG-Wick this PR is on hold for later, this is basically for dark mode on the website.

**Comment by Mr-DG-Wick** [comment]
Gotit 👍🏽

**Comment by Chadha93** [comment]
A great effort by @NikhilSharma03, @Mr-DG-Wick would you like to tie this off?

**Review by Chadha93 — COMMENTED** [review]
@warunicorn19 @YashKamboj are these changes still required? If not let's close the PR.

**Pull request closed without merging**
