### PR TITLE
[WIP] added more patterns 

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chatterjee <speak2adi@gmail.com>

**Description**
Refactored code, added more patterns. 
This PR fixes #

**Notes for Reviewers**
Still stuck on filtering. 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]

**Review by leecalcote — CHANGES_REQUESTED** [review]
This PR seems to include a change that has the video player modal exposed
Screen Shot 2021-12-23 at 2 49 48 PM
.

**Comment by warunicorn19** [comment]
That's weird🤔, I'll take a look.

**Comment by warunicorn19** [comment]
@leecalcote where are you getting this exactly? I don't see it
Screenshot 2021-12-23 at 3 54 32 PM
t

**Comment by warunicorn19** [comment]
Merging right now will make updates on another PR.

**Pull request merged**
