### PR TITLE
Issue 939 unwanted white background in bee icon

### PR DESCRIPTION
**Pull request by Musab1258**
**Description**

This pr fixes the white bacground that appears in the ebpf logo in the catalog page of the meshery website when in dark mode. 

This PR fixes #

fixes issue #939 

**Notes for Reviewers**

I created a new svg image of the ebpf logo and replaced the former one with it.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 
Videoes / Screenshots

Before

 
ebpf-before

After

ebpf-after

### CODE REVIEW

**Comment by Musab1258** [comment]
@leecalcote , I don't understand this, I always signed off on my commit, but DCO IS ALWAYS failing.

**Comment by Musab1258** [comment]
But, I will resolve the DCO issues.

**Comment by leecalcote** [comment]
Temp instructions here -https://github.com/meshery/meshery.io/pull/945/checks?check_run_id=10352071544
Permanent instructions in the contributing.md in meshery/meshery.

**Review by leecalcote — CHANGES_REQUESTED** [review]
@Musab1258, we need to retain the bee's colors, but just lose the background.

**Pull request closed without merging**
