### PR TITLE
integration card back text issue fixed  w/signoff

### LINKED ISSUE #1137: Integration name overflows or at the edge of card.
### Description
In the integration section, when we hover on icons that contains large text (3-4 words), it looks not so good. Please look at the below SS.

### Expected Behavior
Text Content must be inside the boundries of Integration Icon Card.

### Screenshots
Screenshot (53)
Look that Postgres Database(CrunchyData)
Screenshot (56)
Now, look into this, isn't it looks good?

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by eagerashwani**
**Description**

This PR fixes #1137

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by eagerashwani** [comment]
Hey @leecalcote , @GaganpreetKaurKalsi, @Chadha93, Please review my PR.

**Review by GaganpreetKaurKalsi — COMMENTED** [review]
Hey @eagerashwani, 
reducing the font-size makes the text hardly readable.

I would prefer increasing the card size to solve the overflowing issue. Let's wait for Lee and Gaurav, what they have to say.

**Comment by leecalcote** [comment]
Following on @GaganpreetKaurKalsi's suggestion, `text-overflow: ellipsis;` is a potential solution to both keep the font size legible and prevent integration names from spilling over their respective card.

**Comment by eagerashwani** [comment]
okay

**Comment by vishalvivekm** [comment]
@eagerashwani 
let's discuss your updates on websites call, add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) , if you would :)

**Comment by vishalvivekm** [comment]
@eagerashwani any update?

**Comment by thisiskaransgit** [comment]
Since the change was not going in the direction we intended, will have to close this PR, thank you for your efforts so far.

**Pull request closed without merging**
