### PR TITLE
Add search (filter) for an specific Integration on Homepage's Integrations section

### LINKED ISSUE #1798: Add search (filter) for an specific Integration on Homepage's Integrations section
### Current Behavior

On https://meshery.io/ homepage  a section displays all the integrations that the project supports.
### Desired Behavior

[meshery.io](http://meshery.io/)’s home page is in need of a search (filter) for site visitors who wish to search for a specific integration.<br>

### Screenshots / Mockups

Screenshot 2024-07-03 at 2 19 02 PM
---
<h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by shubhusion**
**Description**

This PR fixes #1798

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
Thank you for your contribution.
Let's discuss this on Websites' call. Adding this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit).

**Comment by vishalvivekm** [comment]
@shubhusion 
Please remove commits not related to this PR.

**Comment by shubhusion** [comment]
> @shubhusion Please remove commits not related to this PR.

@vishalvivekm commits not related to PR just appear here but there are no changes in the PR wrt to those commits. there is only 1 file change which is related to the PR.

**Review by leecalcote — CHANGES_REQUESTED** [review]
> > @shubhusion Please remove commits not related to this PR.
> 
> @vishalvivekm commits not related to PR just appear here but there are no changes in the PR wrt to those commits. It looks like a bug. there is only 1 file change which is related to the PR. Merging will only change the concerned file where changes are needed.

@shubhusion, again, remove extraneous commits. Sync your fork and branch with head on master. Your PR should only include your commits / commits pertinent to the PR at-hand.

**Pull request closed without merging**
