### PR TITLE
Hamburger Icon and MENU Label Visibility Bug

### PR DESCRIPTION
**Pull request by shaikahmadnawaz**
**Title**

**Description**

This PR addresses issue #1104 

The current implementation of the footer in production uses "/stellarnav.min.js", which causes issues with visibility of the MENU label. This PR modifies the environment conditional in the "footer.html" file to use "/js/stellarnav.js" instead. Alternatively, we can make `menuLabel: ""` from the "/stellarnav.min.js" file before this PR merge, which would also resolve the issue.

After merging this PR, the navbar will look like the screenshot attached:

Screenshot (608)

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ x ] Yes, I signed my commits.

### CODE REVIEW

**Comment by shaikahmadnawaz** [comment]
Check this PR once @GaganpreetKaurKalsi

**Comment by GaganpreetKaurKalsi** [comment]
> Check this PR once @GaganpreetKaurKalsi

Yeah, works. Great 👍

**Review by GaganpreetKaurKalsi — APPROVED** [review]
LGTM 👍

**Comment by shaikahmadnawaz** [comment]
> > Check this PR once @GaganpreetKaurKalsi
> 
> Yeah, works. Great 👍 

Thank you 😊

**Comment by leecalcote** [comment]
@GaganpreetKaurKalsi in light your recent changes in this area is this update still desired?

**Comment by GaganpreetKaurKalsi** [comment]
> @GaganpreetKaurKalsi in light your recent changes in this area is this update still desired?

Yes @leecalcote, this PR is related to "Menu" text visible beside Hamburger icon in deployed Meshery site.
This is still a valid PR.

**Pull request closed without merging**
