### PR TITLE
Fixing issue#562 in repo meshery.io w/signoff

### LINKED ISSUE #562: Button in a Button Again
**Description**
I think someone has edited the div of the button or the button and the classes applied to different pages are facing this button in a button issue. 

**Expected Behavior**
Currently only this page buttons needs to be updated asap.

**Screenshots**

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by AndrewArnita**
Signed-off-by: Andrew <andrew_arnita@hotmail.com>

**Description**

This PR fixes #562 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by AndrewArnita** [comment]
@warunicorn19, everything is working now! Please if you can check it :)

**Review by warunicorn19 — APPROVED** [review]
LGTM🎉, Thanks @AndrewArnita

**Review by leecalcote — APPROVED** [review]
Good stuff, @AndrewArnita 👍

**Comment by leecalcote** [comment]
Yay, @AndrewArnita! 🎈

**Pull request merged**
