### PR TITLE
[Site] Community forum  updated

### LINKED ISSUE #492: [UI] Need some modifications
**Current State of the Meshery.io site**
Modification relates to `mobile view` in general:
1. [x] Needs to add Community Forum point at appropriate section [Community]
2. [ ] Alignment of `Created by LAYER5 and it's open source community` needs to set, i.e, flexible to current state - G
3. [ ] Horizontally footer content must be vertical represent - A
4. [ ] Menu issue - H

**Current State of the Meshery.io site**

 </br>
----
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

### PR DESCRIPTION
**Pull request by amino19**
**Description**
Added: Needs to add Community Forum point at appropriate section [Community]

This PR fixes #492 

**Notes for Reviewers**
Tasks have to divided at different Pull Requests. 
Ready to merge! :slightly_smiling_face: 

**Preview:** (Point 4)
image

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
@amino19 Do you mind fixing all the issues related to #492 in this PR itself, so it will be a bit more towards the heavier side 👀

**Review by adithyaakrishna — CHANGES_REQUESTED** [review]
@amino19 Instead of this one single change itself, I hope it would be fine with you to fix all the issues related to https://github.com/meshery/meshery.io/issues/492 in this PR itself

**Comment by amino19** [comment]
@adithyaakrishna : Yes obv, on it! 
Pl merge this, so I can move next! :rocket:

**Comment by leecalcote** [comment]
@amino19 if this PR is a partial fix, you'll want to update this text in the description:

```
This PR fixes #492
```
so that GH doesn't auto-close that issue upon merge of this PR.

**Review by leecalcote — APPROVED** [review]
Looking good.

**Pull request merged**
