### PR TITLE
[Mailing List] Make all the items width equal.

### LINKED ISSUE #868: [Mailing List] Make all the items width equal.
#### Description

It looks odd currently.

image

#### Expected Behavior

All of the widths should be same.
#### Environment:
- Host OS: 
- Browser: 

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by tinniaru3005**
Signed-off-by: Arunima Chaudhuri <tinniarunima66@gmail.com>

**Description**

This PR fixes #868 
Closes #868 

**Notes for Review
meshery
ers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by tinniaru3005** [comment]
Hey @legendarykamal, Can you plaese review the changes. By mistake I uncommitted the changes of the previous PR. Hence it was close. So, can you please look at the changes and approve them?

**Comment by leecalcote** [comment]
Looking good, @tinniaru3005

**Review by legendarykamal — APPROVED** [review]
LGTM 👍

**Comment by Nikhil-Ladha** [comment]
The buttons are still not of identical width.
Screenshot from 2022-10-16 14-01-11
Screenshot from 2022-10-16 14-01-28

Instead of adjusting the padding for each button, keep the padding the same for all of them and adjust other CSS properties like `display`, and `min-width`. And, set the `width: auto`, `margin:auto` to the parent `p` element.

**Comment by tinniaru3005** [comment]
hey @Nikhil-Ladha, are the changes fine now?
meshery io width same

**Comment by tinniaru3005** [comment]
Hey @Nikhil-Ladha, are the changes fine now?

**Comment by Nikhil-Ladha** [comment]
The text is not center aligned, please fix that.
Also, you will have to use `min-width` (probably 8rem) for `a` else, the button width won't remain the same for all of them.

**Pull request closed without merging**
