### PR TITLE
[UI]: Meshery extension catalog modal image height fix

### LINKED ISSUE #1881: [UI]: Center align images inside Card Modal of extensions page
### Description

When the Card in https://meshery.io/extensions page is clicked and the modal opens, the image is not center aligned.

### Expected Behavior

All images inside the card modal must be center aligned .

### Screenshots

image
image
image

### Environment:
 - OS: Mac
 - Browser: Chrome 
 - Version: 
 - Device: Desktop 

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by SAHU-01**
**Description**

This PR fixes #1881

**Notes for Reviewers**
I've resolved this by adding a `height:100%` to the image tag CSS

image
image

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by amitamrutiya — DISMISSED** [review]

**Review by Ashparshp — APPROVED** [review]
Thank you @SAHU-01.

**Review by sudhanshutech — COMMENTED** [review]
@SAHU-01 few snapshots images is streched out . Is this due to this change? I think yes!
image

**Comment by SAHU-01** [comment]
> @SAHU-01 few snapshots images is streched out . Is this due to this change? I think yes! image

Yes, I'll check these and fix it!
Thank you for highlighting the same.

**Review by sudhanshutech — CHANGES_REQUESTED** [review]
@SAHU-01 will you remove the unnecessary added lines , the lint changes.

**Comment by SAHU-01** [comment]
Sure I'll get rid of the linting changes.

**Comment by Ashparshp** [comment]
@SAHU-01, just a reminder in case you missed this.

**Comment by vishalvivekm** [comment]
@SAHU-01 ?

**Comment by SAHU-01** [comment]
@vishalvivekm thank you for highlighting this, I'll remove the unecessary linting changes .

**Pull request closed without merging**
