### PR TITLE
feat : Fixing installation instructions

### LINKED ISSUE #1279: Installation instructions needs to be updated
#### Current State of the Meshery.io site
Under the getting started section, the steps mentioned to install Meshery on various platforms haven't been updated.
#### Desired State of the Meshery.io site
- The Commands need to be updated with the reference to installation instructions provided in Meshery docs.

1. Commands for Docker and Kubernetes are utilizing mesheryctl by creating a new platform context
**Example**:  
 `mesheryctl system context create docker --platform docker --set `. and `mesheryctl system start`
This should be changed to use the curl command and download directly package
**Example**: 
 `curl -L https://meshery.io/install | PLATFORM=kubernetes bash - `, 
 We are practicing it under installation through bash but not in the concerned section.

2. Under KinD installation removing the option of using manifest for installation

3. update the GKE installation command to include --token flag, for automatic configuration (one-line instruction on how to get the token will be helpful)
- The link to directly download the CLI manifest, should be removed.

Link: https://docs.meshery.io/installation

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Ghat0tkach**
**Description**

This PR fixes #1279 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @Ghat0tkach.

1. Please note that point #1 in https://github.com/meshery/meshery.io/issues/1279 can be ignored.
1. KinD can be deleted as it is one in the same as Helm and doesn’t need a special callout unless there is something unique to KinD to account for.

**Comment by Ghat0tkach** [comment]
I have commented out 
KinD rather than deleting it completely

**Comment by sudhanshutech** [comment]
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Review by thisiskaransgit — APPROVED** [review]
@Ghat0tkach  Looks good to merge tada:

**Pull request merged**
