### PR TITLE
updated dark mode styling for programs page and updated navbar styling

### LINKED ISSUE #994: Text is not visible on every page of programs (i.e change its color in dark mode)
### Description

Text is not visible on every page of programs (i.e change its color in dark mode) 
[Link](https://meshery.io/programs)

### Expected Behavior

The text should be visible in dark mode.

### Screenshots

Now:
image

Desired:
image

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Avi-88**
The PR updates the programs page background and text to be dark mode compatible

This PR fixes #994 

**Notes for Reviewers**

The styling of navbar has been slightly changed, I have checked it across multiple pages and removed margin where it was being used. In case there are places where the styles need to be updated do let me know and I'll fix it asap. Also I have made changes in the youtube iframe card embedded in the programs to be responsive as it was breaking in certain places. 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Looking really good @Avi-88 .
Though, while you are there could you please update the content (list of names) under "Program Maintainers" to be a `ul, li`?

**Comment by Avi-88** [comment]
> Looking really good @Avi-88 . Though, while you are there could you please update the content (list of names) under "Program Maintainers" to be a `ul, li`?

On it , thanks for the feedback

**Comment by Avi-88** [comment]
@Nikhil-Ladha , I've made the necessary changes. Please let me know if there  are any issues , thanks

**Comment by Nikhil-Ladha** [comment]
I think you might have rebased the branch incorrectly, which has caused to have unintended changeset in the PR. Please fix that.

**Comment by Avi-88** [comment]
> I think you might have rebased the branch incorrectly, which has caused to have unintended changeset in the PR. Please fix that.

I'm really sorry about that, I should've cross checked before pushing. I've made a new [PR](https://github.com/meshery/meshery.io/pull/1033) with only the intended changes, please have a look at that. Extremely sorry for the inconvinience.

**Pull request closed without merging**
