### PR TITLE
Fixed Copy URL button visibility with better UX.

### LINKED ISSUE #1000: Copy to clipboard button not visible
### Description

The Copy to clipboard is not visible on https://meshery.io/catalog page items.

### Expected Behavior

The button should be visible and working properly.

### Screenshots

https://user-images.githubusercontent.com/66985303/215340454-6bf60be2-957a-453a-91e8-312318d4f842.mov

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by chinu-anand**
Signed-off-by: Chinu Anand <chinuanand81@gmail.com>

**Description**

This PR fixes #1000 

**Notes for Reviewers**
I prettified some files that's why there are a bit more no. of changes.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Yashsharma1911 — COMMENTED** [review]
Hey @chinu-anand nice work I have a suggestion can you remove those extra space and format changes it just makes it hard to review the real changes

**Comment by Yashsharma1911** [comment]
On clicking on the `Copy URL` button it is shrinking and I think it should not shrink on click 

https://user-images.githubusercontent.com/71271069/216156726-697734a3-a57b-4abe-96cd-1472dbf6852a.mov

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks, @chinu-anand. This works. 

Will you please remove all other changes to lines other than those pertinent to facilitating the "copied" message?

**Review by leecalcote — CHANGES_REQUESTED** [review]
@chinu-anand it's quite difficult to review meaningful changes when they are intermixed and buried with a slew of non-meaningful changes. Will you please only include line changes pertinent to the issue at-hand? Disable your formatter, perhaps.

My other question above has gone unaddressed.

**Comment by chinu-anand** [comment]
@leecalcote I reverted all the "formatting" changes and did a new commit which only changes the lines of code relevant to the button issue. At my side the file changes in this PR is showing what exactly it should be. 🤔

**Comment by leecalcote** [comment]
> This PR fixes https://github.com/meshery/meshery.io/issues/1000

💥 💥

**Comment by leecalcote** [comment]
> Hey @chinu-anand nice work I have a suggestion can you remove those extra space and format changes it just makes it hard to review the real changes

Ha! I'm just now seeing this.

**Pull request closed without merging**
