### PR TITLE
[Site] Update Program Page -w/signoff

### PR DESCRIPTION
**Pull request by NikhilSharma03**
Signed-off-by: Nikhil Sharma <nikhilsharmamusic2000@gmail.com>

**Description**
The program page was a bit hideous so made some changes related to that.

## After Changes
Screenshot from 2021-07-11 17-16-19

Screenshot from 2021-07-11 17-16-28

Screenshot from 2021-07-11 17-16-34

**Notes for Reviewers**
- Let me know if there are any other changes we can make.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by NikhilSharma03** [comment]
@leecalcote Need help here.

**Comment by leecalcote** [comment]
We might have to get a design together. In the meantime, heads-up: there is a mobile responsive issue or two on this programs page.

**Comment by NikhilSharma03** [comment]
> We might have to get a design together. In the meantime, heads-up: there is a mobile responsive issue or two on this programs page.

Yup almost complete.

**Comment by leecalcote** [comment]
@NikhilSharma03 good stuff here. 👍

**Pull request merged**
