### PR TITLE
Install instructions for Docker Extension for meshery

### LINKED ISSUE #702: Add install instructions for Docker Extension for Meshery
#### Current State
A Docker Extension for Meshery has been created and will be publicly available at DockerCon 2022.  A description of the extension and how to install it are needed. See https://layer5.io/docker-extension-meshery and https://hub.docker.com/r/meshery/docker-extension-meshery for details.

Screen Shot 2022-05-03 at 5 49 53 PM

#### Desired State
Add Docker Extension as a second option in the Docker deployment instructions.

```
docker extension install meshery/docker-extension-meshery:stable-latest
```

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)
---
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by karnatisrinivas**
Signed-off-by: Srinivas karnati <karnatisrinivasulareddy@gmail.com>

**Description**

This PR fixes #702

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by YashKamboj — DISMISSED** [review]
LGTM!!!, Great Work

**Comment by Akshit42-hue** [comment]
Hey @karnatisrinivas, there is a small bug when I click on (copy to clipboard) in "Use Docker Extension for Meshery"
the "Use mesheryctl" command gets copy can you please do have a look

**Review by Akshit42-hue — CHANGES_REQUESTED** [review]
Update (data-clipboard-text)

**Comment by karnatisrinivas** [comment]
Thank you @Akshit42-hue  for bringing this up. I made changes to the clipboard text , would you please check now.

**Review by Akshit42-hue — APPROVED** [review]
LGTM, Great work @karnatisrinivas

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
