### PR TITLE
Updated the incorrect link inside PR template

### LINKED ISSUE #1300: incorrect links inside pull request template
### Description
The path inside [pull request template](https://github.com/meshery/meshery.io/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1) for signed in comments is incorrect.  Currently it is directing to **Not Found** page. 
```
**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
```

### Expected Behavior
It should be: 
```
**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
```
### Enviroment:
 - OS:  Linux 
 - Browser: Brave
 - Version: 
 - Device: Desktop 

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Debjyoti0404**
**Description**
Updated the link inside pull request template which was incorrect.
This PR fixes #1300 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
@Debjyoti0404 
Let's discuss it on the websites call.
Add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

**Comment by Debjyoti0404** [comment]
> @Debjyoti0404 Let's discuss it on the websites call. Add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima), if you would :)

Sure!

**Review by thisiskaransgit — APPROVED** [review]
@Debjyoti0404, thanks for this quick fix, looks good to merge 🚀

**Review by HarshDobariya79 — APPROVED** [review]
Nice work @Debjyoti0404. Looks good to merge.

**Review by leecalcote — COMMENTED** [review]
Thank you, @Debjyoti0404, @HarshDobariya79 @thisiskaransgit

**Pull request merged**
