### PR TITLE
Most Popular discussions posts

### PR DESCRIPTION
**Pull request by kayceeDev**
**Description**

This PR integrates the most popular discussions from the [discuss forum](https://discuss.layer5.io)

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@asubedy what do you think?

**Comment by asubedy** [comment]
@kayceeDev are we using the same json file for popular post and reset post?

**Comment by kayceeDev** [comment]
> @kayceeDev are we using the same json file for popular post and reset post?

Yes. It has same data. I am just sorted them on number of views.

**Comment by asubedy** [comment]
> > @kayceeDev are we using the same json file for popular post and reset post?
> 
> Yes. It has same data. I am just sorted them on number of views.

I think this should not be the case since the overall popular post could be different from the popular post from the recent topics

**Comment by kayceeDev** [comment]
> > > @kayceeDev are we using the same json file for popular post and reset post?
> > 
> > 
> > Yes. It has same data. I am just sorted them on number of views.
> 
> I think this should not be the case since the overall popular post could be different from the popular post from the recent topics

I think it's same API for posts. Not like different API's for posts.

**Comment by leecalcote** [comment]
So long as the objective is "the most popular posts (by like) with 'meshery' tag", then we're ok. But, if it's not with 'meshery' tag, then, we're misrepresenting.

**Comment by leecalcote** [comment]
Good deal. Ping when you've made your final update. 👍

**Pull request merged**
