### PR TITLE
Add back to top button in README.md file #1486

### LINKED ISSUE #1486: [Docs]:  Back-to-Top Button in README
### Current State:
image

### Desired State:
image

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by Aseem22**
**Description**

This PR fixes #1486

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by saurabh100ni** [comment]
Hi @Aseem22   ,
Thanks for your PR! I encourage you to share this in the Website Meeting tomorrow at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Comment by leecalcote** [comment]
@Aseem22 be sure to sign your commits. See these instructions https://github.com/meshery/meshery.io/pull/1579/checks?check_run_id=20452343888

**Comment by sudhanshutech** [comment]
@iArchitSharma is this required? If so can test this can move us forward here.
@Aseem22 try not to force push and rebase commits, and can you send us a recording the working of it

**Review by iArchitSharma — APPROVED** [review]
LGTM!

**Comment by iArchitSharma** [comment]
@sudhanshutech its working

**Pull request merged**
