### PR TITLE
Image after changed successfully

### LINKED ISSUE #1580: [Website] enhance before and after screenshot
### Current Behavior
On the homepage, there is a before and after section. The after screenshot is not the best.

image

### Desired Behavior
Replace the after screenshot with a more intriguing version, like this one:

image

Crop the image as needed.

---
<h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by surajvast1**
**Description**

This PR fixes #1580

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by surajvast1** [comment]
gitops-snapshot

**Comment by saurabh100ni** [comment]
Hi @surajvast1  ,
Thanks for your PR! I encourage you to share this in the Website Meeting tomorrow at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Review by sudhanshutech — COMMENTED** [review]
1. You have rebased your branch @surajvast1 this can be risky(it might take us few commits back)
2. Use designer view for the screenshot that is more appropriate
3. Remove the change of unused file `.jekyll-metadata`

**Comment by surajvast1** [comment]
Sure

**Pull request closed without merging**
