### PR TITLE
Fixed layout and alignment of components on Service Mesh Interface page

### LINKED ISSUE #1021: Adding Margin from Top to Bottom
### Current Behavior

WhatsApp Image 2023-02-13 at 8 41 55 PM

### Desired Behavior
Adding Margin from top to bottom to improve UI  
image

### link :-https://meshery.io/service-mesh-interface
---
<h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and designs for Meshery Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Savio629**
**Description**
Fixed layout and alignment of components on Service Mesh Interface page

- Added margin to legend elements
- Text and icon aligned
- Removed the table div from the scrollable layout

This PR fixes #1021

**Notes for Reviewers**

https://user-images.githubusercontent.com/91362589/232553941-1ef960f7-2e4b-44ca-8cc2-5113d92f88f6.mp4

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Savio629** [comment]
@vishalvivekm @Avi-88 Can you review the pr?

**Comment by Avi-88** [comment]
LGTM, good work @Savio629 :) Just one think I want to discuss is the positioning of the legend on smaller screens. I think it would look better if centered or completely to the right, right now its weirdly positioned (neither fully centered nor fully to the right), let me know what you think about this

**Comment by Savio629** [comment]
> LGTM, good work @Savio629 :) Just one think I want to discuss is the positioning of the legend on smaller screens. I think it would look better if centered or completely to the right, right now its weirdly positioned (neither fully centered nor fully to the right), let me know what you think about this

@Avi-88 I feel it would look better either way. The legend is right aligned for windows so it can follow the same but center aligned looks better for smaller devices.

- Does the legend supposed to be gray on light mode?
- Also from 770 width to 900 width, the text inside the legend becomes thinner. Was it supposed to behave like that?

**Comment by Savio629** [comment]
@Avi-88 
Which one looks better?
I feel the second one (right aligned) looks better...

check1


check2

**Comment by Avi-88** [comment]
Yeah, I agree the right aligned looks better :)

**Comment by Savio629** [comment]
@Avi-88 Done 👍

**Review by Avi-88 — APPROVED** [review]
LGTM, good work @Savio629 :)

**Comment by leecalcote** [comment]
Thank you, gents.

**Pull request merged**
