### PR TITLE
Homepage features section converted to Liquid templates

### LINKED ISSUE #1370: Utilize Liquid templates for feature sections on the homepage
### Current Behavior
Currently, the feature sections on the homepage of meshery.io are hardcoded in HTML, which makes it challenging to update or maintain them efficiently.

### Desired Behavior
 To enhance flexibility and ease of maintenance, it is recommended to transition to Liquid templates for rendering the feature sections dynamically on the homepage. The features sections should be moved in the includes directory and are used as liquid templates.

### Screenshots / Mockups

---
<h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by RavindraP04**
**Description**

This PR fixes #1370 

**Notes for Reviewers**

I have converted Features section in the Homepage of Meshery.io website from Hard coded HTML code to Liquid templates
- deleted two features files `grpc.html` from features folder inside `_includes` and `patterns.html` from partials folder 
- moved the features HTML code from `home-page.html` to a new file `features.html` inside `_includes` folder and imported features.html to home-page.html.
- added a `features.yml` in the `_data` folder where all the variables are stored for the liquid template and these variables are used in `features.html` file

Now if anyone wants to add a new feature or Update any feature in the homepage section, it can be easily done by adding a new type in the yml file and importing the variables in the `features.html` so now its more organized

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by RavindraP04** [comment]
@vishalvivekm Please review this PR and do let me know if I can improve anything

**Comment by Ghat0tkach** [comment]
@RavindraP04 

Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by leecalcote** [comment]
@RavindraP04 thanks for this.

Will you have a look at the merge conflict here?

**Comment by RavindraP04** [comment]
> @RavindraP04 thanks for this.
> 
> Will you have a look at the merge conflict here?

Updated, I guess, now its resolved

**Review by leecalcote — APPROVED** [review]
Thanks for helping get the site organized, @RavindraP04 💯 Good stuff inside this PR. 👏

**Comment by leecalcote** [comment]
Whoo-hoo, @RavindraP04! 🎈

**Pull request merged**
