### PR TITLE
feat: fix issues on blog page

### LINKED ISSUE #1551: [Blog] Missing image and tags responsiveness
### Description

- [x] In [meshery/blog](https://meshery.io/blog/page/2/) the image is missing for the blog.
- [ ] The tags are not looking good for smaller screens

### Screenshots
Screenshot for both missing image and responsiveness issue of tags
Screenshot 2023-12-21 181430

### Expected Behavior
The images should be visible along with the tags to have flex-column for smaller screens.
image

### Enviroment:
 - OS: Windows
 - Browser: Chrome 
 - Version: 
 - Device: Desktop & Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by ashutosh-rath02**
**Description**

This PR fixes #1551 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by ashutosh-rath02** [comment]
@sudhanshutech please check. And the overflow you suggested, I wasn't able to reproduce them but I have fixed the issue of authors placement

**Comment by saurabh100ni** [comment]
Hi @ashutosh-rath02  ,
Thanks for your PR! I encourage you to share this in the Website Meeting tomorrow at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

**Comment by sudhanshutech** [comment]
@ashutosh-rath02 
image

**Comment by ashutosh-rath02** [comment]
image
@sudhanshutech it seems overflow for medium screens is due to the navbar, I have fixed the overflow of smaller screens it was due to the images.

**Comment by sudhanshutech** [comment]
In that case @vishalvivekm @iArchitSharma @Yashsharma1911 will look over it

**Comment by ashutosh-rath02** [comment]
@sudhanshutech please check

**Review by iArchitSharma — APPROVED** [review]
Thanks LGTM!

**Pull request merged**
