### PR TITLE
[Epic] 3-D Integrations page creation

### PR DESCRIPTION
**Pull request by legendarykamal**
**Description**
Users can switch between table, helix , grid  and sphere mode.

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by legendarykamal** [comment]
@GaganpreetKaurKalsi i think we will have to find another way to integrate instead of build files , its not deploying strangely please check preview.

**Comment by GaganpreetKaurKalsi** [comment]
> @GaganpreetKaurKalsi i think we will have to find another way to integrate instead of build files , its not deploying strangely please check preview.

Yes yes, it's failing to load resources. Will look into it.

**Comment by GaganpreetKaurKalsi** [comment]
Did my best! Integrated the helix onto the homepage. Have a look and let me know.

Tough work, phew!!!
@leecalcote

**Comment by Chadha93** [comment]
@Krishna2323

**Comment by GaganpreetKaurKalsi** [comment]
Hey @legendarykamal, could you move this PR from **Draft** to **Ready**.

**Comment by legendarykamal** [comment]
ya sure @GaganpreetKaurKalsi , done 👍  .
Sorry , I would done some work here to assist you but exams have kept me wrangled . 

Nevertheless , Good work from you here I see 🥇 Kudos

**Comment by GaganpreetKaurKalsi** [comment]
> ya sure @GaganpreetKaurKalsi , done 👍 . Sorry , I would done some work here to assist you but exams have kept me wrangled .
> 
> Nevertheless , Good work from you here I see 🥇 Kudos

No issues Kamal! Mine are going as well. 
It was great working on this feature. Thanks!

**Comment by leecalcote** [comment]
Exams. 😠 Who needs those darn things anyway?

**Comment by leecalcote** [comment]
Users' scrollwheels still get stuck inside of this section. Their scrollwheel is taken captive and prevented from continued to scroll to the next section of the site. Let's try not capturing their wheel (not activating the zoom in/zoom out) until the user clicks on the integrations section. Before they click, let's have a small sign/notice posted indicating that they can click to interactively navigate the 3D listing of all integrations.

**Comment by leecalcote** [comment]
I have added a follow up issue to ensure that scrollwheels aren't unintentionally taken hostage - https://github.com/meshery/meshery.io/issues/901

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Pretty awesome work here, @GaganpreetKaurKalsi, @legendarykamal.

**Pull request merged**
