### PR TITLE
Updated  getting-started.html  issue #517 fixed

### LINKED ISSUE #517: Copy text gets hidden
**Description**
In the Getting Started portion of the website, the tooltip for the copy clipboard is getting cut off

**Expected Behavior**
The complete tooltip should be visible.

**Screenshots**

https://user-images.githubusercontent.com/53532328/129491907-3d9fc663-6192-4ba4-ae04-63d37ffe0d6a.mov

**Enviroment:**
 - OS: MacOs
 - Browser:  Chrome, Safari
 

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by ANURAG-PATHAK**
**Description**

This PR fixes #517 

**Notes for Reviewers**

I updated meshery.io/_includes/getting-started.html 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
@ANURAG-PATHAK you would have to signoff your PRs otherwise the DCO will fail.
Try following this-
https://github.com/meshery/meshery.io/pull/519/checks?check_run_id=3379227671

**Comment by ANURAG-PATHAK** [comment]
> @ANURAG-PATHAK you would have to signoff your PRs otherwise the DCO will fail.
> Try following this-
> https://github.com/meshery/meshery.io/pull/519/checks?check_run_id=3379227671

Okay I will add another PR by fixing DCO

**Comment by warunicorn19** [comment]
@Jashpatel1 @sayantan1413 any idea why these builds are failing?🤔 Im not being able to figure it out

**Comment by leecalcote** [comment]
> @Jashpatel1 @sayantan1413 any idea why these builds are failing?🤔 Im not being able to figure it out

The whitespace in the filename that Anurag pushed.

**Comment by ANURAG-PATHAK** [comment]
> @Jashpatel1 @sayantan1413 any idea why these builds are failing?🤔 Im not being able to figure it out

I did not updated the Gemfile.lock the `ffi (1.13.1)` was this and it should be updated for successful build 
then in the new PR I updated Gemfile.lock 
old content : `ffi (1.13.1)`
new content : `ffi (1.15.3)`
and therefore ffi was updated in the gemfile now the build was successful 

# that's just my guess I am not very much confident about my answer

**Pull request closed without merging**
