### PR TITLE
[Catalog] Generate Model for Azure Architectural Icons

### LINKED ISSUE #1911: [Catalog] Generate Model for Azure architectural icons
# Extending Meshery Models

Meshery as an extensible platform allows users to import, generate and export models that are either annotation (SVGs) or infrastructure configuration (CRDs).
Create a new model with the following specifications:

**Model:** 
**Model Display Name:** 
**Model Resources:** 

Then list the model on [](meshery.io/models) by raising a PR.

### Contributor Resources

- The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](https://slack.meshery.io/) for access.
- See how to [import](https://docs.meshery.io/guides/configuration-management/importing-models), [generate](https://docs.meshery.io/guides/configuration-management/generating-models) and [export](https://docs.meshery.io/guides/configuration-management/exporting-models) models.
- Link to [CSV template](https://docs.google.com/spreadsheets/d/19JEpqvHrG8UL-Bc-An9UIcubf1NVhlfnQSN1TD7JOZ4/edit?gid=0#gid=0)
- See live demo on how to contribute to Meshery Models: https://www.youtube.com/live/iKe52yMWWK4?si=YL8gTRF7yndHQEyt&t=1494

### PR DESCRIPTION
**Pull request by TraXIcoN**
**Description**

This PR fixes #1911 

**Notes for Reviewers**
This pull request generates a new model for Azure architectural icons in the Meshery catalog, extending the Meshery Models feature. It includes annotations (SVGs) as per the issue requirements.

I placed the exported model file in the collections/_models folder. I was not sure about it so let me know if it isn't right, and I'll change it accordingly.

Model:
Model Display Name: Azure Architecture
Model Resources: https://learn.microsoft.com/en-us/azure/architecture/icons/

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by TraXIcoN** [comment]
@Jougan-0 When you get the time can you please review this PR? Thanks!

**Comment by leecalcote** [comment]
Looking good, @TraXIcoN! 💯

**Comment by leecalcote** [comment]
What the next model that you're working on, @TraXIcoN? Let's keep the momentum.

**Comment by TraXIcoN** [comment]
> What the next model that you're working on, @TraXIcoN? Let's keep the momentum.

Happy to work on more models! It was a fun task, and I really got to see how awesome mesheryctl is. I'll drop some ideas in Slack for more models, so others can jump in too!

**Comment by SAHU-01** [comment]
🙌 Thank you for this PR @TraXIcoN!
Now with reference to [#1923 ](https://github.com/meshery/meshery.io/issues/1923) to incorporate these as Azure models you need to :
- [ ] add the `svgColor` data inside `svgComplete`
- [ ] in the `styles` column set the  `background-opacity ` property to 0 and the `border-width` property to 0 

The rest of the steps would be the same , you just need to make these additions and we should be good.
Please feel free to reach out if you need any further clarification or assistance. 😊

**Comment by leecalcote** [comment]
@TraXIcoN are you progressing here?

**Comment by TraXIcoN** [comment]
Hey @leecalcote yeah, I just pushed the updated model. @SAHU-01 Can you please review it? Thanks!

**Comment by leecalcote** [comment]
Thanks, @TraXIcoN!

**Comment by leecalcote** [comment]
@SAHU-01 we're ready to incorporate this model as one of the out-of-the-box models in Meshery releases. Can you take next steps here?

**Pull request merged**
