### PR TITLE
Update community.html

### LINKED ISSUE #1397: Update Tutorials link reference
#### Current State of the Meshery.io site

On the [Community page](https://meshery.io/community/), under Resources section 'Tutorials' card points to https://layer5.io/learn.

#### Desired State of the Meshery.io site

It should point to Tutorials section [here 👇 ](https://meshery.io/talks-and-presentations):
Screenshot 2023-09-01 013408

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by nakulbh**
**Description**

This PR fixes #1397 

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Mohith234** [comment]
@nakulbh Do not create any PR unless you are assigned to that issue. Please read the contributing guidelines

OR else your PR will not be accepted

**Comment by rj2704** [comment]
Now, will this issue be assigned to someone else? If yes, then I want to work on this issue.

**Review by vishalvivekm — CHANGES_REQUESTED** [review]
@nakulbh 
We want to point to the Tutorials section on https://meshery.io/talks-and-presentations page and not the page itself

i.e. `https://meshery.io/talks-and-presentations#Tutorials`

**Comment by nakulbh** [comment]
> @nakulbh We want to point to the Tutorials section on https://meshery.io/talks-and-presentations page and not the page itself
> 
> i.e. `https://meshery.io/talks-and-presentations#Tutorials`

Done sir

**Comment by nakulbh** [comment]
> @nakulbh It's important to request assignment before starting work on an issue if there is no assignee.
> 
> Please go through the [contributing guidelines](https://layer5.io/community/handbook/contribution) and code of conduct outlined in the [community handbook](https://layer5.io/community/handbook). Also refer to https://layer5.io/community/handbook/faq to know how to approach working on issues within the community, I hope you'll keep these in mind for future.

Yes sir i will keep this in mind in future

**Review by vishalvivekm — APPROVED** [review]

**Pull request merged**
