### PR TITLE
Change background of the choose your platform section on homepage

### LINKED ISSUE #1735: Add a better background color to Choose your platform section on homepage
### Current Behavior
The background color of a section that comes up when you click on any of the platforms under the `Choose your platform` section is the same as that of the whole section. 
image

### Desired Behavior
Change the background color of that inner section that pops up

---
<h4>Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources</h4>

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by shailpujan88**
**Description**

This PR fixes #1735

**Notes for Reviewers**
Changed the background color of the Choose Your Platform section.

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by shailpujan88** [comment]
@ritiksaxena124 Sorry, the previous PR got closed accidentally while reverting the gemfile.lock. I've made the changes suggested by you. Can you please verify them and let me know if I've got to change anything?

**Comment by vishalvivekm** [comment]
@shailpujan88 Thank you for your contribution.
Let's discuss this on Websites's call on Monday. Add this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

**Comment by shailpujan88** [comment]
image

@ritiksaxena124  I have made the required changes. Can you please verify them?

**Review by leecalcote — COMMENTED** [review]
Nice work, @shailpujan88. 😄 

What different color might we use for light mode?

**Comment by shailpujan88** [comment]
Hey @leecalcote I changed the color keeping in mind about both the dark and light modes and this single color works for both the themes good enough enhancing the UX of the website. 
This is the color code(#393d41, #0c0d0d, #131313, #3d4042, #3c3e41)

image

**Comment by ritiksaxena124** [comment]
It looks good @shailpujan88 👏but I think we should use some gradient of white in light mode and a dark color gradient in dark mode. The gradient you used looks great in dark mode though 👍. // @Rexford74

**Pull request closed without merging**
