### PR TITLE
update calendar.html

### LINKED ISSUE #1228: Update calendar
### Description
Hii everyone, in desktop and mobile our calendar  is seems to be very awkward , the text inside dates are not proper and there is blue highlighter for text which is not matching idea .

### Expected Behavior
want to change this behaviour of calander , there should be like hover effecting or something else which can show our meeting content (edited) 

### Screenshots
image
image

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Rajivkumawat3**
**Description**

This PR fixes #1228 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ghat0tkach** [comment]
| Before| After |
| --- | ----------- |
| |  |
|  |  |

**Comment by Rajivkumawat3** [comment]
@Ghat0tkach visit site again and you will  see that after hover the title it will be fully visiable without overflow , i think it was only better option to see all the text

**Comment by Ghat0tkach** [comment]
> @Ghat0tkach visit site again and you will  see that after hover the title it will be fully visiable without overflow , i think it was only better option to see all the text . exactly , we can hover only one title at a time . if i will show all title at a time then it will unnecessary give a bigger size to calendar .  @Ghat0tkach please give any idea you have which is better than this .


I personally think it ll be better to implement this 
https://layer5.io/community/calendar
To maintain uniformity between layer5 and meshery. Any thoughts@Rajivkumawat3 ?

**Comment by Rajivkumawat3** [comment]
I think not a good idea because what you extra add is time, text still not visiable and your calendar have left and right scroll in mobile devices which is ackward . our main goal was the text which is not fully visiable , should be visiable before clicking on it . And before clicking the text user have to hover first and the text will be visiable accordingly ,simple. And user can see whole calendar in one view in all media devices

**Comment by vishalvivekm** [comment]
@Rajivkumawat3 Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by Rajivkumawat3** [comment]
ok

**Comment by Rajivkumawat3** [comment]
@vishalvivekm sir what color should i give in place of blue color in text title

**Comment by samyakshah3008** [comment]
@Rajivkumawat3  Let's discuss this on Websites Meeting call on Monday. Please add this as an agenda item in the [meeting mintes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would. :)

**Review by Chadha93 — APPROVED** [review]
Thanks gents, it's an improvement, let's move forward with this.

**Pull request merged**
