### PR TITLE
Added trademark in footer

### LINKED ISSUE #1622: Website does not have the correct trademark disclaimer
As part of our ongoing effort to https://github.com/cncf/techdocs/issues/198, we noticed that the website does not pass the trademark criteria on [CLOMonitor](https://clomonitor.io/search?foundation=cncf&not_passing_check=trademark_disclaimer&page=1).

To fix this:
Head to the source code of the website. In the `<footer>` section, add a **disclaimer** or **link** to the Linux foundation trademark disclaimer page:

**Disclaimer**
```
<footer>
   <p>The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, 
         please see our <a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademark Usage page</a>.
   </p>
</footer>
```

**Link**
```
 <footer>
      <ul>
          <li><a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademarks</a></li>
      </ul>
 </footer>
```

### PR DESCRIPTION
**Pull request by psankhe28**
**Description**

This PR fixes #1622

**Notes for Reviewers**

**[Signed commits](https://docs.meshery.io/project/contributing#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
Revert formatting and prettier changes, if you would. @psankhe28

**Comment by vishalvivekm** [comment]
@psankhe28  Let's discuss this on Websites's call. 
Add this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

**Comment by Rexford74** [comment]
Hey, Pratiksha. I've taken a look at the deployment. I think that just having the word 'Trademarks' there seems a little vague. Is it possible to have something like what is [implemented here](https://github.com/meshery/meshery.io/issues/1622#issuecomment-1915906541) as this has been confirmed to be the desired result by the issue raiser?
Then you can make the 'Trademarks Usage Page' a clickable link that leads to the usage webpage. Let me know what you think. Thanks.

**Comment by psankhe28** [comment]
> Hey, Pratiksha. I've taken a look at the deployment. I think that just having the word 'Trademarks' there seems a little vague. Is it possible to have something like what is [implemented here](https://github.com/meshery/meshery.io/issues/1622#issuecomment-1915906541) as this has been confirmed to be the desired result by the issue raiser? Then you can make the 'Trademarks Usage Page' a clickable link that leads to the usage webpage. Let me know what you think. Thanks.

In the Slack channel, I inquired about which implementation to pursue, and based on the suggestions, I was advised to implement the one you can observe in the pull request.

**Comment by Rexford74** [comment]
But it seems too vague. It says 'Trademarks' but doesn't specify for which solution, or that it is a disclaimer either. It just links people to the LFX usage page. I don't know that this is a better outcome than the one sampled in the initial issue. If it's possible, I'll also like to see the link to the conversation that you had on slack so that I can get a bit more insight on the conversation had.
That said, in the meantime, maybe we can merge this PR to allow traction then when more clarity is achieved, we can make improvements where necessary.

**Comment by psankhe28** [comment]
> But it seems too vague. It says 'Trademarks' but doesn't specify for which solution, or that it is a disclaimer either. It just links people to the LFX usage page. I don't know that this is a better outcome than the one sampled in the initial issue. If it's possible, I'll also like to see the link to the conversation that you had on slack so that I can get a bit more insight on the conversation had. That said, in the meantime, maybe we can merge this PR to allow for traction, then when more clarity is achieved, we can make improvements where necessary.

https://layer5io.slack.com/archives/C015QJKUMPU/p1714659786470789

**Comment by dragon-slayer875** [comment]
@Rexford74 @psankhe28  Do we have any updates here? :eyes:

**Comment by sudhanshutech** [comment]
I wonder do we require this trademark?
@psankhe28 are you still following up on this pr .

**Comment by iArchitSharma** [comment]
I don't think we need this @sudhanshutech 
@vishalvivekm ??

**Comment by sudhanshutech** [comment]
lets close this pr for now also Pratiksha is not responding so we will plan over it later. Thank you folks.

**Pull request closed without merging**
