### PR TITLE
"Join the community" button on /calendar page is not visible properly

### PR DESCRIPTION
**Pull request by YashKamboj**
Signed-off-by: YashKamboj <75125203+YashKamboj@users.noreply.github.com>

**Description**"Join the community" button on /calendar page is not visible properly

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by debo19 — APPROVED** [review]
LGTM 🎉 Thanks @YashKamboj

**Comment by debo19** [comment]
@YashKamboj  Can you link the PR to the issue number it fixes?

**Comment by YashKamboj** [comment]
@debo19 i didn't saw it was already a issue and a pr , i was just surfing through the website when i saw it, should i delete this pr??

**Comment by YashKamboj** [comment]
I think i will close the pr!!

**Comment by debo19** [comment]
oh, right I didn't see the pr either. Yeah, it was done first, let's give that a shot :)

**Comment by leecalcote** [comment]
"A" for effort anyway, though, @YashKamboj. 😄

**Pull request closed without merging**
