### PR TITLE
Chore: how dark mode works

### PR DESCRIPTION
**Pull request by Musab1258**
**Description**

This pr adds to the readme.md of the repo, a short explanation of the light and dark mode on the website

This PR fixes #

fixes issue #922

**Notes for Reviewers**

@leecalcote did I get it right, or I still need to change some things.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 

Video of the changes I made

[screen-capture (2).webm](https://user-images.githubusercontent.com/67251181/208289507-6df24386-f929-464d-9be6-8858671c42b8.webm)

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks. @eeshaanSA @UtkarshMishra12 @Krishna2323 @tinniaru3005 @debo19

**Review by Krishna2323 — COMMENTED** [review]
@Musab1258, thanks for this. I will let you know about this.

**Comment by eeshaanSA** [comment]
Lgtm

**Review by eeshaanSA — DISMISSED** [review]
Lgtm🚀

**Comment by tinniaru3005** [comment]
LGTM ✅

**Review by UtkarshMishra12 — DISMISSED** [review]
LGTM! 🌟🙌 @Musab1258

**Comment by UtkarshMishra12** [comment]
@Musab1258 DCO is failing. Can you please follow these steps [Link](https://github.com/meshery/meshery.io/pull/937/checks?check_run_id=10215821482)

or
To add your Signed-off-by line to every commit in this branch:

Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: **git rebase HEAD~8 --signoff**
Force push your changes to overwrite the branch: **git push --force-with-lease origin chore-how-dark-mode-works**

**Comment by Musab1258** [comment]
@UtkarshMishra12, DCO checks had passed.

**Comment by leecalcote** [comment]
@Musab1258 you'll need to only include your commits. Resync your fork in order to avoid having commits from other people show up in your PR.

**Comment by UtkarshMishra12** [comment]
> @Musab1258 you'll need to only include your commits. Resync your fork in order to avoid having commits from other people show up in your PR.

@Musab1258 Please follow these steps 🚀

**Comment by Musab1258** [comment]
@leecalcote, I am not getting this right.

I guess I will have to delete this fork, create another fork and start making the pull requests again.

**Comment by leecalcote** [comment]
@Musab1258, yes, perhaps so. Although, before you do, please understand that what you've outlined in this PR is how a user can switch between light and dark mode. If we have to explain this to the user, all is lost.

Rather, what the original issue is requesting is developer-facing documentation of how to contribute (code) to the meshery.io website under the newly created dark mode theme. This entails describing how CSS works on the site and how to ensure that style considerations are made for both light and dark mode. 

I'll let you close this PR and rethink your approach to the original issue. If it seems daunting or the request remains a bit confusing, don't sweat it. Unassign yourself from the issue, and let's find you another issue to work on. You can do a PR review when another contributor opens a PR against the original issue, if you do choose to remove assignment.

**Comment by Musab1258** [comment]
Thanks @leecalcote. Please, let me give it a last shot, if I don't get it by the 31st of december, I will unassign myself.

**Pull request closed without merging**
