### PR TITLE
[Improvement] - Updated Gifs with the top bar and Meshery URL

### PR DESCRIPTION
**Pull request by adithyaakrishna**
Signed-off-by: Adithya Krishna <aadithya794@gmail.com>

**Description**

This PR updates the gifs with top bar which also has Meshery URL at top

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
Hold Up, Small Change Pending

**Comment by leecalcote** [comment]
😬

**Comment by warunicorn19** [comment]
The quality is really taking a toll

**Comment by leecalcote** [comment]
the chrome doesn't help. the blurry url only exacerbates the affect of the gif looking of poor quality.

**Comment by warunicorn19** [comment]
GitHub has really upped it's game in terms of image preview, wow.

**Comment by adithyaakrishna** [comment]
Ohhh, Wait Why is it compressing 😶

**Comment by adithyaakrishna** [comment]
Found the issue, the top bar screenshot shared by @warunicorn19 yesterday is of lower PPI range and was taken from his PC. While the gifs were recorded in @leecalcote 's PC which IMO is a iMac with higher resolution. Premier Pro is trying to match the source sequence settings for both the assets (the top frame and older gifs)

**Comment by warunicorn19** [comment]
actually, the gifs have also been shot on my laptop

**Comment by adithyaakrishna** [comment]
This is kinda what is happening in our case, https://community.adobe.com/t5/premiere-pro-discussions/creating-best-possible-quality-gifs/td-p/10314399

I'll have a look at this and try to get some solution for the issue

**Pull request closed without merging**
