### PR TITLE
[Integration] some logos are in colour and some are in white in Dark mode

### LINKED ISSUE #932: In Dark mode, some logos of the integrations are in color. It should be white similar to the dark mode of the layer5.io site
#### Description

In Dark mode, some logos of the integrations are in color. It should be white similar to the dark mode of the layer5.io site.

#### Expected Behavior

All logos should be white.

#### Screenshots

https://user-images.githubusercontent.com/67385503/205699663-340c2ac9-a7f7-4e76-b361-5dc074998506.mp4

#### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Yashsharma1911**
**Description**

This PR fixes #932
1. Fixed problem: some logos in the integration are in color and some are in white in Dark mode
2. Now all logos are in color in Dark mode and in Light mode

**Current state**

Screenshot 2023-01-13 at 3 10 56 PM

**Desired State**

https://user-images.githubusercontent.com/71271069/212288166-ccd4044a-6332-4de3-962d-25d10fd379da.mov

**Notes for Reviewers**
Please check commits if any suggestion let me know

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Shivam-AfA — COMMENTED** [review]
Hey, great work here @Yashsharma1911. However, if you go through the conversation on the corresponding issue i.e. #932, it was being discussed that adding a white stroke to each of the icons for the dark mode would be useful. (Although it was experimental, still we could give it a shot). So I ask @leecalcote to confirm this.

**Review by GaganpreetKaurKalsi — COMMENTED** [review]
Colorful icons in dark mode look really good. But the contrast is too low in case of some icons(eg. cortex, istio) that it is hard to see.

**Comment by Yashsharma1911** [comment]
Okay, then @Shivam-AfA let me try adding a white stroke to every icon just to confirm should I go with this @leecalcote

**Comment by leecalcote** [comment]
> Okay, then @Shivam-AfA let me try adding a white stroke to every icon just to confirm should I go with this @leecalcote

I'd like to see that.

**Comment by Yashsharma1911** [comment]
I added white strokes to some icons, but due to icon's small size, it made them lose their original look. I would suggest It's better to use either all white or original logo

with strokes
Screenshot 2023-01-14 at 1 45 48 PM


without strokes
Screenshot 2023-01-14 at 1 48 28 PM

**Comment by Shivam-AfA** [comment]
> I added white strokes to some icons, but due to icon's small size, it made them lose their original look. I would suggest It's better to use either all white or original logo
> 
> with strokes Screenshot 2023-01-14 at 1 45 48 PM
> 
> without strokes Screenshot 2023-01-14 at 1 48 28 PM

I think you made the stroke width too thick. Try thinning it down @Yashsharma1911

**Comment by leecalcote** [comment]
Thanks. A white stroke should only be added to the color version of the icon. The consideration here is for use only the colored icon and the proposal to allow us to get there is to use a white stroke on the outside of the colored icon.

**Comment by Yashsharma1911** [comment]
Hey, @leecalcote I have a feeling it's fairly complicated involving generating the SVG, querying it with Javascript to get the outline only outside of the SVG icon, then applying the results. If there is an easier non-JS way, I'd love to know or we can create an outline of SVG icon manually by tools like Figma or other and then add them

**Comment by Shivam-AfA** [comment]
@Yashsharma1911 There's a stroke styling property that you can add to the SVG file code. It'll add a stroke to the desired paths. You can also set the desired stroke width.

**Comment by eeshaanSA** [comment]
@Yashsharma1911 it would be great if you could show us your progress today in the Websites Meeting.

**Comment by Yashsharma1911** [comment]
Hey @eeshaanSA I can't join meet today although I am trying to add outline manually in image svg code file if you have better solution to automate this it will be helpful

**Comment by Yashsharma1911** [comment]
Hey @Shivam-AfA @GaganpreetKaurKalsi  have added an outline outside of the icon let me know if that is good I will add this style in all of them

Screenshot 2023-01-17 at 12 02 41 AM

**Comment by Shivam-AfA** [comment]
Great job @Yashsharma1911. Except for the first one, others look fine to me. This creates a doubt for the other integration icons as well. I guess some would be hard to identify.
What are your thoughts on this experiment?
@leecalcote @GaganpreetKaurKalsi

**Review by GaganpreetKaurKalsi — COMMENTED** [review]
I second what @Shivam-AfA said. The icons with dull color would be still hard to recognize even if we add a white outline to them.

**Comment by leecalcote** [comment]
If the stroke is being added with CSS, I would like to see a preview of what the page looks like with all color icons having this white stroke.

**Comment by leecalcote** [comment]
@Yashsharma1911, by the way.... you've done some good work here already.

**Comment by Yashsharma1911** [comment]
Hey, @leecalcote  I tried to use CSS to add strokes outside of icons, but I was having trouble because icons do not have a consistent shape. As a result, some of the icons are losing their original shape when I apply the CSS. This is making it difficult for me to achieve the desired styling.

that's why I added strokes to icons manually via Figma let me know If I can do it in CSS because I tried but I couldn't find any solution for it

**Comment by leecalcote** [comment]
@Yashsharma1911 here you are: https://stackoverflow.com/questions/18330344/how-to-add-border-outline-stroke-to-svg-elements-in-css

**Comment by leecalcote** [comment]
@Yashsharma1911 checking back in... what do you think

**Comment by Yashsharma1911** [comment]
> @Yashsharma1911 checking back in... what do you think?

Hey @leecalcote sorry for late reply I will give you update on it today

**Comment by Yashsharma1911** [comment]
Hey @Lee and @Shivam-AfA I used 3 approaches to add borders only outside of SVG via CSS but non of them worked because icons have different paths and shapes. Only an approach with a clip-path works a little, but problem with a clip-path is we need to define path for the outline of icon and this approach does not work for every icon because every icon has a different path. That's why I can not show you that in the preview phase

So what do you say? I am also thinking to post it on slack so if someone can help

**Comment by leecalcote** [comment]
@Yashsharma1911, for certain, post on discuss.layer5.io or in slack, yes.

Have you tried using a radial gradient (from light in the center to dark on the outside) in the background of the cell/card containing the logo?

We discussed this on yesterday's Websites meeting, which we missed you at (again).

**Comment by leecalcote** [comment]
@Yashsharma1911 example - https://github.com/meshery/meshery.io/pull/1010

**Comment by leecalcote** [comment]
@Yashsharma1911 I tossed in a potential solution. 

Let's get this done.

**Comment by Yashsharma1911** [comment]
Hey, I didn't use that approach actually but it looks good so for confirmation we will be adding a radial gradient(from light in the center to dark on the outside) in middle and using color icons in dark mode and light mode will be as it is, correct me if I am wrong

**Comment by Yashsharma1911** [comment]
Hey @leecalcote check it out now and let me know if there are any changes that need to be made

**Review by leecalcote — CHANGES_REQUESTED** [review]
Ensure that this lighten radial gradient only affects dark mode.

**Comment by Yashsharma1911** [comment]
Yes it is only affecting dark mode not light mode

https://user-images.githubusercontent.com/71271069/217518173-95c2cda9-8459-465c-b1ea-b09e14ef4ac7.mov

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
