### PR TITLE
#939 Unwanted white background in bee icon

### PR DESCRIPTION
**Pull request by Musab1258**
Signed-off-by: Musab Habeeb <habeebmusab@gmail.com>

**Description**

This pr fixes the white bacground that appears in the ebpf logo in the catalog page of the meshery website when in dark mode.

This PR fixes #

fixes issue #939 

**Notes for Reviewers**

I modified the existing ebpf logo to remove the white background. 

**Videoes / Screenshots**

Before

ebpf-before

After

ebpf-after

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Musab1258** [comment]
@leecalcote, it seems that I got it right now.

**Review by leecalcote — APPROVED** [review]
Yes, I think you did…

**Comment by Musab1258** [comment]
@leecalcote, thanks.

**Comment by leecalcote** [comment]
Yay, @Musab1258! 🎈

**Pull request merged**
