### PR TITLE
Made visible consul icon of catalog filters compatibility section in light mode

### LINKED ISSUE #1013: [UI] Consul Icon is not visible in light mode
### Description
on page, [meshery.io/catalog](https://meshery.io/catalog) in compatibility section `Consul` icon is not visible because of its white color

https://user-images.githubusercontent.com/71271069/218055328-c732975b-c063-4b5f-ad58-5fd5ce06eb67.mov

### Expected Behavior
it should only contain color `Consul` svg

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Yashsharma1911**
Signed-off-by: yash sharma <yashsharma2572@gmail.com>

**Description**
Consul icon is now visible in light mode also

This PR fixes #1013

https://user-images.githubusercontent.com/71271069/218142865-ae0604ca-e981-40f1-80e5-c324037ba7aa.mov

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Yashsharma1911** [comment]
Hey @Shivam-AfA check this PR let me know if there is any changes

**Review by Shivam-AfA — APPROVED** [review]
Looks good to me. 🚀

**Comment by Yashsharma1911** [comment]
Hey @Nikhil-Ladha this is a small change and I think it is ready to merge

**Comment by Nikhil-Ladha** [comment]
I am not exactly sure how we are checking for the current theme on the meshery.io site, though if you have gone through the code and figured out that then do you mind updating the kuma logo to its white version in dark mode?

**Comment by Avi-88** [comment]
> I am not exactly sure how we are checking for the current theme on the meshery.io site, though if you have gone through the code and figured out that then do you mind updating the kuma logo to its white version in dark mode?

Hi @Nikhil-Ladha , I don't think  we are checking the theme for changing logos. Currently the logos remain the same for both  modes , this PR just replaces the white consul logo with the colored one. [This](https://github.com/meshery/meshery.io/issues/1016) issue also needs to address the same problem of switching logos according to mode, do let me know if you want me to  look into addressing a proper fix for this ,thanks

**Comment by Nikhil-Ladha** [comment]
> > I am not exactly sure how we are checking for the current theme on the meshery.io site, though if you have gone through the code and figured out that then do you mind updating the kuma logo to its white version in dark mode?
> 
> Hi @Nikhil-Ladha , I don't think we are checking the theme for changing logos. Currently the logos remain the same for both modes , this PR just replaces the white consul logo with the colored one. [This](https://github.com/meshery/meshery.io/issues/1016) issue also needs to address the same problem of switching logos according to mode, do let me know if you want me to look into addressing a proper fix for this ,thanks

I think we have a system for that in place already becasue if you switch to themes on the home page you will notice that the "Meshery", "Patterns" logo changes based on the theme that the user is in.
It seems like we are using `data-*` attributes to do so, though not sure. Please do check it once.

**Comment by Avi-88** [comment]
Oh , you are right @Nikhil-Ladha , If I'm not wrong there was a discussion about whether to use all white logos or coloured logos in dark mode. Judging by the integrations page  on layer5 site I guess we went ahead with the coloured approach and only use white logos for the one's which don't really work with dark mode like the kuma one. I guess @Yashsharma1911 you can just update the kuma logo to switch between coloured and white using the `data-*` attribute as suggested by @Nikhil-Ladha

**Comment by Yashsharma1911** [comment]
sure let me look into it @Avi-88

**Comment by Chadha93** [comment]
merge conflicts @Yashsharma1911

**Pull request closed without merging**
