### PR TITLE
changed the colour for getting started

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chaterjee <speak2adi@gmail.com>

**Description**
This adds a different colour to the getting started area and makes the hover on icons a little smoother.
This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
We'll want to remove or recolor the small section between the presentation and Getting Started sections.
Screen Shot 2021-09-06 at 4 18 27 PM

**Comment by warunicorn19** [comment]
Alright, i think we could just remove it, will probably look better.

**Comment by warunicorn19** [comment]
Screenshot 2021-09-07 at 6 19 49 PM

@leecalcote does this look okay?

**Comment by leecalcote** [comment]
Unfortunately, no, I don't think so. Let's set this aside for the time being. Need to focus time on bugs in Meshery.

**Comment by warunicorn19** [comment]
Screenshot 2021-09-19 at 5 34 12 PM

Deploy not working for some reason, I've not made any changes to the color, just added some space in between the icons and made the transition of the icons smoother.

**Comment by warunicorn19** [comment]
okay deploy working again, just had to re-deploy.

**Comment by warunicorn19** [comment]
@leecalcote looking for a merge here.

**Review by leecalcote — APPROVED** [review]
Good to go.

**Pull request merged**
