### PR TITLE
Fixed mobile responsiveness of home page

### LINKED ISSUE #671: Fix mobile responsiveness of home page
**Description**
On the home page of meshery.io:

The "full catalog" link becomes too small in mobile view.
Screenshot 2022-02-08 at 2 19 16 AM

The button is not mobile-friendly.
Screenshot 2022-02-08 at 2 18 11 AM

**Expected Behavior**

1. Make the link the same size as the rest of the text in mobile view.
2. Make the button mobile responsive. 

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by marpit19**
Signed-off-by: Arpit Mohapatra [arpit.mohapatra19@gmail.com](mailto:arpit.mohapatra19@gmail.com)

**Description**

This PR fixes #671

**Notes for Reviewers**
- Fixed Screenshots

Screenshot from 2022-02-08 19-17-06

Screenshot from 2022-02-08 19-17-28

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by YashKamboj — CHANGES_REQUESTED** [review]
I think you left this part @marpit19 
Screenshot (215)

**Comment by marpit19** [comment]
> I think you left this part @marpit19 Screenshot (215)

oops!! I'll fix that too

**Comment by marpit19** [comment]
@YashKamboj could you mention the dimension cause on my machine it's responsive

image

**Comment by YashKamboj** [comment]
@marpit19 Its not showing for me now also 😅, if you are here why don't you make all these button uniform, with equal width
Screenshot (216)

**Comment by marpit19** [comment]
> @marpit19 Its not showing for me now also 😅, if you are here why don't you make all these button uniform, with equal width Screenshot (216)

I guess right now if someone could review and push this for now. I have some office work so if I got any free time for sure I would do it

**Review by warunicorn19 — APPROVED** [review]
LGTM, Thank you @marpit19

**Pull request merged**
